export const LOAN_READINESS_PERMISSIONS = Object.freeze({
  VIEW: 'loanReadiness.view',
  VIEW_DASHBOARD: 'loanReadiness.viewDashboard',
  MANAGE_CONFIGURATION: 'loanReadiness.manageConfiguration',
  CREATE_ASSESSMENT: 'loanReadiness.createAssessment',
  CALCULATE_ASSESSMENT: 'loanReadiness.calculateAssessment',
  REVIEW_ASSESSMENT: 'loanReadiness.reviewAssessment',
  APPROVE_ASSESSMENT: 'loanReadiness.approveAssessment',
  CREATE_LOAN_REQUEST: 'loanReadiness.createLoanRequest',
  CALCULATE_DEBT_CAPACITY: 'loanReadiness.calculateDebtCapacity',
  RUN_STRESS_TESTS: 'loanReadiness.runStressTests',
  MANAGE_COVENANTS: 'loanReadiness.manageCovenants',
  RUN_AI: 'loanReadiness.runAICommentary',
  REVIEW_AI: 'loanReadiness.reviewAICommentary',
  GENERATE_LENDER_PACKAGE: 'loanReadiness.generateLenderPackage',
  EXPORT: 'loanReadiness.export',
  VIEW_AUDIT: 'loanReadiness.viewAudit',
});
