/**
 * CRM automation catalogue — Phase 13 Wave 4 foundations.
 * Small approved trigger set only. No full sequences. No arbitrary code.
 */

export {
  CRM_AUTOMATION_TRIGGER,
  CRM_AUTOMATION_TRIGGERS,
  CRM_AUTOMATION_RULE_STATUS,
  CRM_AUTOMATION_RULE_STATUSES,
  CRM_AUTOMATION_EXECUTION_STATUS,
  CRM_AUTOMATION_EXECUTION_STATUSES,
} from '../catalogue.js';

export const CRM_AUTOMATION_DEFINITION_VERSION = 'crm-automation-v1-2026-07-30';

/** Approved action kinds only — never eval / scripts. */
export const CRM_AUTOMATION_ACTION = Object.freeze({
  CREATE_FIRST_CONTACT_TASK: 'CREATE_FIRST_CONTACT_TASK',
  CREATE_CHECKLIST_TASK: 'CREATE_CHECKLIST_TASK',
  EMIT_NO_NEXT_ACTION_WARNING: 'EMIT_NO_NEXT_ACTION_WARNING',
});

export const CRM_AUTOMATION_ACTIONS = Object.freeze(Object.values(CRM_AUTOMATION_ACTION));

export const APPROVED_TRIGGER_ACTIONS = Object.freeze({
  LEAD_ASSIGNED: [CRM_AUTOMATION_ACTION.CREATE_FIRST_CONTACT_TASK],
  OPPORTUNITY_STAGE_ENTRY: [CRM_AUTOMATION_ACTION.CREATE_CHECKLIST_TASK],
  NO_NEXT_ACTION_WARNING: [CRM_AUTOMATION_ACTION.EMIT_NO_NEXT_ACTION_WARNING],
});
