export const DESKTOP_CODES = {
  SYNC_REQUIRED: 'DESKTOP_SYNC_REQUIRED',
  ONLINE_ONLY: 'DESKTOP_ONLINE_ONLY',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  DEVICE_BOUND: 'DEVICE_ALREADY_BOUND',
  NOT_BOUND: 'DEVICE_NOT_BOUND',
};
