/**
 * Pipeline catalogue constants — Phase 12 Wave 1 + Wave 4.
 * Pipeline stages ≠ Lead statuses ≠ analytics-pipeline.
 */

export const CRM_PIPELINE_DEFINITION_VERSION = 'crm-pipeline-new-business-v1-2026-07-30';
export const CRM_PIPELINE_EXPANSION_VERSION = 'crm-pipeline-expansion-v1-2026-07-30';
export const CRM_PIPELINE_MRA_EIS_VERSION = 'crm-pipeline-mra-eis-v1-2026-07-30';

export const CRM_PIPELINE_CODE = Object.freeze({
  NEW_BUSINESS: 'NEW_BUSINESS',
  EXPANSION: 'EXPANSION',
  MRA_EIS: 'MRA_EIS',
});

export const CRM_PIPELINE_CODES = Object.freeze(Object.values(CRM_PIPELINE_CODE));

export const CRM_PIPELINE_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  DRAFT: 'DRAFT',
  RETIRED: 'RETIRED',
});

export const CRM_PIPELINE_STAGE = Object.freeze({
  OPPORTUNITY_IDENTIFIED: 'OPPORTUNITY_IDENTIFIED',
  DISCOVERY: 'DISCOVERY',
  NEED_CONFIRMED: 'NEED_CONFIRMED',
  SOLUTION_FIT: 'SOLUTION_FIT',
  COMMERCIAL_SCOPING: 'COMMERCIAL_SCOPING',
  DECISION_PROCESS: 'DECISION_PROCESS',
  PROPOSAL_READY: 'PROPOSAL_READY',
  CUSTOMER_DECISION: 'CUSTOMER_DECISION',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
});

/** Ordered open → terminal stages (stable codes). */
export const CRM_PIPELINE_STAGES_ORDERED = Object.freeze([
  CRM_PIPELINE_STAGE.OPPORTUNITY_IDENTIFIED,
  CRM_PIPELINE_STAGE.DISCOVERY,
  CRM_PIPELINE_STAGE.NEED_CONFIRMED,
  CRM_PIPELINE_STAGE.SOLUTION_FIT,
  CRM_PIPELINE_STAGE.COMMERCIAL_SCOPING,
  CRM_PIPELINE_STAGE.DECISION_PROCESS,
  CRM_PIPELINE_STAGE.PROPOSAL_READY,
  CRM_PIPELINE_STAGE.CUSTOMER_DECISION,
  CRM_PIPELINE_STAGE.CLOSED_WON,
  CRM_PIPELINE_STAGE.CLOSED_LOST,
]);

export const CRM_PIPELINE_TERMINAL_STAGES = Object.freeze([
  CRM_PIPELINE_STAGE.CLOSED_WON,
  CRM_PIPELINE_STAGE.CLOSED_LOST,
]);

export const CRM_OPPORTUNITY_STATUS = Object.freeze({
  OPEN: 'OPEN',
  WON: 'WON',
  LOST: 'LOST',
  /** Wave 4 — controlled merge loser */
  MERGED: 'MERGED',
});

export const CRM_OPPORTUNITY_NUMBER_RE = /^OPP-\d{4}-\d{6}$/;

export const CRM_HANDOFF_TYPE_OPPORTUNITY = 'CRM_OPPORTUNITY_HANDOFF';
