/**
 * CRM catalogue — Phase 11 Wave 1–4 + Phase 12 Wave 1 Pipeline/Opportunity constants.
 * CrmLead ≠ Opportunity ≠ Customer ≠ SupportTicket ≠ CsCase.
 * Never store Tenant GL, payment secrets, or MRA credentials.
 * Score ≠ probability / conversion chance / expected revenue.
 * Opportunity readiness (Phase 11) never creates Opportunity; Phase 12 create does.
 */

export const CRM_DEFINITION_VERSION = 'crm-core-wave4-2026-07-30';
export const CRM_WAVE4_DEFINITION_VERSION = 'crm-core-wave4-2026-07-30';
export const CRM_RECON_VERSION = 'crm-recon-v1';
export const CRM_EXPORT_VERSION = 'crm-export-v1';

/** Canonical Lead statuses (Wave 1 — prefer over simplified Wave 0 sketch). */
export const CRM_LEAD_STATUS = Object.freeze({
  NEW: 'NEW',
  UNASSIGNED: 'UNASSIGNED',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  ATTEMPTING_CONTACT: 'ATTEMPTING_CONTACT',
  CONTACTED: 'CONTACTED',
  ENGAGED: 'ENGAGED',
  QUALIFICATION_IN_PROGRESS: 'QUALIFICATION_IN_PROGRESS',
  QUALIFIED: 'QUALIFIED',
  NURTURE: 'NURTURE',
  ON_HOLD: 'ON_HOLD',
  DISQUALIFIED: 'DISQUALIFIED',
  OPPORTUNITY_READY: 'OPPORTUNITY_READY',
  CONVERTED_TO_OPPORTUNITY: 'CONVERTED_TO_OPPORTUNITY',
  DUPLICATE: 'DUPLICATE',
  MERGED: 'MERGED',
  SPAM: 'SPAM',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_LEAD_STATUSES = Object.freeze(Object.values(CRM_LEAD_STATUS));

/** Early / terminal-ish exits (evidence preserved in history). */
export const CRM_TERMINALISH_STATUSES = Object.freeze([
  CRM_LEAD_STATUS.DISQUALIFIED,
  CRM_LEAD_STATUS.DUPLICATE,
  CRM_LEAD_STATUS.MERGED,
  CRM_LEAD_STATUS.SPAM,
  CRM_LEAD_STATUS.CANCELLED,
  CRM_LEAD_STATUS.ARCHIVED,
  CRM_LEAD_STATUS.CONVERTED_TO_OPPORTUNITY,
]);

export const CRM_LEAD_TYPE = Object.freeze({
  NEW_BUSINESS: 'NEW_BUSINESS',
  DEMO_REQUEST: 'DEMO_REQUEST',
  EXPANSION: 'EXPANSION',
  PARTNER: 'PARTNER',
  OTHER: 'OTHER',
});

export const CRM_LEAD_TYPES = Object.freeze(Object.values(CRM_LEAD_TYPE));

export const CRM_PERSON_OR_ORG = Object.freeze({
  PERSON: 'PERSON',
  ORGANISATION: 'ORGANISATION',
});

export const CRM_LEAD_SOURCE = Object.freeze({
  MANUAL: 'MANUAL',
  WEB_FORM: 'WEB_FORM',
  REFERRAL: 'REFERRAL',
  CS_HANDOFF: 'CS_HANDOFF',
  SUPPORT_HANDOFF: 'SUPPORT_HANDOFF',
  PRODUCT: 'PRODUCT',
  IMPORT: 'IMPORT',
  OTHER: 'OTHER',
  /** Wave 2 capture source codes (also valid on Lead.source) */
  WEBSITE_CONTACT_FORM: 'WEBSITE_CONTACT_FORM',
  REQUEST_DEMO: 'REQUEST_DEMO',
  START_TRIAL: 'START_TRIAL',
  SALES_ENQUIRY: 'SALES_ENQUIRY',
  CUSTOMER_SUCCESS_HANDOFF: 'CUSTOMER_SUCCESS_HANDOFF',
  PRODUCT_SIGNAL: 'PRODUCT_SIGNAL',
});

export const CRM_LEAD_SOURCES = Object.freeze(Object.values(CRM_LEAD_SOURCE));

/** Distinct public / handoff capture source codes (Wave 2). */
export const CRM_CAPTURE_SOURCE = Object.freeze({
  WEBSITE_CONTACT_FORM: 'WEBSITE_CONTACT_FORM',
  REQUEST_DEMO: 'REQUEST_DEMO',
  START_TRIAL: 'START_TRIAL',
  SALES_ENQUIRY: 'SALES_ENQUIRY',
  CUSTOMER_SUCCESS_HANDOFF: 'CUSTOMER_SUCCESS_HANDOFF',
  SUPPORT_HANDOFF: 'SUPPORT_HANDOFF',
  PRODUCT_SIGNAL: 'PRODUCT_SIGNAL',
});

export const CRM_CAPTURE_SOURCES = Object.freeze(Object.values(CRM_CAPTURE_SOURCE));

export const CRM_PUBLIC_CAPTURE_SOURCES = Object.freeze([
  CRM_CAPTURE_SOURCE.WEBSITE_CONTACT_FORM,
  CRM_CAPTURE_SOURCE.REQUEST_DEMO,
  CRM_CAPTURE_SOURCE.START_TRIAL,
  CRM_CAPTURE_SOURCE.SALES_ENQUIRY,
]);

export const CRM_HANDOFF_CAPTURE_SOURCES = Object.freeze([
  CRM_CAPTURE_SOURCE.CUSTOMER_SUCCESS_HANDOFF,
  CRM_CAPTURE_SOURCE.SUPPORT_HANDOFF,
  CRM_CAPTURE_SOURCE.PRODUCT_SIGNAL,
]);

/**
 * Source channels. Wave 1 create uses ADMIN_MANUAL only.
 * Wave 2: WEB_FORM + INTERNAL_HANDOFF available for capture.
 * EMAIL / WHATSAPP remain NOT_AVAILABLE (ingest deferred).
 */
export const CRM_SOURCE_CHANNEL = Object.freeze({
  ADMIN_MANUAL: 'ADMIN_MANUAL',
  EMAIL: 'EMAIL',
  WHATSAPP: 'WHATSAPP',
  WEB_FORM: 'WEB_FORM',
  /** @deprecated prefer INTERNAL_HANDOFF */
  HANDOFF: 'HANDOFF',
  INTERNAL_HANDOFF: 'INTERNAL_HANDOFF',
});

export const CRM_CHANNEL_AVAILABILITY = Object.freeze({
  [CRM_SOURCE_CHANNEL.ADMIN_MANUAL]: 'AVAILABLE',
  [CRM_SOURCE_CHANNEL.EMAIL]: 'NOT_AVAILABLE',
  [CRM_SOURCE_CHANNEL.WHATSAPP]: 'NOT_AVAILABLE',
  [CRM_SOURCE_CHANNEL.WEB_FORM]: 'AVAILABLE',
  [CRM_SOURCE_CHANNEL.HANDOFF]: 'AVAILABLE',
  [CRM_SOURCE_CHANNEL.INTERNAL_HANDOFF]: 'AVAILABLE',
});

export const CRM_CONSENT_STATUS = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  GRANTED: 'GRANTED',
  DENIED: 'DENIED',
  WITHDRAWN: 'WITHDRAWN',
  EXPIRED: 'EXPIRED',
  PENDING: 'PENDING',
  NOT_REQUIRED: 'NOT_REQUIRED',
});

export const CRM_CONSENT_STATUSES = Object.freeze(Object.values(CRM_CONSENT_STATUS));

/** Consent purposes (Wave 3). Never infer GRANTED from presence of email/phone. */
export const CRM_CONSENT_PURPOSE = Object.freeze({
  SALES_CONTACT: 'SALES_CONTACT',
  DEMO_COMMUNICATION: 'DEMO_COMMUNICATION',
  /** Phase 14 Wave 4 — recording governance; UNKNOWN ≠ GRANTED */
  DEMO_RECORDING: 'DEMO_RECORDING',
  MARKETING_EMAIL: 'MARKETING_EMAIL',
  MARKETING_WHATSAPP: 'MARKETING_WHATSAPP',
});

export const CRM_CONSENT_PURPOSES = Object.freeze(Object.values(CRM_CONSENT_PURPOSE));

export const CRM_COMMUNICATION_CHANNEL = Object.freeze({
  EMAIL: 'EMAIL',
  CALL: 'CALL',
  WHATSAPP: 'WHATSAPP',
  SMS: 'SMS',
});

export const CRM_COMMUNICATION_CHANNELS = Object.freeze(
  Object.values(CRM_COMMUNICATION_CHANNEL)
);

export const CRM_DNC_FLAG = Object.freeze({
  DO_NOT_EMAIL: 'DO_NOT_EMAIL',
  DO_NOT_CALL: 'DO_NOT_CALL',
  DO_NOT_WHATSAPP: 'DO_NOT_WHATSAPP',
  DO_NOT_SMS: 'DO_NOT_SMS',
  DO_NOT_CONTACT_ALL: 'DO_NOT_CONTACT_ALL',
});

export const CRM_DNC_FLAGS = Object.freeze(Object.values(CRM_DNC_FLAG));

/** Qualification response states — UNKNOWN ≠ NO. */
export const CRM_QUALIFICATION_RESPONSE = Object.freeze({
  YES: 'YES',
  NO: 'NO',
  PARTIAL: 'PARTIAL',
  UNKNOWN: 'UNKNOWN',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
});

export const CRM_QUALIFICATION_RESPONSES = Object.freeze(
  Object.values(CRM_QUALIFICATION_RESPONSE)
);

export const CRM_QUALIFICATION_DEFINITION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
  SUPERSEDED: 'SUPERSEDED',
});

export const CRM_DEFAULT_QUALIFICATION_VERSION_ID = 'qual-small-business-standard-v1';

export const CRM_SCORE_CONFIDENCE = Object.freeze({
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INSUFFICIENT: 'INSUFFICIENT',
});

export const CRM_SCORE_CONFIDENCES = Object.freeze(Object.values(CRM_SCORE_CONFIDENCE));

export const CRM_SCORE_BAND = Object.freeze({
  COLD: 'COLD',
  WARM: 'WARM',
  HOT: 'HOT',
  BLOCKED: 'BLOCKED',
});

export const CRM_SCORE_BANDS = Object.freeze(Object.values(CRM_SCORE_BAND));

export const CRM_DEFAULT_SCORE_VERSION_ID = 'score-lead-fit-v1';

/** Forbidden labels — never use in API/UI for scores. */
export const CRM_SCORE_FORBIDDEN_LABELS = Object.freeze([
  'probability',
  'conversion chance',
  'expected revenue',
  'win probability',
  'conversion probability',
]);

export const CRM_ASSIGNMENT_STRATEGY = Object.freeze({
  MANUAL: 'MANUAL',
  ROUND_ROBIN: 'ROUND_ROBIN',
  TERRITORY_BASED: 'TERRITORY_BASED',
});

export const CRM_ASSIGNMENT_STRATEGIES = Object.freeze(
  Object.values(CRM_ASSIGNMENT_STRATEGY)
);

export const CRM_ASSIGNMENT_ACTION = Object.freeze({
  ASSIGN: 'ASSIGN',
  ACCEPT: 'ACCEPT',
  REJECT: 'REJECT',
  RETURN_TO_QUEUE: 'RETURN_TO_QUEUE',
  REASSIGN: 'REASSIGN',
});

export const CRM_ASSIGNMENT_ACTIONS = Object.freeze(Object.values(CRM_ASSIGNMENT_ACTION));

export const CRM_TERRITORY_MATCH = Object.freeze({
  COUNTRY: 'COUNTRY',
  REGION: 'REGION',
  ACCOUNT_TYPE: 'ACCOUNT_TYPE',
  LEAD_TYPE: 'LEAD_TYPE',
});

export const CRM_TERRITORY_MATCHES = Object.freeze(Object.values(CRM_TERRITORY_MATCH));

export const CRM_DUPLICATE_STATUS = Object.freeze({
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  LIKELY_DUPLICATE: 'LIKELY_DUPLICATE',
  CONFIRMED_DUPLICATE: 'CONFIRMED_DUPLICATE',
  CONFIRMED_DISTINCT: 'CONFIRMED_DISTINCT',
});

export const CRM_DUPLICATE_STATUSES = Object.freeze(Object.values(CRM_DUPLICATE_STATUS));

export const CRM_DUPLICATE_MATCH_TYPE = Object.freeze({
  SOURCE_IDENTITY: 'SOURCE_IDENTITY',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  HANDOFF_REF: 'HANDOFF_REF',
  /** Low-confidence suggestion only — never auto-merge */
  DOMAIN: 'DOMAIN',
});

export const CRM_CAPTURE_MAX_PAYLOAD_BYTES = 32_768;
export const CRM_CAPTURE_MAX_MESSAGE_CHARS = 8_000;

/** Wave 4 — note visibility (API-enforced; never CSS-only). */
export const CRM_NOTE_VISIBILITY = Object.freeze({
  INTERNAL: 'INTERNAL',
  RESTRICTED: 'RESTRICTED',
});

export const CRM_NOTE_VISIBILITIES = Object.freeze(Object.values(CRM_NOTE_VISIBILITY));

/** Wave 4 — tasks (foundations; no full sales sequences). */
export const CRM_TASK_STATUS = Object.freeze({
  TODO: 'TODO',
  COMPLETED: 'COMPLETED',
});

export const CRM_TASK_STATUSES = Object.freeze(Object.values(CRM_TASK_STATUS));

export const CRM_SUBJECT_TYPE = Object.freeze({
  LEAD: 'LEAD',
  ACCOUNT: 'ACCOUNT',
  CONTACT: 'CONTACT',
  /** Phase 12 Wave 3 — Opportunity-scoped tasks / timeline */
  OPPORTUNITY: 'OPPORTUNITY',
  /** Phase 13 Wave 1 — Activity as note/timeline subject (projections stay one Activity) */
  ACTIVITY: 'ACTIVITY',
  /** Phase 14 Wave 1 — Demo as Meeting/timeline subject (Demo ≠ Meeting) */
  DEMO: 'DEMO',
});

export const CRM_SUBJECT_TYPES = Object.freeze(Object.values(CRM_SUBJECT_TYPE));

/** Phase 13 Wave 1 — canonical Activity types (parent + typed children). */
export const CRM_ACTIVITY_TYPE = Object.freeze({
  TASK: 'TASK',
  FOLLOW_UP: 'FOLLOW_UP',
  NOTE: 'NOTE',
  /** Wave 2+ — catalogue reserved; not creatable via Wave 1 channel modules */
  CALL: 'CALL',
  EMAIL: 'EMAIL',
  MEETING: 'MEETING',
});

export const CRM_ACTIVITY_TYPES = Object.freeze(Object.values(CRM_ACTIVITY_TYPE));

/** Wave 1 creatable Activity types. */
export const CRM_ACTIVITY_TYPES_WAVE1 = Object.freeze([
  CRM_ACTIVITY_TYPE.TASK,
  CRM_ACTIVITY_TYPE.FOLLOW_UP,
  CRM_ACTIVITY_TYPE.NOTE,
]);

/** Wave 2 creatable Activity types (Calls + Email SMTP). */
export const CRM_ACTIVITY_TYPES_WAVE2 = Object.freeze([
  CRM_ACTIVITY_TYPE.CALL,
  CRM_ACTIVITY_TYPE.EMAIL,
]);

/** Wave 3 creatable Activity types (Meetings + Calendar). */
export const CRM_ACTIVITY_TYPES_WAVE3 = Object.freeze([
  CRM_ACTIVITY_TYPE.MEETING,
]);

/** All creatable Activity types through Wave 3. */
export const CRM_ACTIVITY_TYPES_CREATABLE = Object.freeze([
  ...CRM_ACTIVITY_TYPES_WAVE1,
  ...CRM_ACTIVITY_TYPES_WAVE2,
  ...CRM_ACTIVITY_TYPES_WAVE3,
]);

/** Phase 13 Wave 2 — Call child statuses (manual/planned; telephony NOT_AVAILABLE). */
export const CRM_CALL_STATUS = Object.freeze({
  PLANNED: 'PLANNED',
  OPEN: 'OPEN',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
});

export const CRM_CALL_STATUSES = Object.freeze(Object.values(CRM_CALL_STATUS));

/** Manual call outcomes — never invent telephony CONNECTED/recording. */
export const CRM_CALL_OUTCOME = Object.freeze({
  NO_ANSWER: 'NO_ANSWER',
  LEFT_VOICEMAIL: 'LEFT_VOICEMAIL',
  BUSY: 'BUSY',
  WRONG_NUMBER: 'WRONG_NUMBER',
  CALLBACK_REQUESTED: 'CALLBACK_REQUESTED',
  NOT_INTERESTED: 'NOT_INTERESTED',
  /** Manual claim only — not telephony CONNECTED */
  CONNECTED_MANUAL: 'CONNECTED_MANUAL',
  OTHER: 'OTHER',
});

export const CRM_CALL_OUTCOMES = Object.freeze(Object.values(CRM_CALL_OUTCOME));

export const CRM_TELEPHONY_PROVIDER_STATUS = 'NOT_AVAILABLE';
export const CRM_CALL_RECORDING_STATUS = 'NOT_AVAILABLE';

/** Phase 13 Wave 2 — Email Activity / send-request delivery honesty. */
export const CRM_EMAIL_ACTIVITY_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  READY: 'READY',
  SEND_REQUESTED: 'SEND_REQUESTED',
  ACCEPTED_BY_PROVIDER: 'ACCEPTED_BY_PROVIDER',
  SENT: 'SENT',
  FAILED: 'FAILED',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
  CANCELLED: 'CANCELLED',
});

export const CRM_EMAIL_ACTIVITY_STATUSES = Object.freeze(
  Object.values(CRM_EMAIL_ACTIVITY_STATUS)
);

export const CRM_EMAIL_SEND_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  ACCEPTED_BY_PROVIDER: 'ACCEPTED_BY_PROVIDER',
  SENT: 'SENT',
  FAILED: 'FAILED',
  /** Only with provider delivery evidence — never invent */
  DELIVERED: 'DELIVERED',
});

export const CRM_EMAIL_SEND_STATUSES = Object.freeze(
  Object.values(CRM_EMAIL_SEND_STATUS)
);

export const CRM_EMAIL_DELIVERY_EVENT = Object.freeze({
  ACCEPTED_BY_PROVIDER: 'ACCEPTED_BY_PROVIDER',
  SENT: 'SENT',
  FAILED: 'FAILED',
  DELIVERED: 'DELIVERED',
});

export const CRM_EMAIL_DELIVERY_EVENTS = Object.freeze(
  Object.values(CRM_EMAIL_DELIVERY_EVENT)
);

/** Versioned CRM email templates — no executable expressions. */
export const CRM_EMAIL_TEMPLATE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
});

export const CRM_EMAIL_TEMPLATE_STATUSES = Object.freeze(
  Object.values(CRM_EMAIL_TEMPLATE_STATUS)
);

export const CRM_ACTIVITY_STATUS = Object.freeze({
  PLANNED: 'PLANNED',
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
});

export const CRM_ACTIVITY_STATUSES = Object.freeze(Object.values(CRM_ACTIVITY_STATUS));

export const CRM_ACTIVITY_DIRECTION = Object.freeze({
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND',
  INTERNAL: 'INTERNAL',
  NONE: 'NONE',
});

export const CRM_ACTIVITY_DIRECTIONS = Object.freeze(
  Object.values(CRM_ACTIVITY_DIRECTION)
);

/**
 * Type ↔ status compatibility (fail-closed).
 * Planned ≠ completed by due date — COMPLETED only via explicit transition.
 */
export const CRM_ACTIVITY_TYPE_STATUS_COMPAT = Object.freeze({
  [CRM_ACTIVITY_TYPE.TASK]: Object.freeze([
    CRM_ACTIVITY_STATUS.PLANNED,
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.IN_PROGRESS,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
  ]),
  [CRM_ACTIVITY_TYPE.FOLLOW_UP]: Object.freeze([
    CRM_ACTIVITY_STATUS.PLANNED,
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
    CRM_ACTIVITY_STATUS.BLOCKED_BY_CONSENT,
  ]),
  [CRM_ACTIVITY_TYPE.NOTE]: Object.freeze([
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
  ]),
  [CRM_ACTIVITY_TYPE.CALL]: Object.freeze([
    CRM_ACTIVITY_STATUS.PLANNED,
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
    CRM_ACTIVITY_STATUS.BLOCKED_BY_CONSENT,
  ]),
  [CRM_ACTIVITY_TYPE.EMAIL]: Object.freeze([
    CRM_ACTIVITY_STATUS.PLANNED,
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
    CRM_ACTIVITY_STATUS.BLOCKED_BY_CONSENT,
  ]),
  [CRM_ACTIVITY_TYPE.MEETING]: Object.freeze([
    CRM_ACTIVITY_STATUS.PLANNED,
    CRM_ACTIVITY_STATUS.OPEN,
    CRM_ACTIVITY_STATUS.COMPLETED,
    CRM_ACTIVITY_STATUS.CANCELLED,
  ]),
});

export const CRM_ACTIVITY_RELATION_ROLE = Object.freeze({
  PRIMARY: 'PRIMARY',
  RELATED: 'RELATED',
});

export const CRM_FOLLOW_UP_STATUS = Object.freeze({
  PLANNED: 'PLANNED',
  OPEN: 'OPEN',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
});

export const CRM_FOLLOW_UP_STATUSES = Object.freeze(Object.values(CRM_FOLLOW_UP_STATUS));

/** Next-action honesty envelopes — never fabricate. */
export const CRM_NEXT_ACTION_STATUS = Object.freeze({
  VALID: 'VALID',
  MISSING: 'MISSING',
  OVERDUE: 'OVERDUE',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CRM_NEXT_ACTION_STATUSES = Object.freeze(
  Object.values(CRM_NEXT_ACTION_STATUS)
);

/** Wave 4 — merge request lifecycle (SoD: requester ≠ approver). */
export const CRM_MERGE_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXECUTED: 'EXECUTED',
  CANCELLED: 'CANCELLED',
});

export const CRM_MERGE_STATUSES = Object.freeze(Object.values(CRM_MERGE_STATUS));

export const CRM_MERGE_ENTITY = Object.freeze({
  LEAD: 'LEAD',
  ACCOUNT: 'ACCOUNT',
  CONTACT: 'CONTACT',
  /** Phase 12 Wave 4 — Opportunity merge SoD */
  OPPORTUNITY: 'OPPORTUNITY',
});

export const CRM_MERGE_ENTITIES = Object.freeze(Object.values(CRM_MERGE_ENTITY));

/**
 * Opportunity readiness checklist outcome.
 * READY may transition Lead → OPPORTUNITY_READY; never creates Opportunity.
 */
export const CRM_READINESS_STATUS = Object.freeze({
  NOT_READY: 'NOT_READY',
  PARTIALLY_READY: 'PARTIALLY_READY',
  READY: 'READY',
  READY_WITH_WARNINGS: 'READY_WITH_WARNINGS',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  DUPLICATE_REVIEW_REQUIRED: 'DUPLICATE_REVIEW_REQUIRED',
  BLOCKED: 'BLOCKED',
  /** Phase 20 — UNKNOWN never passes as READY */
  UNKNOWN: 'UNKNOWN',
  /** Phase 15 Wave 4 — Closed-Won conversion handoff already emitted (payload only) */
  HANDED_OFF: 'HANDED_OFF',
});

export const CRM_READINESS_STATUSES = Object.freeze(Object.values(CRM_READINESS_STATUS));

export const CRM_FOUNDATION_KIND = Object.freeze({
  IMPORT: 'IMPORT',
  REPORTING: 'REPORTING',
  EMAIL_INGEST: 'EMAIL_INGEST',
  WHATSAPP_INGEST: 'WHATSAPP_INGEST',
  OPPORTUNITY_PIPELINE: 'OPPORTUNITY_PIPELINE',
  /** Phase 13 Waves 1–4 — Activity spine (READY when Wave 4 honesty delivered) */
  ACTIVITY_SPINE: 'ACTIVITY_SPINE',
  /** Phase 14 Wave 1 — Demo Request + Demo spine (FOUNDATION until Wave 4 exit) */
  DEMO_SPINE: 'DEMO_SPINE',
  /** Phase 15 Waves 1–4 — Commercial document spine */
  COMMERCIAL_SPINE: 'COMMERCIAL_SPINE',
});

/** Phase 13 Wave 4 — Reminder delivery channels (≠ Sales contact Activity). */
export const CRM_REMINDER_CHANNEL = Object.freeze({
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL',
});

export const CRM_REMINDER_CHANNELS = Object.freeze(Object.values(CRM_REMINDER_CHANNEL));

export const CRM_REMINDER_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  QUEUED: 'QUEUED',
  DELIVERED: 'DELIVERED',
  SNOOZED: 'SNOOZED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
});

export const CRM_REMINDER_STATUSES = Object.freeze(Object.values(CRM_REMINDER_STATUS));

/** Phase 14 Wave 2 — Demo Agenda/Script/Scenario/Content version statuses (SoD to ACTIVE). */
export const CRM_DEMO_VERSION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
  REJECTED: 'REJECTED',
});

export const CRM_DEMO_VERSION_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_VERSION_STATUS)
);

/** Phase 14 Wave 2 — content classification (RESTRICTED never on Customer/invitation). */
export const CRM_DEMO_CONTENT_CLASSIFICATION = Object.freeze({
  CUSTOMER_SAFE: 'CUSTOMER_SAFE',
  INTERNAL: 'INTERNAL',
  RESTRICTED: 'RESTRICTED',
});

export const CRM_DEMO_CONTENT_CLASSIFICATIONS = Object.freeze(
  Object.values(CRM_DEMO_CONTENT_CLASSIFICATION)
);

export const CRM_DEMO_CONTENT_KIND = Object.freeze({
  SLIDE_PACK: 'SLIDE_PACK',
  HANDOUT: 'HANDOUT',
  VIDEO_REF: 'VIDEO_REF',
  OTHER: 'OTHER',
});

export const CRM_DEMO_CONTENT_KINDS = Object.freeze(
  Object.values(CRM_DEMO_CONTENT_KIND)
);

/** Projection surfaces for Demo content (fail-closed for RESTRICTED). */
export const CRM_DEMO_PROJECTION_SURFACE = Object.freeze({
  INTERNAL: 'INTERNAL',
  CUSTOMER: 'CUSTOMER',
  INVITATION: 'INVITATION',
});

export const CRM_DEMO_PROJECTION_SURFACES = Object.freeze(
  Object.values(CRM_DEMO_PROJECTION_SURFACE)
);

/** Phase 14 Wave 3 — Logical Demo Environment lifecycle (≠ MRA EIS sandbox / Production Tenant). */
export const CRM_DEMO_ENVIRONMENT_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  PROVISIONING: 'PROVISIONING',
  READY: 'READY',
  UNHEALTHY: 'UNHEALTHY',
  EXPIRED: 'EXPIRED',
  DEPROVISIONED: 'DEPROVISIONED',
  REJECTED: 'REJECTED',
});

export const CRM_DEMO_ENVIRONMENT_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_ENVIRONMENT_STATUS)
);

export const CRM_DEMO_ENVIRONMENT_HEALTH = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  HEALTHY: 'HEALTHY',
  UNHEALTHY: 'UNHEALTHY',
  EXPIRED: 'EXPIRED',
});

export const CRM_DEMO_ENVIRONMENT_HEALTHS = Object.freeze(
  Object.values(CRM_DEMO_ENVIRONMENT_HEALTH)
);

/** Safe data-pack source kinds — Production / credential sources rejected. */
export const CRM_DEMO_DATA_PACK_SOURCE_KIND = Object.freeze({
  SYNTHETIC: 'SYNTHETIC',
  FIXTURE: 'FIXTURE',
  SANITISED_TEMPLATE: 'SANITISED_TEMPLATE',
});

export const CRM_DEMO_DATA_PACK_SOURCE_KINDS = Object.freeze(
  Object.values(CRM_DEMO_DATA_PACK_SOURCE_KIND)
);

export const CRM_DEMO_CHECKLIST_EXECUTION_STATUS = Object.freeze({
  IN_PROGRESS: 'IN_PROGRESS',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
});

export const CRM_DEMO_CHECKLIST_EXECUTION_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_CHECKLIST_EXECUTION_STATUS)
);

export const CRM_DEMO_REHEARSAL_OUTCOME = Object.freeze({
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  PARTIAL: 'PARTIAL',
});

export const CRM_DEMO_REHEARSAL_OUTCOMES = Object.freeze(
  Object.values(CRM_DEMO_REHEARSAL_OUTCOME)
);

export const CRM_DEMO_ISSUE_SEVERITY = Object.freeze({
  CRITICAL: 'CRITICAL',
  WARN: 'WARN',
  INFO: 'INFO',
});

export const CRM_DEMO_ISSUE_SEVERITIES = Object.freeze(
  Object.values(CRM_DEMO_ISSUE_SEVERITY)
);

/** Phase 13 Wave 4 — Activity/Task templates (versioned; ACTIVE not directly editable). */
export const CRM_ACTIVITY_TEMPLATE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
});

export const CRM_ACTIVITY_TEMPLATE_STATUSES = Object.freeze(
  Object.values(CRM_ACTIVITY_TEMPLATE_STATUS)
);

export const CRM_ACTIVITY_TEMPLATE_KIND = Object.freeze({
  ACTIVITY: 'ACTIVITY',
  TASK: 'TASK',
  FOLLOW_UP: 'FOLLOW_UP',
  CHECKLIST: 'CHECKLIST',
});

export const CRM_ACTIVITY_TEMPLATE_KINDS = Object.freeze(
  Object.values(CRM_ACTIVITY_TEMPLATE_KIND)
);

/** Phase 13 Wave 4 — small approved automation trigger set only. */
export const CRM_AUTOMATION_TRIGGER = Object.freeze({
  LEAD_ASSIGNED: 'LEAD_ASSIGNED',
  OPPORTUNITY_STAGE_ENTRY: 'OPPORTUNITY_STAGE_ENTRY',
  NO_NEXT_ACTION_WARNING: 'NO_NEXT_ACTION_WARNING',
});

export const CRM_AUTOMATION_TRIGGERS = Object.freeze(Object.values(CRM_AUTOMATION_TRIGGER));

export const CRM_AUTOMATION_RULE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  DISABLED: 'DISABLED',
  REJECTED: 'REJECTED',
});

export const CRM_AUTOMATION_RULE_STATUSES = Object.freeze(
  Object.values(CRM_AUTOMATION_RULE_STATUS)
);

export const CRM_AUTOMATION_EXECUTION_STATUS = Object.freeze({
  SUCCESS: 'SUCCESS',
  SKIPPED: 'SKIPPED',
  FAILED: 'FAILED',
  IDEMPOTENT_REPLAY: 'IDEMPOTENT_REPLAY',
});

export const CRM_AUTOMATION_EXECUTION_STATUSES = Object.freeze(
  Object.values(CRM_AUTOMATION_EXECUTION_STATUS)
);

/** Phase 13 Wave 4 — Activity report honesty envelopes. */
export const CRM_ACTIVITY_REPORT_STATUS = Object.freeze({
  READY: 'READY',
  EMPTY: 'EMPTY',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CRM_ACTIVITY_REPORT_SCHEDULE_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
});

export const CRM_FOUNDATION_STATUS = Object.freeze({
  FOUNDATION: 'FOUNDATION',
  /** Wave 4 — Opportunity import / reporting / pipeline planes when honestly delivered */
  READY: 'READY',
  NOT_AVAILABLE: 'NOT_AVAILABLE',
});

export const CRM_RELIABILITY_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  PARTIAL_HISTORY: 'PARTIAL_HISTORY',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  NOT_INSTRUMENTED: 'NOT_INSTRUMENTED',
  PERMISSION_RESTRICTED: 'PERMISSION_RESTRICTED',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CRM_TIMELINE_EVENT_TYPE = Object.freeze({
  STATUS_CHANGE: 'STATUS_CHANGE',
  NOTE_ADDED: 'NOTE_ADDED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  ASSIGNMENT: 'ASSIGNMENT',
  SCORE_EVALUATED: 'SCORE_EVALUATED',
  QUALIFICATION: 'QUALIFICATION',
  CONSENT: 'CONSENT',
  MERGE_REQUESTED: 'MERGE_REQUESTED',
  MERGE_APPROVED: 'MERGE_APPROVED',
  MERGE_EXECUTED: 'MERGE_EXECUTED',
  READINESS_EVALUATED: 'READINESS_EVALUATED',
  CAPTURE: 'CAPTURE',
  SYSTEM: 'SYSTEM',
  /** Phase 12 Wave 3 Opportunity plane */
  STAGE_CHANGE: 'STAGE_CHANGE',
  CLOSED_WON: 'CLOSED_WON',
  CLOSED_LOST: 'CLOSED_LOST',
  REOPENED: 'REOPENED',
  RISK_EVALUATED: 'RISK_EVALUATED',
  PROPOSAL_READINESS: 'PROPOSAL_READINESS',
  CONVERSION_READINESS: 'CONVERSION_READINESS',
  /** Phase 13 Wave 1 Activity plane */
  ACTIVITY_CREATED: 'ACTIVITY_CREATED',
  ACTIVITY_STATUS_CHANGED: 'ACTIVITY_STATUS_CHANGED',
  FOLLOW_UP_CREATED: 'FOLLOW_UP_CREATED',
  FOLLOW_UP_COMPLETED: 'FOLLOW_UP_COMPLETED',
  FOLLOW_UP_RESCHEDULED: 'FOLLOW_UP_RESCHEDULED',
  TASK_REOPENED: 'TASK_REOPENED',
  /** Phase 13 Wave 2 Call / Email plane */
  CALL_PLANNED: 'CALL_PLANNED',
  CALL_LOGGED: 'CALL_LOGGED',
  CALL_COMPLETED: 'CALL_COMPLETED',
  EMAIL_DRAFT_CREATED: 'EMAIL_DRAFT_CREATED',
  EMAIL_SEND_REQUESTED: 'EMAIL_SEND_REQUESTED',
  EMAIL_SENT: 'EMAIL_SENT',
  EMAIL_FAILED: 'EMAIL_FAILED',
  /** Phase 13 Wave 3 Meeting / Calendar plane */
  MEETING_CREATED: 'MEETING_CREATED',
  MEETING_RESCHEDULED: 'MEETING_RESCHEDULED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
  MEETING_ATTENDANCE_RECORDED: 'MEETING_ATTENDANCE_RECORDED',
  /** Phase 14 Wave 1 Demo plane */
  DEMO_REQUEST_CREATED: 'DEMO_REQUEST_CREATED',
  DEMO_REQUEST_QUALIFIED: 'DEMO_REQUEST_QUALIFIED',
  DEMO_REQUEST_REJECTED: 'DEMO_REQUEST_REJECTED',
  DEMO_REQUEST_CONVERTED: 'DEMO_REQUEST_CONVERTED',
  DEMO_CREATED: 'DEMO_CREATED',
  DEMO_STATUS_CHANGED: 'DEMO_STATUS_CHANGED',
  DEMO_SCHEDULED: 'DEMO_SCHEDULED',
  DEMO_READINESS_EVALUATED: 'DEMO_READINESS_EVALUATED',
  DEMO_PARTICIPANT_ADDED: 'DEMO_PARTICIPANT_ADDED',
  DEMO_PARTICIPANT_REMOVED: 'DEMO_PARTICIPANT_REMOVED',
  DEMO_ENVIRONMENT_REQUESTED: 'DEMO_ENVIRONMENT_REQUESTED',
  DEMO_ENVIRONMENT_APPROVED: 'DEMO_ENVIRONMENT_APPROVED',
  DEMO_ENVIRONMENT_PROVISIONED: 'DEMO_ENVIRONMENT_PROVISIONED',
  DEMO_ENVIRONMENT_RESET: 'DEMO_ENVIRONMENT_RESET',
  DEMO_ENVIRONMENT_DEPROVISIONED: 'DEMO_ENVIRONMENT_DEPROVISIONED',
  DEMO_CHECKLIST_EXECUTED: 'DEMO_CHECKLIST_EXECUTED',
  DEMO_REHEARSAL_RECORDED: 'DEMO_REHEARSAL_RECORDED',
  /** Phase 14 Wave 4 */
  DEMO_DELIVERY_STARTED: 'DEMO_DELIVERY_STARTED',
  DEMO_DELIVERY_ENDED: 'DEMO_DELIVERY_ENDED',
  DEMO_ATTENDANCE_RECORDED: 'DEMO_ATTENDANCE_RECORDED',
  DEMO_RECORDING_GOV: 'DEMO_RECORDING_GOV',
  DEMO_FEEDBACK_RECORDED: 'DEMO_FEEDBACK_RECORDED',
  DEMO_OUTCOME_RECORDED: 'DEMO_OUTCOME_RECORDED',
  DEMO_FOLLOW_UP_CREATED: 'DEMO_FOLLOW_UP_CREATED',
  DEMO_PROPOSAL_HANDOFF: 'DEMO_PROPOSAL_HANDOFF',
  DEMO_TRIAL_HANDOFF: 'DEMO_TRIAL_HANDOFF',
  DEMO_REPORT_RUN: 'DEMO_REPORT_RUN',
  /** Phase 15 Wave 1 — commercial / proposal request plane */
  PROPOSAL_REQUEST_CREATED: 'PROPOSAL_REQUEST_CREATED',
  PROPOSAL_REQUEST_QUALIFIED: 'PROPOSAL_REQUEST_QUALIFIED',
  PROPOSAL_REQUEST_REJECTED: 'PROPOSAL_REQUEST_REJECTED',
  PROPOSAL_REQUEST_CONVERTED: 'PROPOSAL_REQUEST_CONVERTED',
  COMMERCIAL_DOCUMENT_CREATED: 'COMMERCIAL_DOCUMENT_CREATED',
  COMMERCIAL_DOCUMENT_STATUS_CHANGED: 'COMMERCIAL_DOCUMENT_STATUS_CHANGED',
  COMMERCIAL_DOCUMENT_VERSION_CREATED: 'COMMERCIAL_DOCUMENT_VERSION_CREATED',
  /** Phase 15 Wave 2 — pricing / approvals */
  PRICE_BOOK_CREATED: 'PRICE_BOOK_CREATED',
  PRICE_BOOK_VERSION_ACTIVATED: 'PRICE_BOOK_VERSION_ACTIVATED',
  COMMERCIAL_PRICING_CALCULATED: 'COMMERCIAL_PRICING_CALCULATED',
  COMMERCIAL_APPROVAL_SUBMITTED: 'COMMERCIAL_APPROVAL_SUBMITTED',
  COMMERCIAL_APPROVAL_DECIDED: 'COMMERCIAL_APPROVAL_DECIDED',
  COMMERCIAL_APPROVAL_INVALIDATED: 'COMMERCIAL_APPROVAL_INVALIDATED',
  DISCOUNT_REQUEST_CREATED: 'DISCOUNT_REQUEST_CREATED',
  /** Phase 15 Wave 4 — Closed-Won readiness + Phase 16 handoff + commercial reports */
  CLOSED_WON_READINESS: 'CLOSED_WON_READINESS',
  CLOSED_WON_CONVERSION_HANDOFF: 'CLOSED_WON_CONVERSION_HANDOFF',
  COMMERCIAL_REPORT_RUN: 'COMMERCIAL_REPORT_RUN',
});

/**
 * @param {string} channel
 * @returns {'AVAILABLE'|'NOT_AVAILABLE'|'UNKNOWN'}
 */
export function channelAvailability(channel) {
  const key = String(channel || '').toUpperCase();
  return CRM_CHANNEL_AVAILABILITY[key] || 'UNKNOWN';
}

export const CRM_ACCOUNT_TYPE = Object.freeze({
  PROSPECT: 'PROSPECT',
  CUSTOMER: 'CUSTOMER',
  PARTNER: 'PARTNER',
  OTHER: 'OTHER',
});

export const CRM_ACCOUNT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_CONTACT_ROLE = Object.freeze({
  PRIMARY: 'PRIMARY',
  DECISION_MAKER: 'DECISION_MAKER',
  INFLUENCER: 'INFLUENCER',
  OTHER: 'OTHER',
});

/**
 * Transition table (v1). Keys = fromStatus; values = allowed toStatus list.
 *
 * Notes:
 * - Create always starts NEW (not a transition).
 * - Happy path: NEW → ASSIGNED → ACCEPTED → ATTEMPTING_CONTACT → CONTACTED
 *   → QUALIFICATION_IN_PROGRESS → QUALIFIED → OPPORTUNITY_READY
 * - CONVERTED_TO_OPPORTUNITY only from OPPORTUNITY_READY / QUALIFIED via Opportunity
 *   create success path (stateMachine requires fromOpportunityCreate).
 * - DISQUALIFIED requires disqualificationReason at assert time.
 */
export const CRM_TRANSITION_TABLE = Object.freeze({
  [CRM_LEAD_STATUS.NEW]: Object.freeze([
    CRM_LEAD_STATUS.UNASSIGNED,
    CRM_LEAD_STATUS.ASSIGNED,
    CRM_LEAD_STATUS.DISQUALIFIED,
    CRM_LEAD_STATUS.DUPLICATE,
    CRM_LEAD_STATUS.SPAM,
    CRM_LEAD_STATUS.CANCELLED,
    CRM_LEAD_STATUS.MERGED,
  ]),
  [CRM_LEAD_STATUS.UNASSIGNED]: Object.freeze([
    CRM_LEAD_STATUS.ASSIGNED,
    CRM_LEAD_STATUS.DISQUALIFIED,
    CRM_LEAD_STATUS.DUPLICATE,
    CRM_LEAD_STATUS.SPAM,
    CRM_LEAD_STATUS.CANCELLED,
  ]),
  [CRM_LEAD_STATUS.ASSIGNED]: Object.freeze([
    CRM_LEAD_STATUS.ACCEPTED,
    CRM_LEAD_STATUS.UNASSIGNED,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.DISQUALIFIED,
    CRM_LEAD_STATUS.DUPLICATE,
    CRM_LEAD_STATUS.CANCELLED,
  ]),
  [CRM_LEAD_STATUS.ACCEPTED]: Object.freeze([
    CRM_LEAD_STATUS.ATTEMPTING_CONTACT,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.ATTEMPTING_CONTACT]: Object.freeze([
    CRM_LEAD_STATUS.CONTACTED,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.CONTACTED]: Object.freeze([
    CRM_LEAD_STATUS.ENGAGED,
    CRM_LEAD_STATUS.QUALIFICATION_IN_PROGRESS,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.ENGAGED]: Object.freeze([
    CRM_LEAD_STATUS.QUALIFICATION_IN_PROGRESS,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.QUALIFICATION_IN_PROGRESS]: Object.freeze([
    CRM_LEAD_STATUS.QUALIFIED,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.QUALIFIED]: Object.freeze([
    CRM_LEAD_STATUS.OPPORTUNITY_READY,
    CRM_LEAD_STATUS.CONVERTED_TO_OPPORTUNITY,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.NURTURE]: Object.freeze([
    CRM_LEAD_STATUS.ASSIGNED,
    CRM_LEAD_STATUS.ACCEPTED,
    CRM_LEAD_STATUS.ATTEMPTING_CONTACT,
    CRM_LEAD_STATUS.QUALIFICATION_IN_PROGRESS,
    CRM_LEAD_STATUS.DISQUALIFIED,
  ]),
  [CRM_LEAD_STATUS.ON_HOLD]: Object.freeze([
    CRM_LEAD_STATUS.ASSIGNED,
    CRM_LEAD_STATUS.ACCEPTED,
    CRM_LEAD_STATUS.ATTEMPTING_CONTACT,
    CRM_LEAD_STATUS.CONTACTED,
    CRM_LEAD_STATUS.QUALIFICATION_IN_PROGRESS,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.DISQUALIFIED,
    CRM_LEAD_STATUS.CANCELLED,
  ]),
  [CRM_LEAD_STATUS.OPPORTUNITY_READY]: Object.freeze([
    CRM_LEAD_STATUS.CONVERTED_TO_OPPORTUNITY,
    CRM_LEAD_STATUS.NURTURE,
    CRM_LEAD_STATUS.ON_HOLD,
    CRM_LEAD_STATUS.DISQUALIFIED,
    CRM_LEAD_STATUS.ARCHIVED,
  ]),
  [CRM_LEAD_STATUS.DISQUALIFIED]: Object.freeze([CRM_LEAD_STATUS.ARCHIVED]),
  [CRM_LEAD_STATUS.DUPLICATE]: Object.freeze([CRM_LEAD_STATUS.ARCHIVED]),
  [CRM_LEAD_STATUS.MERGED]: Object.freeze([]),
  [CRM_LEAD_STATUS.SPAM]: Object.freeze([]),
  [CRM_LEAD_STATUS.CANCELLED]: Object.freeze([CRM_LEAD_STATUS.ARCHIVED]),
  [CRM_LEAD_STATUS.ARCHIVED]: Object.freeze([]),
  [CRM_LEAD_STATUS.CONVERTED_TO_OPPORTUNITY]: Object.freeze([]),
});

export const CRM_LEAD_NUMBER_RE = /^LEAD-\d{4}-\d{6}$/;
export const CRM_ACCOUNT_NUMBER_RE = /^ACC-\d{4}-\d{6}$/;
export const CRM_CONTACT_NUMBER_RE = /^CON-\d{4}-\d{6}$/;
export const CRM_OPPORTUNITY_NUMBER_RE = /^OPP-\d{4}-\d{6}$/;
export const CRM_ACTIVITY_NUMBER_RE = /^ACT-\d{4}-\d{6}$/;
export const CRM_TASK_NUMBER_RE = /^TASK-\d{4}-\d{6}$/;
export const CRM_CALL_NUMBER_RE = /^CALL-\d{4}-\d{6}$/;
export const CRM_MEETING_NUMBER_RE = /^MEET-\d{4}-\d{6}$/;
export const CRM_DEMO_REQUEST_NUMBER_RE = /^DMR-\d{4}-\d{6}$/;
export const CRM_DEMO_NUMBER_RE = /^DEMO-\d{4}-\d{6}$/;
export const CRM_DEMO_ENVIRONMENT_NUMBER_RE = /^DENV-\d{4}-\d{6}$/;
/** Phase 15 Wave 1 — commercial document numbers */
export const CRM_PROPOSAL_REQUEST_NUMBER_RE = /^PRQ-\d{4}-\d{6}$/;
export const CRM_PROPOSAL_NUMBER_RE = /^PROP-\d{4}-\d{6}$/;
export const CRM_QUOTATION_NUMBER_RE = /^QUO-\d{4}-\d{6}$/;
export const CRM_PRICE_BOOK_NUMBER_RE = /^PB-\d{4}-\d{6}$/;
/** Phase 16 Wave 1 — conversion request / conversion numbers */
export const CRM_CONVERSION_REQUEST_NUMBER_RE = /^CVR-\d{4}-\d{6}$/;
export const CRM_CONVERSION_NUMBER_RE = /^CVN-\d{4}-\d{6}$/;

/** Phase 17 Wave 1 — onboarding request / project numbers */
export const ONBOARDING_REQUEST_NUMBER_RE = /^ONR-\d{4}-\d{6}$/;
export const ONBOARDING_PROJECT_NUMBER_RE = /^ONB-\d{4}-\d{6}$/;

/** Phase 14 Wave 1 — Demo Request statuses. Convert ≠ Opportunity create. */
export const CRM_DEMO_REQUEST_STATUS = Object.freeze({
  NEW: 'NEW',
  QUALIFYING: 'QUALIFYING',
  QUALIFIED: 'QUALIFIED',
  CONVERTED: 'CONVERTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_DEMO_REQUEST_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_REQUEST_STATUS)
);

/** Phase 14 Wave 1 — Demo statuses. Meeting COMPLETED ⇏ Demo DELIVERED. */
export const CRM_DEMO_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PLANNED: 'PLANNED',
  SCHEDULED: 'SCHEDULED',
  READY_TO_DELIVER: 'READY_TO_DELIVER',
  /** Wave 4 — reserved; not creatable via Wave 1 transitions */
  IN_DELIVERY: 'IN_DELIVERY',
  DELIVERED: 'DELIVERED',
  OUTCOME_RECORDED: 'OUTCOME_RECORDED',
  FOLLOW_UP_PENDING: 'FOLLOW_UP_PENDING',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_DEMO_STATUSES = Object.freeze(Object.values(CRM_DEMO_STATUS));

/** Wave 1 creatable / transitionable Demo statuses (delivery plane deferred). */
export const CRM_DEMO_STATUSES_WAVE1 = Object.freeze([
  CRM_DEMO_STATUS.DRAFT,
  CRM_DEMO_STATUS.PLANNED,
  CRM_DEMO_STATUS.SCHEDULED,
  CRM_DEMO_STATUS.READY_TO_DELIVER,
  CRM_DEMO_STATUS.CANCELLED,
  CRM_DEMO_STATUS.ARCHIVED,
]);

/**
 * Demo status transition table (Wave 1 spine + Wave 4 delivery/outcome).
 * Meeting COMPLETED ⇏ Demo DELIVERED; outcome never auto-mutates Opportunity.
 */
export const CRM_DEMO_TRANSITION_TABLE = Object.freeze({
  [CRM_DEMO_STATUS.DRAFT]: Object.freeze([
    CRM_DEMO_STATUS.PLANNED,
    CRM_DEMO_STATUS.SCHEDULED,
    CRM_DEMO_STATUS.CANCELLED,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.PLANNED]: Object.freeze([
    CRM_DEMO_STATUS.SCHEDULED,
    CRM_DEMO_STATUS.CANCELLED,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.SCHEDULED]: Object.freeze([
    CRM_DEMO_STATUS.READY_TO_DELIVER,
    CRM_DEMO_STATUS.CANCELLED,
    CRM_DEMO_STATUS.NO_SHOW,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.READY_TO_DELIVER]: Object.freeze([
    CRM_DEMO_STATUS.IN_DELIVERY,
    CRM_DEMO_STATUS.CANCELLED,
    CRM_DEMO_STATUS.NO_SHOW,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.IN_DELIVERY]: Object.freeze([
    CRM_DEMO_STATUS.DELIVERED,
    CRM_DEMO_STATUS.CANCELLED,
    CRM_DEMO_STATUS.NO_SHOW,
  ]),
  [CRM_DEMO_STATUS.DELIVERED]: Object.freeze([
    CRM_DEMO_STATUS.OUTCOME_RECORDED,
    CRM_DEMO_STATUS.FOLLOW_UP_PENDING,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.OUTCOME_RECORDED]: Object.freeze([
    CRM_DEMO_STATUS.FOLLOW_UP_PENDING,
    CRM_DEMO_STATUS.ARCHIVED,
  ]),
  [CRM_DEMO_STATUS.FOLLOW_UP_PENDING]: Object.freeze([CRM_DEMO_STATUS.ARCHIVED]),
  [CRM_DEMO_STATUS.CANCELLED]: Object.freeze([CRM_DEMO_STATUS.ARCHIVED]),
  [CRM_DEMO_STATUS.NO_SHOW]: Object.freeze([CRM_DEMO_STATUS.ARCHIVED]),
  [CRM_DEMO_STATUS.ARCHIVED]: Object.freeze([]),
});

/** Phase 14 Wave 4 — source-backed Demo attendance (never from RSVP alone). */
export const CRM_DEMO_ATTENDANCE_STATUS = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  ATTENDED: 'ATTENDED',
  NO_SHOW: 'NO_SHOW',
  EXCUSED: 'EXCUSED',
});

export const CRM_DEMO_ATTENDANCE_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_ATTENDANCE_STATUS)
);

export const CRM_DEMO_ATTENDANCE_SOURCE = Object.freeze({
  AUTHORISED_CONFIRMATION: 'AUTHORISED_CONFIRMATION',
  MEETING_ATTENDANCE_PROJECTION: 'MEETING_ATTENDANCE_PROJECTION',
});

export const CRM_DEMO_ATTENDANCE_SOURCES = Object.freeze(
  Object.values(CRM_DEMO_ATTENDANCE_SOURCE)
);

/** Phase 14 Wave 4 — recording governance only; provider NOT_AVAILABLE. */
export const CRM_DEMO_RECORDING_GOV_STATUS = Object.freeze({
  OFF: 'OFF',
  REQUESTED: 'REQUESTED',
  CONSENT_PENDING: 'CONSENT_PENDING',
  CONSENT_GRANTED: 'CONSENT_GRANTED',
  CONSENT_DENIED: 'CONSENT_DENIED',
  APPROVED: 'APPROVED',
  DENIED: 'DENIED',
  PROVIDER_NOT_AVAILABLE: 'PROVIDER_NOT_AVAILABLE',
});

export const CRM_DEMO_RECORDING_GOV_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_RECORDING_GOV_STATUS)
);

/** Phase 14 Wave 4 — Demo outcome codes. ≠ win probability ≠ Closed Won. */
export const CRM_DEMO_OUTCOME_CODE = Object.freeze({
  POSITIVE: 'POSITIVE',
  NEUTRAL: 'NEUTRAL',
  NEGATIVE: 'NEGATIVE',
  NO_SHOW: 'NO_SHOW',
  RESCHEDULE_NEEDED: 'RESCHEDULE_NEEDED',
  OTHER: 'OTHER',
});

export const CRM_DEMO_OUTCOME_CODES = Object.freeze(
  Object.values(CRM_DEMO_OUTCOME_CODE)
);

/** Completeness ≠ success / ≠ outcome polarity. */
export const CRM_DEMO_OUTCOME_COMPLETENESS = Object.freeze({
  COMPLETE: 'COMPLETE',
  PARTIAL: 'PARTIAL',
  INCOMPLETE: 'INCOMPLETE',
});

export const CRM_DEMO_OUTCOME_COMPLETENESS_VALUES = Object.freeze(
  Object.values(CRM_DEMO_OUTCOME_COMPLETENESS)
);

export const CRM_DEMO_ISSUE_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  RESOLVED: 'RESOLVED',
  DEFERRED: 'DEFERRED',
});

export const CRM_DEMO_ISSUE_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_ISSUE_STATUS)
);

export const CRM_DEMO_QUESTION_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ANSWERED: 'ANSWERED',
  DEFERRED: 'DEFERRED',
});

export const CRM_DEMO_QUESTION_STATUSES = Object.freeze(
  Object.values(CRM_DEMO_QUESTION_STATUS)
);

export const CRM_DEMO_HANDOFF_TYPE = Object.freeze({
  PROPOSAL: 'PROPOSAL',
  TRIAL: 'TRIAL',
});

export const CRM_DEMO_HANDOFF_TYPES = Object.freeze(
  Object.values(CRM_DEMO_HANDOFF_TYPE)
);

export const CRM_DEMO_REPORT_STATUS = Object.freeze({
  READY: 'READY',
  EMPTY: 'EMPTY',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CRM_DEMO_REPORT_SCHEDULE_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
});

/** Phase 15 Wave 4 — Commercial report honesty envelopes. */
export const CRM_COMMERCIAL_REPORT_STATUS = Object.freeze({
  READY: 'READY',
  EMPTY: 'EMPTY',
  UNAVAILABLE: 'UNAVAILABLE',
});

export const CRM_COMMERCIAL_REPORT_SCHEDULE_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  DISABLED: 'DISABLED',
});

/** Phase 13 Wave 3 — Meeting child statuses. RSVP ≠ attendance. */
export const CRM_MEETING_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

export const CRM_MEETING_STATUSES = Object.freeze(Object.values(CRM_MEETING_STATUS));

export const CRM_MEETING_RSVP = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  TENTATIVE: 'TENTATIVE',
});

export const CRM_MEETING_RSVPS = Object.freeze(Object.values(CRM_MEETING_RSVP));

/** Attendance requires authorised confirmation — never from RSVP alone. */
export const CRM_MEETING_ATTENDANCE = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  ATTENDED: 'ATTENDED',
  NO_SHOW: 'NO_SHOW',
  EXCUSED: 'EXCUSED',
});

export const CRM_MEETING_ATTENDANCES = Object.freeze(
  Object.values(CRM_MEETING_ATTENDANCE)
);

export const CRM_MEETING_INVITATION_STATUS = Object.freeze({
  NOT_SENT: 'NOT_SENT',
  REQUESTED: 'REQUESTED',
  SENT: 'SENT',
  BLOCKED_BY_CONSENT: 'BLOCKED_BY_CONSENT',
});

export const CRM_MEETING_INVITATION_STATUSES = Object.freeze(
  Object.values(CRM_MEETING_INVITATION_STATUS)
);

export const CRM_MEETING_OUTCOME = Object.freeze({
  COMPLETED: 'COMPLETED',
  NO_SHOW: 'NO_SHOW',
  CANCELLED_BY_PROSPECT: 'CANCELLED_BY_PROSPECT',
  CANCELLED_BY_US: 'CANCELLED_BY_US',
  RESCHEDULED: 'RESCHEDULED',
  OTHER: 'OTHER',
});

export const CRM_MEETING_OUTCOMES = Object.freeze(Object.values(CRM_MEETING_OUTCOME));

/** Internal calendar conflict policy — server-side truth. */
export const CRM_CALENDAR_CONFLICT_POLICY = Object.freeze({
  BLOCK: 'BLOCK',
  WARN: 'WARN',
  ALLOW_WITH_REASON: 'ALLOW_WITH_REASON',
});

export const CRM_CALENDAR_CONFLICT_POLICIES = Object.freeze(
  Object.values(CRM_CALENDAR_CONFLICT_POLICY)
);

export const CRM_CALENDAR_VIEW = Object.freeze({
  DAY: 'day',
  WEEK: 'week',
  MONTH: 'month',
  AGENDA: 'agenda',
});

export const CRM_CALENDAR_VIEWS = Object.freeze(Object.values(CRM_CALENDAR_VIEW));

export const CRM_CALENDAR_VISIBILITY = Object.freeze({
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE',
});

export const CRM_CALENDAR_EVENT_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  CANCELLED: 'CANCELLED',
});

/** Google / Outlook sync — typed NOT_CONNECTED; never fabricate external Events. */
export const CRM_CALENDAR_INTEGRATION_STATUS = 'NOT_CONNECTED';

export const CRM_NUMBER_PREFIX = Object.freeze({
  LEAD: 'LEAD',
  ACC: 'ACC',
  CON: 'CON',
  OPP: 'OPP',
  ACT: 'ACT',
  TASK: 'TASK',
  CALL: 'CALL',
  MEET: 'MEET',
  /** Phase 14 Wave 1 */
  DMR: 'DMR',
  DEMO: 'DEMO',
  /** Phase 14 Wave 3 — Logical Demo Environment */
  DENV: 'DENV',
  /** Phase 15 Wave 1 — commercial documents */
  PRQ: 'PRQ',
  PROP: 'PROP',
  QUO: 'QUO',
  /** Phase 15 Wave 2 — Price Books */
  PB: 'PB',
  /** Phase 16 Wave 1 — conversion */
  CVR: 'CVR',
  CVN: 'CVN',
  /** Phase 17 Wave 1 — customer onboarding */
  ONR: 'ONR',
  ONB: 'ONB',
  /** Phase 18 Wave 1 — customer training */
  TRQ: 'TRQ',
  TRN: 'TRN',
  /** Phase 18 Wave 2 — cohorts / sessions */
  COH: 'COH',
  TRS: 'TRS',
  /** Phase 18 Wave 3 — certificates (IB-TRN-CERT-YYYY-######) */
  CERT: 'IB-TRN-CERT',
  /** Phase 19 Wave 1 — customer adoption */
  ADR: 'ADR',
  ADP: 'ADP',
});

export const CRM_LIST_MAX_LIMIT = 100;
export const CRM_LIST_DEFAULT_LIMIT = 50;
