/**
 * CRM Core — Phase 11–12 + Phase 13 Wave 1–4 Activity plane + Phase 14 Wave 1–2 Demo plane.
 * CrmLead ≠ Opportunity ≠ Customer ≠ SupportTicket ≠ CsCase.
 * Activity ≠ Audit Event ≠ Analytics Event; Task ≠ CsTask; Call ≠ telephony live dial.
 * CRM Email Activity ≠ Support threads; SMTP accept ≠ delivered.
 * Meeting RSVP ≠ attendance; Google/Outlook NOT_CONNECTED; ICS export only.
 * Reminder delivery ≠ Activity complete; automation SoD + small approved triggers only.
 * Demo ≠ Meeting ≠ Trial ≠ Proposal; Demo convert ≠ Opportunity create.
 * Demo Agenda/Script ACTIVE immutable; SoD approve; RESTRICTED Script never on Customer/invite.
 * Score ≠ probability / conversion chance / expected revenue.
 * Opportunity readiness (Phase 11) never creates Opportunity; Wave 1 create does.
 */

export {
  CRM_DEFINITION_VERSION,
  CRM_LEAD_STATUS,
  CRM_LEAD_STATUSES,
  CRM_TERMINALISH_STATUSES,
  CRM_LEAD_TYPE,
  CRM_LEAD_TYPES,
  CRM_PERSON_OR_ORG,
  CRM_LEAD_SOURCE,
  CRM_LEAD_SOURCES,
  CRM_CAPTURE_SOURCE,
  CRM_CAPTURE_SOURCES,
  CRM_PUBLIC_CAPTURE_SOURCES,
  CRM_HANDOFF_CAPTURE_SOURCES,
  CRM_SOURCE_CHANNEL,
  CRM_CHANNEL_AVAILABILITY,
  CRM_CONSENT_STATUS,
  CRM_CONSENT_STATUSES,
  CRM_CONSENT_PURPOSE,
  CRM_CONSENT_PURPOSES,
  CRM_COMMUNICATION_CHANNEL,
  CRM_COMMUNICATION_CHANNELS,
  CRM_DNC_FLAG,
  CRM_DNC_FLAGS,
  CRM_QUALIFICATION_RESPONSE,
  CRM_QUALIFICATION_RESPONSES,
  CRM_QUALIFICATION_DEFINITION_STATUS,
  CRM_DEFAULT_QUALIFICATION_VERSION_ID,
  CRM_SCORE_CONFIDENCE,
  CRM_SCORE_CONFIDENCES,
  CRM_SCORE_BAND,
  CRM_SCORE_BANDS,
  CRM_DEFAULT_SCORE_VERSION_ID,
  CRM_SCORE_FORBIDDEN_LABELS,
  CRM_ASSIGNMENT_STRATEGY,
  CRM_ASSIGNMENT_STRATEGIES,
  CRM_ASSIGNMENT_ACTION,
  CRM_ASSIGNMENT_ACTIONS,
  CRM_TERRITORY_MATCH,
  CRM_TERRITORY_MATCHES,
  CRM_DUPLICATE_STATUS,
  CRM_DUPLICATE_STATUSES,
  CRM_DUPLICATE_MATCH_TYPE,
  CRM_CAPTURE_MAX_PAYLOAD_BYTES,
  CRM_CAPTURE_MAX_MESSAGE_CHARS,
  CRM_ACCOUNT_TYPE,
  CRM_ACCOUNT_STATUS,
  CRM_CONTACT_ROLE,
  CRM_TRANSITION_TABLE,
  CRM_LEAD_NUMBER_RE,
  CRM_ACCOUNT_NUMBER_RE,
  CRM_CONTACT_NUMBER_RE,
  CRM_OPPORTUNITY_NUMBER_RE,
  CRM_NUMBER_PREFIX,
  CRM_LIST_MAX_LIMIT,
  CRM_LIST_DEFAULT_LIMIT,
  CRM_WAVE4_DEFINITION_VERSION,
  CRM_NOTE_VISIBILITY,
  CRM_NOTE_VISIBILITIES,
  CRM_TASK_STATUS,
  CRM_TASK_STATUSES,
  CRM_SUBJECT_TYPE,
  CRM_SUBJECT_TYPES,
  CRM_ACTIVITY_TYPE,
  CRM_ACTIVITY_TYPES,
  CRM_ACTIVITY_TYPES_WAVE1,
  CRM_ACTIVITY_TYPES_WAVE2,
  CRM_ACTIVITY_TYPES_WAVE3,
  CRM_ACTIVITY_TYPES_CREATABLE,
  CRM_ACTIVITY_STATUS,
  CRM_ACTIVITY_STATUSES,
  CRM_ACTIVITY_DIRECTION,
  CRM_ACTIVITY_DIRECTIONS,
  CRM_ACTIVITY_TYPE_STATUS_COMPAT,
  CRM_ACTIVITY_RELATION_ROLE,
  CRM_FOLLOW_UP_STATUS,
  CRM_FOLLOW_UP_STATUSES,
  CRM_NEXT_ACTION_STATUS,
  CRM_NEXT_ACTION_STATUSES,
  CRM_ACTIVITY_NUMBER_RE,
  CRM_TASK_NUMBER_RE,
  CRM_CALL_NUMBER_RE,
  CRM_MEETING_NUMBER_RE,
  CRM_DEMO_REQUEST_NUMBER_RE,
  CRM_DEMO_NUMBER_RE,
  CRM_DEMO_REQUEST_STATUS,
  CRM_DEMO_REQUEST_STATUSES,
  CRM_DEMO_STATUS,
  CRM_DEMO_STATUSES,
  CRM_DEMO_STATUSES_WAVE1,
  CRM_DEMO_TRANSITION_TABLE,
  CRM_MEETING_STATUS,
  CRM_MEETING_STATUSES,
  CRM_MEETING_RSVP,
  CRM_MEETING_RSVPS,
  CRM_MEETING_ATTENDANCE,
  CRM_MEETING_ATTENDANCES,
  CRM_MEETING_INVITATION_STATUS,
  CRM_MEETING_INVITATION_STATUSES,
  CRM_MEETING_OUTCOME,
  CRM_MEETING_OUTCOMES,
  CRM_CALENDAR_CONFLICT_POLICY,
  CRM_CALENDAR_CONFLICT_POLICIES,
  CRM_CALENDAR_VIEW,
  CRM_CALENDAR_VIEWS,
  CRM_CALENDAR_VISIBILITY,
  CRM_CALENDAR_EVENT_STATUS,
  CRM_CALENDAR_INTEGRATION_STATUS,
  CRM_CALL_STATUS,
  CRM_CALL_STATUSES,
  CRM_CALL_OUTCOME,
  CRM_CALL_OUTCOMES,
  CRM_TELEPHONY_PROVIDER_STATUS,
  CRM_CALL_RECORDING_STATUS,
  CRM_EMAIL_ACTIVITY_STATUS,
  CRM_EMAIL_ACTIVITY_STATUSES,
  CRM_EMAIL_SEND_STATUS,
  CRM_EMAIL_SEND_STATUSES,
  CRM_EMAIL_DELIVERY_EVENT,
  CRM_EMAIL_DELIVERY_EVENTS,
  CRM_EMAIL_TEMPLATE_STATUS,
  CRM_EMAIL_TEMPLATE_STATUSES,
  CRM_MERGE_STATUS,
  CRM_MERGE_STATUSES,
  CRM_MERGE_ENTITY,
  CRM_MERGE_ENTITIES,
  CRM_READINESS_STATUS,
  CRM_READINESS_STATUSES,
  CRM_FOUNDATION_KIND,
  CRM_FOUNDATION_STATUS,
  CRM_RELIABILITY_STATUS,
  CRM_TIMELINE_EVENT_TYPE,
  CRM_RECON_VERSION,
  CRM_EXPORT_VERSION,
  CRM_REMINDER_CHANNEL,
  CRM_REMINDER_CHANNELS,
  CRM_REMINDER_STATUS,
  CRM_REMINDER_STATUSES,
  CRM_DEMO_VERSION_STATUS,
  CRM_DEMO_VERSION_STATUSES,
  CRM_DEMO_CONTENT_CLASSIFICATION,
  CRM_DEMO_CONTENT_CLASSIFICATIONS,
  CRM_DEMO_CONTENT_KIND,
  CRM_DEMO_CONTENT_KINDS,
  CRM_DEMO_PROJECTION_SURFACE,
  CRM_DEMO_PROJECTION_SURFACES,
  CRM_DEMO_ENVIRONMENT_NUMBER_RE,
  CRM_DEMO_ENVIRONMENT_STATUS,
  CRM_DEMO_ENVIRONMENT_STATUSES,
  CRM_DEMO_ENVIRONMENT_HEALTH,
  CRM_DEMO_ENVIRONMENT_HEALTHS,
  CRM_DEMO_DATA_PACK_SOURCE_KIND,
  CRM_DEMO_DATA_PACK_SOURCE_KINDS,
  CRM_DEMO_CHECKLIST_EXECUTION_STATUS,
  CRM_DEMO_CHECKLIST_EXECUTION_STATUSES,
  CRM_DEMO_REHEARSAL_OUTCOME,
  CRM_DEMO_REHEARSAL_OUTCOMES,
  CRM_DEMO_ISSUE_SEVERITY,
  CRM_DEMO_ISSUE_SEVERITIES,
  CRM_ACTIVITY_TEMPLATE_STATUS,
  CRM_ACTIVITY_TEMPLATE_STATUSES,
  CRM_ACTIVITY_TEMPLATE_KIND,
  CRM_ACTIVITY_TEMPLATE_KINDS,
  CRM_AUTOMATION_TRIGGER,
  CRM_AUTOMATION_TRIGGERS,
  CRM_AUTOMATION_RULE_STATUS,
  CRM_AUTOMATION_RULE_STATUSES,
  CRM_AUTOMATION_EXECUTION_STATUS,
  CRM_AUTOMATION_EXECUTION_STATUSES,
  CRM_ACTIVITY_REPORT_STATUS,
  CRM_ACTIVITY_REPORT_SCHEDULE_STATUS,
  CRM_COMMERCIAL_REPORT_STATUS,
  CRM_COMMERCIAL_REPORT_SCHEDULE_STATUS,
  channelAvailability,
} from './catalogue.js';

export {
  formatCrmNumber,
  utcYearOf,
  allocateCrmNumber,
} from './numbering.js';

export { canTransition, assertTransition } from './stateMachine.js';

export { resolveCrmAccess, resolveCrmScope } from './authz.js';

export {
  hasCrmAccountModel,
  createAccount,
  getAccount,
  listAccounts,
  serializeAccount,
} from './accounts.js';

export {
  hasCrmContactModel,
  createContact,
  getContact,
  listContacts,
  serializeContact,
  normalizeEmail,
  normalizePhone,
} from './contacts.js';

export {
  hasCrmLeadModel,
  createLead,
  getLead,
  listLeads,
  transitionLeadStatus,
  serializeLead,
} from './leads.js';

export {
  hasCrmCaptureRecordModel,
  captureLead,
  _resetCaptureThrottleForTests,
} from './capture.js';

export {
  hasCrmDuplicateCandidateModel,
  detectDuplicateCandidates,
  listDuplicateCandidates,
  reviewDuplicateCandidate,
  serializeCandidate,
} from './duplicates.js';

export { intakeHandoffAsLead } from './handoffIntake.js';

export {
  getDefaultQualificationDefinition,
  getQualificationDefinitionByVersion,
  getActiveQualificationDefinition,
  listQualificationDefinitions,
  hasCrmQualificationResponseModel,
  evaluateQualificationResponses,
  evaluateQualification,
  assertLeadQualificationForQualifiedStatus,
} from './qualification/index.js';

export {
  getDefaultScoreDefinition,
  getScoreDefinitionByVersion,
  getActiveScoreDefinition,
  listScoreDefinitions,
  hasCrmScoreEvaluationModel,
  hasCrmScoreContributionModel,
  assertScoreLabelSafe,
  computeScore,
  runLeadScore,
  getLatestLeadScore,
} from './scoring/index.js';

export {
  CRM_SALES_TEAM_DEFINITIONS,
  hasCrmSalesTeamModel,
  hasCrmSalesTeamMemberModel,
  listSalesTeams,
  resolveTeamMemberAdminIds,
} from './teams.js';

export {
  CRM_TERRITORY_DEFINITIONS,
  hasCrmTerritoryModel,
  hasCrmTerritoryRuleModel,
  listTerritories,
  evaluateTerritory,
} from './territories.js';

export {
  hasCrmAssignmentHistoryModel,
  assignLead,
  acceptLeadAssignment,
  returnLeadToQueue,
  serializeAssignmentHistory,
} from './assignment.js';

export {
  hasCrmConsentRecordModel,
  hasCrmDoNotContactModel,
  hasCrmCommunicationPreferenceModel,
  recordConsent,
  setDoNotContact,
  getConsentStatus,
  listActiveDncFlags,
} from './consent.js';

export { checkCommunicationEligibility } from './eligibility.js';

export {
  hasCrmTimelineEventModel,
  appendTimelineEvent,
  listTimeline,
  serializeTimelineEvent,
} from './timeline.js';

export {
  hasCrmNoteModel,
  createNote,
  listNotes,
  projectNotesForViewer,
  serializeNote,
} from './notes.js';

export {
  hasCrmTaskModel,
  createTask,
  completeTask,
  reopenTask,
  listTasks,
  serializeTask,
} from './tasks.js';

export {
  CRM_ACTIVITY_STATUS_TRANSITIONS,
  isActivityStatusCompatible,
  canTransitionActivityStatus,
  allocateActivityNumber,
  allocateTaskNumber,
  hasCrmActivityModel,
  hasCrmActivityStatusHistoryModel,
  hasCrmActivityRelationModel,
  hasCrmActivityParticipantModel,
  serializeActivity,
  createCrmActivity,
  getCrmActivity,
  listCrmActivities,
  transitionActivityStatus,
  linkActivityRelation,
  listActivityRelations,
  addActivityParticipant,
  listActivityParticipants,
  CRM_ACTIVITY_PARTICIPANT_TYPE,
  CRM_ACTIVITY_PARTICIPANT_ROLE,
  CRM_ACTIVITY_REPORT_VERSION,
  applyActivityReportHonesty,
  getActivityReport,
  hasCrmActivityReportScheduleModel,
  hasCrmActivityReportRunModel,
  createActivityReportSchedule,
  listActivityReportSchedules,
  runActivityReportSchedule,
  CRM_ACTIVITY_DQ_VERSION,
  evaluateActivityDataQuality,
  CRM_ACTIVITY_RECON_VERSION,
  runActivityReconciliation,
  listEntityActivityProjections,
} from './activities/index.js';

export {
  hasCrmReminderModel,
  buildReminderDedupeKey,
  scheduleReminder,
  queueDueReminders,
  markReminderDelivered,
  snoozeReminder,
  listReminders,
  serializeReminder,
} from './reminders.js';

export {
  hasCrmActivityTemplateModel,
  createActivityTemplateVersion,
  updateActivityTemplate,
  getActiveActivityTemplate,
  listActivityTemplates,
  serializeActivityTemplate,
} from './templates.js';

export {
  CRM_AUTOMATION_ACTION,
  CRM_AUTOMATION_ACTIONS,
  CRM_AUTOMATION_DEFINITION_VERSION,
  APPROVED_TRIGGER_ACTIONS,
  hasCrmAutomationRuleModel,
  hasCrmAutomationApprovalModel,
  hasCrmAutomationExecutionModel,
  createAutomationRule,
  requestAutomationApproval,
  approveAutomationRule,
  listAutomationRules,
  executeAutomationRule,
  buildIdempotencyKey,
  serializeRule,
  serializeExecution,
  isApprovedPair,
} from './automation/index.js';
/* CRM_AUTOMATION_TRIGGER / RULE_STATUS / EXECUTION_STATUS exported from catalogue.js above */

export {
  hasCrmFollowUpModel,
  hasCrmFollowUpHistoryModel,
  createFollowUp,
  completeFollowUp,
  rescheduleFollowUp,
  listFollowUps,
  serializeFollowUp,
} from './followUps.js';

export {
  evaluateNextAction,
  listNoNextActionOpportunities,
  listNoNextActionLeads,
} from './nextAction.js';

export {
  hasCrmCallModel,
  serializeCall,
  allocateCallNumber,
  planCall,
  logManualCall,
  completeCall,
  listCalls,
  getTelephonyProviderContract,
  getCallRecordingStatus,
  isValidCallOutcome,
  isValidCallDirection,
} from './calls/index.js';

export {
  hasCrmEmailActivityModel,
  hasCrmEmailSendRequestModel,
  hasCrmEmailDeliveryEventModel,
  hasCrmEmailTemplateModel,
  serializeEmailActivity,
  serializeSendRequest,
  serializeDeliveryEvent,
  serializeEmailTemplate,
  createEmailDraft,
  evaluateEmailSendEligibility,
  evaluateEmailEligibility,
  requestEmailSend,
  listEmailActivities,
  renderEmailTemplateSafe,
  createEmailTemplateVersion,
  getActiveEmailTemplate,
  sendCrmSmtpMail,
  CRM_EMAIL_TEMPLATE_ALLOWED_VARS,
  CRM_EMAIL_TRACKING_PIXELS_ENABLED,
} from './emails/index.js';

export {
  hasCrmMeetingModel,
  hasCrmMeetingParticipantModel,
  hasCrmMeetingRescheduleHistoryModel,
  serializeMeeting,
  serializeMeetingParticipant,
  serializeRescheduleHistory,
  allocateMeetingNumber,
  createMeeting,
  rescheduleMeeting,
  cancelMeeting,
  recordMeetingRsvp,
  recordAttendance,
  listMeetings,
  getMeetingIntegrationContract,
  isValidMeetingRsvp,
  isValidMeetingAttendance,
  isValidMeetingOutcome,
  CRM_MEETING_PARTICIPANT_TYPE,
  CRM_MEETING_PARTICIPANT_ROLE,
} from './meetings/index.js';

export {
  hasCrmCalendarEventModel,
  serializeCalendarEvent,
  listCalendarEvents,
  detectCalendarConflicts,
  applyConflictPolicy,
  exportIcs,
  createCalendarEventForMeeting,
  getCalendarIntegrationStatus,
  resolveCalendarRange,
  rangesOverlap,
  CRM_CALENDAR_DEFAULT_WORKING_HOURS,
  CRM_CALENDAR_MAX_RANGE_DAYS,
  isValidConflictPolicy,
  isValidCalendarView,
} from './calendar/index.js';

export {
  hasCrmDemoRequestModel,
  hasCrmDemoModel,
  hasCrmDemoParticipantModel,
  hasCrmDemoStatusHistoryModel,
  serializeDemoRequest,
  serializeDemo,
  serializeDemoParticipant,
  serializeDemoStatusHistory,
  allocateDemoRequestNumber,
  allocateDemoNumber,
  createDemoRequest,
  qualifyDemoRequest,
  rejectDemoRequest,
  convertDemoRequest,
  listDemoRequests,
  createDemo,
  getDemo,
  listDemos,
  transitionDemoStatus,
  scheduleDemo,
  evaluateDemoReadiness,
  addDemoParticipant,
  removeDemoParticipant,
  listDemoParticipants,
  listDemosForLead,
  listDemosForOpportunity,
  getDemoDomainContract,
  isValidDemoStatus,
  isValidDemoRequestStatus,
  isValidDemoParticipantRole,
  isValidDemoParticipantType,
  canTransitionDemoStatus,
  CRM_DEMO_PARTICIPANT_TYPE,
  CRM_DEMO_PARTICIPANT_TYPES,
  CRM_DEMO_PARTICIPANT_ROLE,
  CRM_DEMO_PARTICIPANT_ROLES,
  hasCrmDemoAgendaModel,
  createAgendaVersion,
  updateAgendaVersion,
  requestAgendaApproval,
  approveAgendaVersion,
  listAgendaVersions,
  projectAgendaForSurface,
  pinAgendaToDemo,
  serializeAgenda,
  hasCrmDemoScriptModel,
  createScriptVersion,
  updateScriptVersion,
  requestScriptApproval,
  approveScriptVersion,
  listScriptVersions,
  projectScriptForSurface,
  pinScriptToDemo,
  serializeScript,
  hasCrmDemoScenarioModel,
  createScenarioVersion,
  updateScenarioVersion,
  requestScenarioApproval,
  approveScenarioVersion,
  listScenarioVersions,
  pinScenarioToDemo,
  serializeScenario,
  hasCrmDemoContentModel,
  createContentVersion,
  updateContentVersion,
  requestContentApproval,
  approveContentVersion,
  listContentVersions,
  pinContentToDemo,
  serializeContent,
  allocateDemoEnvironmentNumber,
  hasCrmDemoDataPackModel,
  validateDataPackSource,
  createDataPackVersion,
  updateDataPackVersion,
  requestDataPackApproval,
  approveDataPackVersion,
  listDataPackVersions,
  serializeDataPack,
  hasCrmDemoEnvironmentModel,
  evaluateLogicalEnvironmentHealth,
  requestDemoEnvironment,
  approveDemoEnvironment,
  provisionDemoEnvironment,
  runDemoEnvironmentHealthCheck,
  resetDemoEnvironment,
  deprovisionDemoEnvironment,
  getDemoEnvironment,
  listDemoEnvironments,
  serializeEnvironment,
  hasCrmDemoChecklistModel,
  hasCrmDemoChecklistExecutionModel,
  createChecklistVersion,
  updateChecklistVersion,
  requestChecklistApproval,
  approveChecklistVersion,
  listChecklistVersions,
  pinChecklistToDemo,
  executeDemoChecklist,
  serializeChecklist,
  serializeChecklistExecution,
  hasCrmDemoRehearsalModel,
  recordDemoRehearsal,
  listDemoRehearsals,
  serializeRehearsal,
  configureDemoReadinessRequirements,
  isValidDemoEnvironmentStatus,
  CRM_DEMO_ATTENDANCE_STATUS,
  CRM_DEMO_ATTENDANCE_STATUSES,
  CRM_DEMO_ATTENDANCE_SOURCE,
  CRM_DEMO_ATTENDANCE_SOURCES,
  CRM_DEMO_RECORDING_GOV_STATUS,
  CRM_DEMO_RECORDING_GOV_STATUSES,
  CRM_DEMO_OUTCOME_CODE,
  CRM_DEMO_OUTCOME_CODES,
  CRM_DEMO_OUTCOME_COMPLETENESS,
  CRM_DEMO_OUTCOME_COMPLETENESS_VALUES,
  CRM_DEMO_ISSUE_STATUS,
  CRM_DEMO_ISSUE_STATUSES,
  CRM_DEMO_QUESTION_STATUS,
  CRM_DEMO_QUESTION_STATUSES,
  CRM_DEMO_HANDOFF_TYPE,
  CRM_DEMO_HANDOFF_TYPES,
  CRM_DEMO_REPORT_STATUS,
  CRM_DEMO_REPORT_SCHEDULE_STATUS,
  isValidDemoAttendanceStatus,
  isValidDemoAttendanceSource,
  isValidDemoOutcomeCode,
  isValidDemoOutcomeCompleteness,
  hasCrmDemoDeliverySessionModel,
  hasCrmDemoLiveIssueModel,
  hasCrmDemoCustomerQuestionModel,
  startDemoDelivery,
  endDemoDelivery,
  recordAgendaCoverage,
  recordLiveIssue,
  recordCustomerQuestion,
  getDemoDeliverySession,
  serializeDeliverySession,
  serializeLiveIssue,
  serializeCustomerQuestion,
  hasCrmDemoAttendanceModel,
  recordDemoAttendance,
  projectAttendanceFromMeeting,
  listDemoAttendance,
  serializeDemoAttendance,
  hasCrmDemoRecordingGovModel,
  requestDemoRecording,
  setDemoRecordingConsent,
  approveDemoRecording,
  denyDemoRecording,
  getDemoRecordingGov,
  serializeRecordingGov,
  CRM_DEMO_RECORDING_PROVIDER_STATUS,
  hasCrmDemoFeedbackFormModel,
  hasCrmDemoFeedbackResponseModel,
  createFeedbackFormVersion,
  recordDemoFeedbackResponse,
  listDemoFeedbackResponses,
  serializeFeedbackForm,
  serializeFeedbackResponse,
  hasCrmDemoOutcomeModel,
  recordDemoOutcome,
  getDemoOutcome,
  serializeDemoOutcome,
  createDemoFollowUp,
  hasCrmDemoHandoffModel,
  emitDemoProposalHandoff,
  emitDemoTrialHandoff,
  assertNoProposalOrTrialCreate,
  listDemoHandoffs,
  serializeDemoHandoff,
  DEMO_PROPOSAL_HANDOFF_TYPE,
  DEMO_PROPOSAL_HANDOFF_VERSION,
  DEMO_TRIAL_HANDOFF_TYPE,
  DEMO_TRIAL_HANDOFF_VERSION,
  getDemoReport,
  applyDemoReportHonesty,
  CRM_DEMO_REPORT_VERSION,
  hasCrmDemoReportScheduleModel,
  hasCrmDemoReportRunModel,
  createDemoReportSchedule,
  listDemoReportSchedules,
  runDemoReportSchedule,
} from './demos/index.js';

export {
  CRM_PROPOSAL_REQUEST_STATUS,
  CRM_PROPOSAL_REQUEST_STATUSES,
  CRM_COMMERCIAL_DOCUMENT_STATUS,
  CRM_COMMERCIAL_DOCUMENT_STATUSES,
  CRM_COMMERCIAL_DOCUMENT_FAMILY,
  CRM_COMMERCIAL_DOCUMENT_FAMILIES,
  CRM_REQUESTED_DOCUMENT_TYPE,
  CRM_PROPOSAL_REQUEST_SOURCE,
  CRM_PRICE_BOOK_TYPE,
  CRM_PRICE_BOOK_VERSION_STATUS,
  CRM_FX_RELIABILITY,
  CRM_DISCOUNT_REQUEST_STATUS,
  CRM_APPROVAL_REQUEST_STATUS,
  CRM_APPROVAL_STEP_STATUS,
  CRM_PROPOSAL_REQUEST_NUMBER_RE,
  CRM_PROPOSAL_NUMBER_RE,
  CRM_QUOTATION_NUMBER_RE,
  CRM_PRICE_BOOK_NUMBER_RE,
  isValidCommercialDocumentStatus,
  isValidProposalRequestStatus,
  canTransitionCommercialDocumentStatus,
  canTransitionProposalRequestStatus,
  getCommercialDomainContract,
  allocateProposalRequestNumber,
  allocateProposalNumber,
  allocateQuotationNumber,
  allocatePriceBookNumber,
  formatDocumentVersionLabel,
  hasCrmProposalRequestModel,
  hasCrmProposalRequestStatusHistoryModel,
  hasCrmCommercialDocumentModel,
  hasCrmCommercialDocumentVersionModel,
  hasCrmCommercialDocumentVersionStatusHistoryModel,
  hasCrmProposalModel,
  hasCrmQuotationModel,
  hasCrmPriceBookModel,
  hasCrmPriceBookVersionModel,
  hasCrmPriceBookEntryModel,
  hasCrmDiscountRequestModel,
  hasCrmPricingSnapshotModel,
  hasCrmApprovalRequestModel,
  serializeProposalRequest,
  serializeCommercialDocument,
  serializeDocumentVersion,
  serializeProposal,
  serializeQuotation,
  serializePriceBook,
  serializePriceBookVersion,
  serializeDiscountRequest,
  serializeApprovalRequest,
  createProposalRequest,
  createProposalRequestFromDemoHandoff,
  seedProposalRequestFromOpportunityReadiness,
  qualifyProposalRequest,
  rejectProposalRequest,
  convertProposalRequest,
  listProposalRequests,
  createCommercialDocument,
  getCommercialDocument,
  listCommercialDocuments,
  createProposal,
  getProposal,
  createQuotation,
  getQuotation,
  createDocumentVersion,
  updateDocumentVersionContent,
  assertVersionMutable,
  transitionDocumentStatus,
  transitionProposalRequestStatus,
  createPriceBook,
  approvePriceBookVersion,
  activatePriceBookVersion,
  updatePriceBookEntry,
  listPriceBooks,
  calculateCommercialDocument,
  createDiscountRequest,
  approveDiscountRequest,
  submitCommercialDocumentForApproval,
  decideApprovalStep,
  applyMaterialDocumentChange,
  listCommercialApprovals,
  createTerm,
  listTerms,
  createClause,
  listClauses,
  createPricingException,
  approvePricingException,
  renderCommercialDocument,
  issueCommercialDocument,
  withdrawCommercialDocument,
  recordCustomerView,
  submitCustomerComment,
  submitRevisionRequest,
  acceptCommercialDocument,
  evaluateAcceptanceAuthority,
  evaluateAcceptanceAuthorityStatus,
  assertEngagementIsNotAcceptance,
  CRM_ACCEPTANCE_AUTHORITY_STATUS,
  rejectCommercialDocument,
  runCommercialExpiryJob,
  getESignatureProviderStatus,
  CRM_COMMERCIAL_PROJECTION,
  CRM_DELIVERY_METHOD,
  CRM_ESIGN_STATUS,
  projectContentForAudience,
  createCommercialTemplate,
  recordCommercialDelivery,
  createReviewAccess,
  resolveReviewAccessByToken,
  hasCrmCommercialRecipientModel,
  hasCrmCommercialArtifactModel,
  hasCrmCommercialAcceptanceModel,
  evaluateClosedWonReadiness,
  createClosedWonConversionHandoff,
  serializeClosedWonHandoff,
  hasCrmClosedWonConversionHandoffModel,
  applyCommercialReportHonesty,
  getCommercialMetric,
  getCommercialReport,
  getCommercialOverview,
  createCommercialReportSchedule,
  listCommercialReportSchedules,
  runCommercialReportSchedule,
  runCommercialDataQuality,
  runCommercialReconciliation,
  CRM_COMMERCIAL_REPORT_VERSION,
  CRM_COMMERCIAL_METRIC_VERSION,
  PHASE16_CONVERSION_HANDOFF_TYPE,
  PHASE16_CONVERSION_HANDOFF_VERSION,
} from './commercial/index.js';

export {
  CRM_CONVERSION_REQUEST_SOURCE,
  CRM_CONVERSION_REQUEST_STATUS,
  CRM_CONVERSION_REQUEST_STATUSES,
  CRM_CONVERSION_TYPE,
  CRM_CONVERSION_STATUS,
  CRM_CONVERSION_STEP_CODE,
  CRM_CONVERSION_STEP_STATUS,
  CRM_CONVERSION_WAVE1_STEPS,
  CRM_CONVERSION_READINESS_STATUS,
  CONVERSION_DOMAIN_CONTRACT,
  getConversionDomainContract,
  CRM_CONVERSION_REQUEST_NUMBER_RE,
  CRM_CONVERSION_NUMBER_RE,
  allocateConversionRequestNumber,
  allocateConversionNumber,
  hasCrmConversionRequestModel,
  hasCrmConversionPlanModel,
  hasCrmConversionPlanVersionModel,
  hasCrmConversionDryRunModel,
  hasCrmConversionModel,
  hasCrmConversionStepModel,
  hasCrmConversionAttemptModel,
  hasCrmConversionFailureModel,
  serializeConversionRequest,
  serializeConversionPlan,
  serializeConversionPlanVersion,
  serializeConversion,
  serializeConversionStep,
  transitionConversionRequestStatus,
  transitionConversionStatus,
  createConversionRequest,
  createConversionRequestFromClosedWonHandoff,
  validateConversionRequest,
  approveConversionRequest,
  listConversionRequests,
  evaluateConversionReadiness,
  evaluateConversionRequestReadiness,
  createConversionPlan,
  dryRunConversion,
  executeClosedWonConversion,
  resumeConversion,
  hashConversionInput,
  CRM_CONVERSION_WAVE2_STEPS,
  CRM_CONVERSION_WAVE3_STEPS,
  CRM_CUSTOMER_MATCH_STATE,
  CRM_CONTACT_LINK_DECISION,
  CRM_CONVERSION_RESOURCE_TYPE,
  CRM_TENANT_PROVISION_STATUS,
  CRM_SUBSCRIPTION_PROVISION_STATUS,
  CRM_ACTIVATION_POLICY,
  CRM_PAYMENT_INITIATION_STATUS,
  matchPlatformCustomer,
  decideCustomerCreateOrLink,
  isExactCustomerMatch,
  isExactOrHighConfidenceMatch,
  createOrLinkPlatformCustomer,
  decideTenantCreateOrLink,
  createOrLinkTenant,
  createPrimaryBusinessBranch,
  linkContactsForConversion,
  decideContactCreateOrLink,
  lockConversionCommercialSnapshot,
  getLockedConversionCommercialSnapshot,
  resolveConversionAcceptedSnapshot,
  checksumCommercialSnapshot,
  claimConversionStep,
  beginStepOptimistic,
  createInitialUserInvitation,
  assertTenantIsolation,
  assertNoTenantAccountingSideEffects,
  ensureWave2Steps,
  ensureWave3Steps,
  createOrAmendSubscriptionFromAccepted,
  provisionEntitlementsFromAccepted,
  createOrLinkBillingAccount,
  createBillingSchedule,
  createPlatformInvoiceIfRequired,
  initiatePaymentIfRequired,
  evaluateActivationPolicy,
  resolveAuthoritativePaymentSuccess,
  activateProvisionedSubscription,
  runWave3ProvisionSpine,
  CRM_CONVERSION_WAVE4_STEPS,
  assignCustomerSuccessOwner,
  createOnboardingHandoff,
  sendOnboardingHandoff,
  supersedeOnboardingHandoff,
  createTrainingHandoff,
  createDataMigrationHandoff,
  createMraEisHandoff,
  finalizeConversion,
  compensateConversionArtifacts,
  computeCompletionCertificateChecksum,
  applyConversionReportHonesty,
  safeConversionCount,
  CRM_CONVERSION_REPORT_STATUS,
  getConversionMetric,
  getConversionReport,
  getConversionOverview,
  CRM_CONVERSION_REPORT_VERSION,
  runConversionDataQuality,
  runConversionReconciliation,
  resolveConversionListScope,
  whereFromConversionScope,
  exportConversionReport,
  searchConversionIndex,
  getConversionValueLabelHonesty,
  CRM_CONVERSION_VALUE_LABEL,
  CRM_CONVERSION_HUB_ROUTES,
  CRM_CONVERSION_PERMISSION_NOTES,
  CRM_CONVERSION_SEARCH_KEYS,
  CRM_CONVERSION_CACHE_KEYS,
  CRM_CONVERSION_HANDOFF_TYPE,
  CRM_CONVERSION_HANDOFF_STATUS,
  CRM_CONVERSION_HANDOFF_EXECUTION,
  CRM_ONBOARDING_HANDOFF_PACKAGE_STATUS,
  sanitizeConversionHandoffPayload,
  computeOnboardingHandoffChecksum,
  assertProvisionResultHonesty,
  clampProvisionRequestStatus,
  stripFabricatedProvisionArgs,
} from './conversions/index.js';

export {
  hasCrmMergeRequestModel,
  requestMerge,
  approveMerge,
  executeMerge,
  listMergeRequests,
  serializeMergeRequest,
} from './merge.js';

export {
  evaluateOpportunityReadiness,
  assertNoOpportunityCreate,
} from './opportunityReadiness.js';

export {
  hasCrmReconciliationRunModel,
  applyCrmReconHonesty,
  runCrmReconciliation,
} from './reconciliation.js';

export { hasCrmExportAuditModel, buildCrmExportPack } from './export.js';

export { getCrmFoundations, FOUNDATION_CONTRACTS } from './foundations.js';

export {
  CRM_PIPELINE_CODE,
  CRM_PIPELINE_CODES,
  CRM_PIPELINE_DEFINITION_VERSION,
  CRM_PIPELINE_EXPANSION_VERSION,
  CRM_PIPELINE_MRA_EIS_VERSION,
  CRM_PIPELINE_STAGE,
  CRM_PIPELINE_STAGES_ORDERED,
  CRM_PIPELINE_STATUS,
  CRM_PIPELINE_TERMINAL_STAGES,
  CRM_OPPORTUNITY_STATUS,
  CRM_HANDOFF_TYPE_OPPORTUNITY,
  // CRM_OPPORTUNITY_NUMBER_RE exported from catalogue.js
  getDefaultNewBusinessPipelineDefinition,
  getDefaultExpansionPipelineDefinition,
  getDefaultMraEisPipelineDefinition,
  listCataloguePipelineDefinitions,
  getPipelineDefinitionByCode,
  canTransitionStage,
  isTerminalStage,
  stageSortOrder,
  listPipelineStages,
  getStageDefinition,
  hasCrmPipelineModel,
  hasCrmPipelineVersionModel,
  hasCrmPipelineStageModel,
  listPipelines,
  getPipeline,
  transitionOpportunityStage,
  hasCrmOpportunityModel,
  hasCrmOpportunityStageHistoryModel,
  serializeOpportunity,
} from './pipeline/index.js';

export {
  allocateOpportunityNumber,
  createOpportunityFromHandoff,
  getOpportunity,
  listOpportunities,
  CRM_OPPORTUNITY_CONTACT_ROLE,
  CRM_OPPORTUNITY_CONTACT_ROLES,
  hasCrmOpportunityContactRoleModel,
  hasCrmOpportunityContactRoleHistoryModel,
  hasPrimaryContactRole,
  seedPrimaryContactFromOpportunity,
  listOpportunityContactRoles,
  upsertOpportunityContactRole,
  listOpportunityContactRoleHistory,
  OPPORTUNITY_PRODUCT_BINDING,
  hasCrmOpportunityProductModel,
  resolveCatalogueProductRef,
  listOpportunityProducts,
  addOpportunityProduct,
  WEIGHTED_PIPELINE_UI_ENABLED,
  resolveWeightedPipelineUiAccess,
  CRM_AMOUNT_BASIS,
  CRM_AMOUNT_BASES,
  hasCrmOpportunityAmountHistoryModel,
  isIso4217Currency,
  computeIndicativeWeightedAmount,
  summarizeAmountsByCurrency,
  setOpportunityCommercial,
  getOpportunityCommercial,
  CRM_PROBABILITY_SOURCE,
  CRM_PROBABILITY_CONFIDENCE,
  CRM_PROBABILITY_CONFIDENCES,
  CRM_PROBABILITY_APPROVAL_STATUS,
  hasCrmOpportunityProbabilityHistoryModel,
  getStageDefaultProbability,
  applyStageDefaultProbability,
  overrideOpportunityProbability,
  getOpportunityProbability,
  CRM_CLOSE_DATE_SOURCE,
  CRM_CLOSE_DATE_SOURCES,
  CRM_CLOSE_DATE_CONFIDENCE,
  CRM_CLOSE_DATE_CONFIDENCES,
  hasCrmOpportunityCloseDateHistoryModel,
  isCloseDateForecastEligible,
  setOpportunityCloseDate,
  getOpportunityCloseDate,
  BOARD_COLUMN_PAGE_SIZE,
  getPipelineBoard,
  CRM_OPPORTUNITY_RISK_SEVERITY,
  CRM_OPPORTUNITY_RISK_STATUS,
  CRM_OPPORTUNITY_RISK_CODE,
  hasCrmOpportunityRiskModel,
  computeOpportunityRiskSignals,
  evaluateOpportunityRisks,
  listOpportunityRisks,
  createOpportunityTask,
  listOpportunityTasks,
  completeOpportunityTask,
  appendOpportunityTimelineEvent,
  listOpportunityTimeline,
  CRM_CLOSE_APPROVAL_STATUS,
  CRM_WIN_REASON,
  CRM_LOSS_REASON,
  assertNoProvision,
  resolveClosedWonAcceptanceId,
  commercialReadinessRequiredByPolicy,
  closeOpportunityWon,
  closeOpportunityLost,
  reopenOpportunity,
  evaluateProposalReadiness,
  assertNoProposalCreate,
  PROPOSAL_HANDOFF_TYPE,
  assertNoConversionExecute,
  CONVERSION_HANDOFF_TYPE,
  CRM_OPP_DUPLICATE_MATCH_TYPE,
  CRM_OPP_DUPLICATE_MATCH_TYPES,
  hasCrmOpportunityDuplicateCandidateModel,
  detectOpportunityDuplicateCandidates,
  listOpportunityDuplicateCandidates,
  reviewOpportunityDuplicateCandidate,
  CRM_OPP_IMPORT_VERSION,
  validateOpportunityImportRow,
  previewOpportunityImport,
  confirmOpportunityImport,
  CRM_PIPELINE_REPORT_VERSION,
  getPipelineReport,
  CRM_PIPELINE_REPORT_SCHEDULE_STATUS,
  hasCrmPipelineReportScheduleModel,
  hasCrmPipelineReportRunModel,
  createPipelineReportSchedule,
  listPipelineReportSchedules,
  runPipelineReportSchedule,
} from './opportunities/index.js';
