/**
 * Phase 16 Wave 1–4 — Closed-Won conversion catalogue.
 * Closed Won ≠ Paid ≠ ACTIVE. Dry-run = zero operational side effects.
 * Wave 2: Customer match/create-link, Tenant/Business/Branch, invitations.
 * Wave 3: Subscription/entitlements/billing/payment/activation.
 * Wave 4: CS + handoffs + completion + reports/DQ/recon (handoff ≠ execute).
 */

export const CRM_CONVERSION_REQUEST_SOURCE = Object.freeze({
  PHASE_15_ACCEPTANCE_HANDOFF: 'PHASE_15_ACCEPTANCE_HANDOFF',
  MANUAL_APPROVED: 'MANUAL_APPROVED',
  EXPANSION: 'EXPANSION',
  PARTNER_RESELLER: 'PARTNER_RESELLER',
  API: 'API',
});

export const CRM_CONVERSION_REQUEST_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  VALIDATING: 'VALIDATING',
  INFORMATION_REQUIRED: 'INFORMATION_REQUIRED',
  DUPLICATE_REVIEW_REQUIRED: 'DUPLICATE_REVIEW_REQUIRED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  READY: 'READY',
  QUEUED: 'QUEUED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  FAILED: 'FAILED',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REJECTED: 'REJECTED',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_CONVERSION_REQUEST_STATUSES = Object.freeze(
  Object.values(CRM_CONVERSION_REQUEST_STATUS)
);

export const CRM_CONVERSION_TYPE = Object.freeze({
  NEW_CUSTOMER_NEW_TENANT: 'NEW_CUSTOMER_NEW_TENANT',
  EXISTING_CUSTOMER_NEW_SUBSCRIPTION: 'EXISTING_CUSTOMER_NEW_SUBSCRIPTION',
  MANUAL_APPROVED: 'MANUAL_APPROVED',
});

export const CRM_CONVERSION_STATUS = Object.freeze({
  LOCKED: 'LOCKED',
  IN_PROGRESS: 'IN_PROGRESS',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  FAILED: 'FAILED',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const CRM_CONVERSION_STEP_CODE = Object.freeze({
  VALIDATE_EVIDENCE: 'VALIDATE_EVIDENCE',
  TRANSITION_OPPORTUNITY_CLOSED_WON: 'TRANSITION_OPPORTUNITY_CLOSED_WON',
  CREATE_OR_LINK_PLATFORM_CUSTOMER: 'CREATE_OR_LINK_PLATFORM_CUSTOMER',
  CREATE_OR_LINK_TENANT: 'CREATE_OR_LINK_TENANT',
  CREATE_BUSINESS: 'CREATE_BUSINESS',
  CREATE_BRANCH: 'CREATE_BRANCH',
  LINK_CONTACTS: 'LINK_CONTACTS',
  CREATE_INITIAL_USER_INVITATIONS: 'CREATE_INITIAL_USER_INVITATIONS',
  CREATE_OR_AMEND_SUBSCRIPTION: 'CREATE_OR_AMEND_SUBSCRIPTION',
  PROVISION_ENTITLEMENTS: 'PROVISION_ENTITLEMENTS',
  CREATE_OR_LINK_BILLING_ACCOUNT: 'CREATE_OR_LINK_BILLING_ACCOUNT',
  CREATE_PLATFORM_INVOICE_IF_REQUIRED: 'CREATE_PLATFORM_INVOICE_IF_REQUIRED',
  INITIATE_PAYMENT_IF_REQUIRED: 'INITIATE_PAYMENT_IF_REQUIRED',
  ACTIVATE_SUBSCRIPTION: 'ACTIVATE_SUBSCRIPTION',
  ASSIGN_CS: 'ASSIGN_CS',
  ONBOARDING_HANDOFF: 'ONBOARDING_HANDOFF',
  TRAINING_HANDOFF: 'TRAINING_HANDOFF',
  MIGRATION_HANDOFF: 'MIGRATION_HANDOFF',
  MRA_EIS_HANDOFF: 'MRA_EIS_HANDOFF',
  RECONCILE: 'RECONCILE',
  COMPLETION_CERTIFICATE: 'COMPLETION_CERTIFICATE',
  /** Wave 1 sentinel — simulates later-wave failure without reopen */
  WAVE1_PROVISION_BOUNDARY: 'WAVE1_PROVISION_BOUNDARY',
});

export const CRM_CONVERSION_STEP_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_WARNING: 'COMPLETED_WITH_WARNING',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  FAILED_RETRYABLE: 'FAILED_RETRYABLE',
  FAILED_NON_RETRYABLE: 'FAILED_NON_RETRYABLE',
  BLOCKED: 'BLOCKED',
  COMPENSATING: 'COMPENSATING',
  COMPENSATED: 'COMPENSATED',
  SKIPPED_NOT_APPLICABLE: 'SKIPPED_NOT_APPLICABLE',
  MANUAL_INTERVENTION_REQUIRED: 'MANUAL_INTERVENTION_REQUIRED',
});

/** Wave 1 durable step spine — validate + closed-won; later steps skipped/not started. */
export const CRM_CONVERSION_WAVE1_STEPS = Object.freeze([
  { stepCode: CRM_CONVERSION_STEP_CODE.VALIDATE_EVIDENCE, stepOrder: 10 },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.TRANSITION_OPPORTUNITY_CLOSED_WON,
    stepOrder: 20,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_LINK_PLATFORM_CUSTOMER,
    stepOrder: 30,
    wave1Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_LINK_TENANT,
    stepOrder: 40,
    wave1Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_AMEND_SUBSCRIPTION,
    stepOrder: 50,
    wave1Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.WAVE1_PROVISION_BOUNDARY,
    stepOrder: 60,
    wave1Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
]);

/** Wave 2 provision steps — replace Wave 1 SKIPPED defaults when Wave 2 runs. */
export const CRM_CONVERSION_WAVE2_STEPS = Object.freeze([
  { stepCode: CRM_CONVERSION_STEP_CODE.VALIDATE_EVIDENCE, stepOrder: 10 },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.TRANSITION_OPPORTUNITY_CLOSED_WON,
    stepOrder: 20,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_LINK_PLATFORM_CUSTOMER,
    stepOrder: 30,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_LINK_TENANT,
    stepOrder: 40,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_BUSINESS,
    stepOrder: 45,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_BRANCH,
    stepOrder: 46,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.LINK_CONTACTS,
    stepOrder: 47,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_INITIAL_USER_INVITATIONS,
    stepOrder: 48,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_AMEND_SUBSCRIPTION,
    stepOrder: 50,
    wave2Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.WAVE1_PROVISION_BOUNDARY,
    stepOrder: 60,
    wave2Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
]);

export const CRM_CUSTOMER_MATCH_STATE = Object.freeze({
  EXACT_EXISTING_CUSTOMER: 'EXACT_EXISTING_CUSTOMER',
  /** Phase 20 canonical exact-identity state (alias of EXACT_EXISTING_CUSTOMER policy). */
  EXACT_MATCH: 'EXACT_MATCH',
  HIGH_CONFIDENCE_MATCH: 'HIGH_CONFIDENCE_MATCH',
  POSSIBLE_MATCH: 'POSSIBLE_MATCH',
  NO_MATCH: 'NO_MATCH',
  CONFLICT: 'CONFLICT',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
  /** Policy decisions (not match scores) — used by decideCustomerCreateOrLink. */
  LINK_EXISTING: 'LINK_EXISTING',
  CREATE_NEW: 'CREATE_NEW',
});

export const CRM_CONVERSION_RESOURCE_TYPE = Object.freeze({
  PLATFORM_CUSTOMER: 'PLATFORM_CUSTOMER',
  TENANT: 'TENANT',
  BUSINESS: 'BUSINESS',
  BRANCH: 'BRANCH',
  CONTACT_LINK: 'CONTACT_LINK',
  USER_INVITATION: 'USER_INVITATION',
  SUBSCRIPTION: 'SUBSCRIPTION',
  ENTITLEMENT_SET: 'ENTITLEMENT_SET',
  BILLING_ACCOUNT: 'BILLING_ACCOUNT',
  BILLING_SCHEDULE: 'BILLING_SCHEDULE',
  PLATFORM_INVOICE: 'PLATFORM_INVOICE',
  PLATFORM_PAYMENT: 'PLATFORM_PAYMENT',
  /** Phase 20 — immutable conversion-time commercial snapshot lock */
  COMMERCIAL_SNAPSHOT: 'COMMERCIAL_SNAPSHOT',
});

export const CRM_CONTACT_LINK_DECISION = Object.freeze({
  LINK: 'LINK',
  CREATE: 'CREATE',
  DENIED_CROSS_CUSTOMER: 'DENIED_CROSS_CUSTOMER',
  DENIED_CONSENT: 'DENIED_CONSENT',
});

export const CRM_TENANT_PROVISION_STATUS = Object.freeze({
  PROVISIONING: 'PROVISIONING',
  PENDING: 'PENDING',
  FAILED_PROVISIONING: 'FAILED_PROVISIONING',
});

export const CRM_SUBSCRIPTION_PROVISION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PENDING_ACTIVATION: 'PENDING_ACTIVATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
});

export const CRM_ACTIVATION_POLICY = Object.freeze({
  IMMEDIATE: 'IMMEDIATE',
  AFTER_INVOICE: 'AFTER_INVOICE',
  AFTER_PAYMENT: 'AFTER_PAYMENT',
  SERVICE_DATE: 'SERVICE_DATE',
  MANUAL: 'MANUAL',
});

export const CRM_PAYMENT_INITIATION_STATUS = Object.freeze({
  NOT_REQUIRED: 'NOT_REQUIRED',
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  INITIATED: 'INITIATED',
  PENDING: 'PENDING',
});

/** Wave 3 subscription/billing/activation steps. */
export const CRM_CONVERSION_WAVE3_STEPS = Object.freeze([
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_AMEND_SUBSCRIPTION,
    stepOrder: 50,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.PROVISION_ENTITLEMENTS,
    stepOrder: 51,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_OR_LINK_BILLING_ACCOUNT,
    stepOrder: 52,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.CREATE_PLATFORM_INVOICE_IF_REQUIRED,
    stepOrder: 53,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.INITIATE_PAYMENT_IF_REQUIRED,
    stepOrder: 54,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.ACTIVATE_SUBSCRIPTION,
    stepOrder: 55,
  },
  {
    stepCode: CRM_CONVERSION_STEP_CODE.WAVE1_PROVISION_BOUNDARY,
    stepOrder: 60,
    wave3Default: CRM_CONVERSION_STEP_STATUS.SKIPPED_NOT_APPLICABLE,
  },
]);

/** Wave 4 CS + domain handoffs + recon + completion certificate. */
export const CRM_CONVERSION_WAVE4_STEPS = Object.freeze([
  { stepCode: CRM_CONVERSION_STEP_CODE.ASSIGN_CS, stepOrder: 70 },
  { stepCode: CRM_CONVERSION_STEP_CODE.ONBOARDING_HANDOFF, stepOrder: 71 },
  { stepCode: CRM_CONVERSION_STEP_CODE.TRAINING_HANDOFF, stepOrder: 72 },
  { stepCode: CRM_CONVERSION_STEP_CODE.MIGRATION_HANDOFF, stepOrder: 73 },
  { stepCode: CRM_CONVERSION_STEP_CODE.MRA_EIS_HANDOFF, stepOrder: 74 },
  { stepCode: CRM_CONVERSION_STEP_CODE.RECONCILE, stepOrder: 80 },
  { stepCode: CRM_CONVERSION_STEP_CODE.COMPLETION_CERTIFICATE, stepOrder: 90 },
]);

export const RESERVED_TENANT_SLUGS = Object.freeze([
  'admin',
  'api',
  'www',
  'app',
  'insightbooks',
  'system',
  'root',
  'support',
  'billing',
  'null',
  'undefined',
]);

export const CRM_CONVERSION_READINESS_STATUS = Object.freeze({
  NOT_READY: 'NOT_READY',
  PARTIALLY_READY: 'PARTIALLY_READY',
  READY: 'READY',
  READY_WITH_WARNINGS: 'READY_WITH_WARNINGS',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  DUPLICATE_REVIEW_REQUIRED: 'DUPLICATE_REVIEW_REQUIRED',
  BLOCKED: 'BLOCKED',
  /** Phase 20 — UNKNOWN never passes as READY */
  UNKNOWN: 'UNKNOWN',
});

export const CONVERSION_DOMAIN_CONTRACT = Object.freeze({
  surface: '/insightbooks/crm/conversions',
  /** PRD Phase 20 (tree phase-16 alias retained in docs) */
  phase: 20,
  wave: 4,
  closedWonTiming: 'EARLY_DURABLE_LOCK',
  dryRunSideEffects: false,
  provisionsCustomer: true,
  provisionsTenant: true,
  provisionsSubscription: true,
  provisionsInvoice: true,
  tenantGlForbidden: true,
  fabricatePaidForbidden: true,
  fabricateActiveForbidden: true,
  invitationHashOnly: true,
  closedWonImpliesActive: false,
  paymentInitiationImpliesPaid: false,
  handoffImpliesExecution: false,
  inventZeroesForbidden: true,
});

export function getConversionDomainContract() {
  return { ...CONVERSION_DOMAIN_CONTRACT };
}

export {
  CRM_CONVERSION_REQUEST_NUMBER_RE,
  CRM_CONVERSION_NUMBER_RE,
  CRM_NUMBER_PREFIX,
} from '../catalogue.js';
