<?php
return [
    'app_name' => 'InsightBooks Android App Center',
    'app_url' => getenv('APP_URL') ?: 'https://app.insightinnovationsltd.com',
    'public_url' => getenv('PUBLIC_URL') ?: (getenv('APP_URL') ?: 'https://app.insightinnovationsltd.com'),
    'admin_url' => getenv('ADMIN_URL') ?: rtrim((getenv('APP_URL') ?: 'https://app.insightinnovationsltd.com'), '/') . '/admin',
    'timezone' => 'Africa/Harare',
    'debug' => filter_var(getenv('APP_DEBUG') ?: false, FILTER_VALIDATE_BOOLEAN),
    'force_https' => true,
    'session_name' => 'ib_apk_center',
    'upload_max_apk_mb' => 150,
    'upload_max_image_mb' => 5,
    'api_key' => getenv('API_KEY') ?: 'change-this-api-key-in-production',
    'api_shared_secret' => getenv('API_SHARED_SECRET') ?: 'change-this-shared-secret-in-production',
    'main_system_sync_url' => getenv('MAIN_SYSTEM_SYNC_URL') ?: 'https://insightbooksafrica.com/api/mobile-app/external-sync',
    'main_system_api_key' => getenv('MAIN_SYSTEM_API_KEY') ?: 'change-main-system-api-key',
    'main_system_shared_secret' => getenv('MAIN_SYSTEM_SHARED_SECRET') ?: 'change-main-system-shared-secret',
    'rate_limit_update_check' => 120,
    'rate_limit_reviews' => 5,
    'rate_limit_window_seconds' => 3600,
    'captcha_enabled' => false,
    'default_developer' => 'InsightBooks Africa',
    'brand_primary' => '#6366f1',
    'brand_primary_dark' => '#4f46e5',
    'brand_secondary' => '#3b82f6',
];
