export const EQUITY_PERMISSIONS = Object.freeze({
  VIEW: 'equity.view',
  VIEW_DASHBOARD: 'equity.viewDashboard',
  VIEW_OWNERS: 'equity.viewOwners',
  MANAGE_OWNERS: 'equity.manageOwners',
  VERIFY_OWNERS: 'equity.verifyOwners',
  VIEW_SHAREHOLDERS: 'equity.viewShareholders',
  MANAGE_SHAREHOLDERS: 'equity.manageShareholders',
  VIEW_HOLDINGS: 'equity.viewHoldings',
  MANAGE_SHARE_CLASSES: 'equity.manageShareClasses',
  ISSUE_SHARES: 'equity.issueShares',
  TRANSFER_SHARES: 'equity.transferShares',
  REDEEM_SHARES: 'equity.redeemShares',
  VIEW_CONTRIBUTIONS: 'equity.viewContributions',
  CREATE_CONTRIBUTION: 'equity.createContribution',
  APPROVE_CONTRIBUTION: 'equity.approveContribution',
  POST_CONTRIBUTION: 'equity.postContribution',
  CREATE_DRAWING: 'equity.createDrawing',
  APPROVE_DRAWING: 'equity.approveDrawing',
  POST_DRAWING: 'equity.postDrawing',
  VIEW_DIVIDENDS: 'equity.viewDividends',
  DECLARE_DIVIDEND: 'equity.declareDividend',
  APPROVE_DIVIDEND: 'equity.approveDividend',
  PAY_DIVIDEND: 'equity.payDividend',
  MANAGE_RESERVES: 'equity.manageReserves',
  CREATE_PPA: 'equity.createPriorPeriodAdjustment',
  APPROVE_PPA: 'equity.approvePriorPeriodAdjustment',
  REQUEST_REVERSAL: 'equity.requestReversal',
  RECONCILE: 'equity.reconcile',
  VIEW_STATEMENTS: 'equity.viewStatements',
  EXPORT: 'equity.export',
  VIEW_DOCUMENTS: 'equity.viewDocuments',
  MANAGE_DOCUMENTS: 'equity.manageDocuments',
  VIEW_AUDIT: 'equity.viewAudit',
  MANAGE_CONFIGURATION: 'equity.manageConfiguration',
  VIEW_SENSITIVE: 'equity.viewSensitiveOwnershipDetails',
});

export const EQUITY_PERMISSION_ACTIONS = Object.freeze([
  'view',
  'viewDashboard',
  'viewOwners',
  'manageOwners',
  'verifyOwners',
  'viewShareholders',
  'manageShareholders',
  'viewHoldings',
  'manageShareClasses',
  'issueShares',
  'transferShares',
  'redeemShares',
  'viewContributions',
  'createContribution',
  'approveContribution',
  'postContribution',
  'createDrawing',
  'approveDrawing',
  'postDrawing',
  'viewDividends',
  'declareDividend',
  'approveDividend',
  'payDividend',
  'manageReserves',
  'createPriorPeriodAdjustment',
  'approvePriorPeriodAdjustment',
  'requestReversal',
  'reconcile',
  'viewStatements',
  'export',
  'viewDocuments',
  'manageDocuments',
  'viewAudit',
  'manageConfiguration',
  'viewSensitiveOwnershipDetails',
]);
