export const TAX_PURPOSES = Object.freeze({
  VAT_OUTPUT: 'VAT_OUTPUT',
  VAT_INPUT: 'VAT_INPUT',
  TAX_PAYABLE: 'TAX_PAYABLE',
  TAX_RECEIVABLE: 'TAX_RECEIVABLE',
  WITHHOLDING_PAYABLE: 'WITHHOLDING_PAYABLE',
  PRIMARY_BANK: 'PRIMARY_BANK',
});

export const TAX_PURPOSE_LIST = Object.freeze(Object.values(TAX_PURPOSES));
