/** Canonical EIS secret type registry (Phase 6). */

export const EIS_SECRET_TYPE = Object.freeze({
  MRA_TERMINAL_JWT: 'MRA_TERMINAL_JWT',
  MRA_TERMINAL_SECRET: 'MRA_TERMINAL_SECRET',
  MRA_TERMINAL_ACTIVATION_CODE: 'MRA_TERMINAL_ACTIVATION_CODE',
  MRA_BUYER_AUTHORIZATION_CODE: 'MRA_BUYER_AUTHORIZATION_CODE',
  MRA_SANDBOX_ACCESS_TOKEN: 'MRA_SANDBOX_ACCESS_TOKEN',
  MRA_PRODUCTION_ACCESS_TOKEN: 'MRA_PRODUCTION_ACCESS_TOKEN',
  MRA_CLIENT_CREDENTIAL: 'MRA_CLIENT_CREDENTIAL',
  MRA_OFFLINE_SIGNING_SECRET: 'MRA_OFFLINE_SIGNING_SECRET',
  INTERNAL_DATA_ENCRYPTION_KEY_REFERENCE: 'INTERNAL_DATA_ENCRYPTION_KEY_REFERENCE',
  OTHER_APPROVED_SECRET: 'OTHER_APPROVED_SECRET',
});

/** Map Phase 5 credentialType → Phase 6 secret type */
export const CREDENTIAL_TYPE_TO_SECRET = Object.freeze({
  TERMINAL_JWT: EIS_SECRET_TYPE.MRA_TERMINAL_JWT,
  TERMINAL_SECRET: EIS_SECRET_TYPE.MRA_TERMINAL_SECRET,
  ACTIVATION_CODE_EPHEMERAL: EIS_SECRET_TYPE.MRA_TERMINAL_ACTIVATION_CODE,
  BUYER_AUTHORIZATION_EPHEMERAL: EIS_SECRET_TYPE.MRA_BUYER_AUTHORIZATION_CODE,
  SANDBOX_ACCESS: EIS_SECRET_TYPE.MRA_SANDBOX_ACCESS_TOKEN,
});

export const SECRET_TYPE_POLICY = Object.freeze({
  [EIS_SECRET_TYPE.MRA_TERMINAL_JWT]: {
    classification: 'SECRET',
    maxLifetimeHours: 24 * 90,
    browserExposure: false,
    persistent: true,
    allowedOperations: ['MRA_HTTP_AUTHORIZATION', 'CREDENTIAL_ROTATION', 'SECURITY_DIAGNOSTICS_METADATA'],
  },
  [EIS_SECRET_TYPE.MRA_TERMINAL_SECRET]: {
    classification: 'SECRET',
    maxLifetimeHours: 24 * 365,
    browserExposure: false,
    persistent: true,
    allowedOperations: [
      'MRA_ACTIVATION_CONFIRMATION',
      'MRA_REQUEST_MESSAGE_HASH',
      'MRA_OFFLINE_SIGN',
      'CREDENTIAL_ROTATION',
      'SECURITY_DIAGNOSTICS_METADATA',
    ],
  },
  [EIS_SECRET_TYPE.MRA_TERMINAL_ACTIVATION_CODE]: {
    classification: 'SECRET',
    maxLifetimeHours: 1,
    browserExposure: false,
    persistent: false,
    ephemeral: true,
    oneTime: true,
    allowedOperations: ['MRA_ACTIVATION_REQUEST', 'MRA_ACTIVATION_CONFIRMATION'],
  },
  [EIS_SECRET_TYPE.MRA_BUYER_AUTHORIZATION_CODE]: {
    classification: 'SECRET',
    maxLifetimeHours: 1,
    browserExposure: false,
    persistent: false,
    ephemeral: true,
    oneTime: true,
    allowedOperations: ['MRA_BUYER_TIN_AUTHORIZATION'],
  },
});

export const EIS_CRYPTO_OPERATION = Object.freeze({
  MRA_HTTP_AUTHORIZATION: 'MRA_HTTP_AUTHORIZATION',
  MRA_ACTIVATION_CONFIRMATION: 'MRA_ACTIVATION_CONFIRMATION',
  MRA_REQUEST_MESSAGE_HASH: 'MRA_REQUEST_MESSAGE_HASH',
  MRA_OFFLINE_SIGN: 'MRA_OFFLINE_SIGN',
  MRA_ACTIVATION_REQUEST: 'MRA_ACTIVATION_REQUEST',
  MRA_BUYER_TIN_AUTHORIZATION: 'MRA_BUYER_TIN_AUTHORIZATION',
  CREDENTIAL_ROTATION: 'CREDENTIAL_ROTATION',
  MASTER_KEY_REWRAP: 'MASTER_KEY_REWRAP',
  SECURITY_DIAGNOSTICS_METADATA: 'SECURITY_DIAGNOSTICS_METADATA',
});

export const CREDENTIAL_SECRET_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  EXPIRING: 'EXPIRING',
  EXPIRED: 'EXPIRED',
  ROTATION_PENDING: 'ROTATION_PENDING',
  ROTATED: 'ROTATED',
  REVOKED: 'REVOKED',
  INVALID: 'INVALID',
  ACCESS_BLOCKED: 'ACCESS_BLOCKED',
  DECRYPTION_FAILED: 'DECRYPTION_FAILED',
});
