/** Canonical analytics event catalogue — version analytics-events-2026-07-28 */

export const ANALYTICS_CATALOGUE_VERSION = 'analytics-events-2026-07-28';

export const ANALYTICS_EVENT_TYPES = Object.freeze({
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_STATUS_CHANGED: 'TENANT_STATUS_CHANGED',
  SUBSCRIPTION_STARTED: 'SUBSCRIPTION_STARTED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  PLATFORM_INVOICE_ISSUED: 'PLATFORM_INVOICE_ISSUED',
  PLATFORM_PAYMENT_SUCCEEDED: 'PLATFORM_PAYMENT_SUCCEEDED',
  USER_LOGIN: 'USER_LOGIN',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  // Phase 9 Wave 1 — commerce product meaningful actions (verified producers)
  SALES_INVOICE_POSTED: 'SALES_INVOICE_POSTED',
  POS_TRANSACTION_COMPLETED: 'POS_TRANSACTION_COMPLETED',
  MRA_EIS_TRANSACTION_ACCEPTED: 'MRA_EIS_TRANSACTION_ACCEPTED',
  // Scaffold — no free-for-all FEATURE_USED emitter
  LEAD_CREATED: 'LEAD_CREATED',
  FEATURE_USED: 'FEATURE_USED',
});

export const PRIVACY_CLASS = Object.freeze({
  INTERNAL: 'INTERNAL',
  FINANCE: 'FINANCE',
  PII: 'PII',
  SECURITY: 'SECURITY',
});

export const OUTBOX_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  DONE: 'DONE',
  DEAD: 'DEAD',
});

/** Events that may be emitted by Phase 4 / Phase 9 producers. */
export const VERIFIED_EMITTERS = new Set([
  ANALYTICS_EVENT_TYPES.TENANT_CREATED,
  ANALYTICS_EVENT_TYPES.TENANT_STATUS_CHANGED,
  ANALYTICS_EVENT_TYPES.SUBSCRIPTION_STARTED,
  ANALYTICS_EVENT_TYPES.SUBSCRIPTION_RENEWED,
  ANALYTICS_EVENT_TYPES.SUBSCRIPTION_CANCELLED,
  ANALYTICS_EVENT_TYPES.PLATFORM_INVOICE_ISSUED,
  ANALYTICS_EVENT_TYPES.PLATFORM_PAYMENT_SUCCEEDED,
  ANALYTICS_EVENT_TYPES.USER_LOGIN,
  ANALYTICS_EVENT_TYPES.ADMIN_LOGIN,
  ANALYTICS_EVENT_TYPES.SALES_INVOICE_POSTED,
  ANALYTICS_EVENT_TYPES.POS_TRANSACTION_COMPLETED,
  ANALYTICS_EVENT_TYPES.MRA_EIS_TRANSACTION_ACCEPTED,
]);

export const SCAFFOLD_ONLY = new Set([
  ANALYTICS_EVENT_TYPES.LEAD_CREATED,
  ANALYTICS_EVENT_TYPES.FEATURE_USED,
]);

export function privacyForEventType(eventType) {
  if (
    eventType === ANALYTICS_EVENT_TYPES.PLATFORM_INVOICE_ISSUED ||
    eventType === ANALYTICS_EVENT_TYPES.PLATFORM_PAYMENT_SUCCEEDED ||
    String(eventType).startsWith('SUBSCRIPTION_')
  ) {
    return PRIVACY_CLASS.FINANCE;
  }
  if (
    eventType === ANALYTICS_EVENT_TYPES.USER_LOGIN ||
    eventType === ANALYTICS_EVENT_TYPES.ADMIN_LOGIN
  ) {
    return PRIVACY_CLASS.PII;
  }
  return PRIVACY_CLASS.INTERNAL;
}

export function requiresTenantId(eventType) {
  return eventType !== ANALYTICS_EVENT_TYPES.ADMIN_LOGIN;
}
