export const ForecastMethod = Object.freeze({
  LAST_PERIOD: 'LAST_PERIOD',
  HISTORICAL_AVERAGE: 'HISTORICAL_AVERAGE',
  MOVING_AVERAGE: 'MOVING_AVERAGE',
  YEAR_OVER_YEAR_GROWTH: 'YEAR_OVER_YEAR_GROWTH',
  COMPOUND_GROWTH: 'COMPOUND_GROWTH',
  SEASONAL_GROWTH: 'SEASONAL_GROWTH',
  DRIVER_BASED: 'DRIVER_BASED',
  PERCENTAGE_OF_REVENUE: 'PERCENTAGE_OF_REVENUE',
  FIXED_SCHEDULE: 'FIXED_SCHEDULE',
  MANUAL_INPUT: 'MANUAL_INPUT',
  AI_SUGGESTED_WITH_REVIEW: 'AI_SUGGESTED_WITH_REVIEW',
});

export const ScenarioType = Object.freeze({
  CONSERVATIVE: 'CONSERVATIVE',
  EXPECTED: 'EXPECTED',
  OPTIMISTIC: 'OPTIMISTIC',
  STRESS: 'STRESS',
  CUSTOM: 'CUSTOM',
});

export const ForecastVersionStatus = Object.freeze({
  DRAFT: 'DRAFT',
  CALCULATING: 'CALCULATING',
  CALCULATED: 'CALCULATED',
  VALIDATING: 'VALIDATING',
  INVALID: 'INVALID',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
  FAILED: 'FAILED',
});

export const ForecastIntegrityStatus = Object.freeze({
  NOT_CALCULATED: 'NOT_CALCULATED',
  CALCULATING: 'CALCULATING',
  VALIDATING: 'VALIDATING',
  VALID: 'VALID',
  VALID_WITH_WARNINGS: 'VALID_WITH_WARNINGS',
  INVALID: 'INVALID',
  BLOCKED: 'BLOCKED',
});

export const BudgetStatus = Object.freeze({
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
  REJECTED: 'REJECTED',
});

export const AssumptionType = Object.freeze({
  PERCENTAGE: 'PERCENTAGE',
  ABSOLUTE_AMOUNT: 'ABSOLUTE_AMOUNT',
  DAYS: 'DAYS',
  RATE: 'RATE',
  COUNT: 'COUNT',
  BOOLEAN: 'BOOLEAN',
  SEASONAL_INDEX: 'SEASONAL_INDEX',
});

export const Granularity = Object.freeze({
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  ANNUAL: 'ANNUAL',
});

export const DataQualityStatus = Object.freeze({
  HIGH_CONFIDENCE: 'HIGH_CONFIDENCE',
  MODERATE_CONFIDENCE: 'MODERATE_CONFIDENCE',
  LIMITED_HISTORY: 'LIMITED_HISTORY',
  MATERIAL_EXCEPTIONS: 'MATERIAL_EXCEPTIONS',
  INCOMPLETE: 'INCOMPLETE',
  UNSUITABLE_FOR_AUTOMATIC_BASELINE: 'UNSUITABLE_FOR_AUTOMATIC_BASELINE',
});

export const VarianceFavourability = Object.freeze({
  FAVOURABLE: 'FAVOURABLE',
  UNFAVOURABLE: 'UNFAVOURABLE',
  NEUTRAL: 'NEUTRAL',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});
