export const AssessmentStatus = Object.freeze({
  DRAFT: 'DRAFT',
  CALCULATING: 'CALCULATING',
  CALCULATED: 'CALCULATED',
  VALIDATING: 'VALIDATING',
  INVALID: 'INVALID',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  REVIEWED: 'REVIEWED',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
  FAILED: 'FAILED',
});

export const IntegrityStatus = Object.freeze({
  NOT_CALCULATED: 'NOT_CALCULATED',
  CALCULATING: 'CALCULATING',
  VALIDATING: 'VALIDATING',
  VALID: 'VALID',
  VALID_WITH_WARNINGS: 'VALID_WITH_WARNINGS',
  INVALID: 'INVALID',
  BLOCKED: 'BLOCKED',
});

export const LoanPurpose = Object.freeze({
  WORKING_CAPITAL: 'WORKING_CAPITAL',
  INVENTORY_FINANCE: 'INVENTORY_FINANCE',
  ASSET_FINANCE: 'ASSET_FINANCE',
  EQUIPMENT_PURCHASE: 'EQUIPMENT_PURCHASE',
  VEHICLE_FINANCE: 'VEHICLE_FINANCE',
  PROPERTY_FINANCE: 'PROPERTY_FINANCE',
  BUSINESS_EXPANSION: 'BUSINESS_EXPANSION',
  CONTRACT_FINANCE: 'CONTRACT_FINANCE',
  REFINANCING: 'REFINANCING',
  OVERDRAFT: 'OVERDRAFT',
  REVOLVING_CREDIT: 'REVOLVING_CREDIT',
  OTHER_APPROVED_PURPOSE: 'OTHER_APPROVED_PURPOSE',
});

export const AmortizationMethod = Object.freeze({
  EQUAL_INSTALMENT: 'EQUAL_INSTALMENT',
  EQUAL_PRINCIPAL: 'EQUAL_PRINCIPAL',
  INTEREST_ONLY: 'INTEREST_ONLY',
  BULLET: 'BULLET',
  BALLOON: 'BALLOON',
});

export const RateType = Object.freeze({
  FIXED: 'FIXED',
  VARIABLE: 'VARIABLE',
});

export const AffordabilityStatus = Object.freeze({
  COMFORTABLE: 'COMFORTABLE',
  MANAGEABLE_WITH_CUSHION: 'MANAGEABLE_WITH_CUSHION',
  TIGHT: 'TIGHT',
  HIGH_RISK: 'HIGH_RISK',
  UNAFFORDABLE_UNDER_ASSUMPTIONS: 'UNAFFORDABLE_UNDER_ASSUMPTIONS',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
});

export const CovenantStatus = Object.freeze({
  COMPLIANT: 'COMPLIANT',
  COMPLIANT_WITH_LOW_HEADROOM: 'COMPLIANT_WITH_LOW_HEADROOM',
  WARNING: 'WARNING',
  BREACH: 'BREACH',
  WAIVED: 'WAIVED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  INSUFFICIENT_DATA: 'INSUFFICIENT_DATA',
});

export const DataQualityStatus = Object.freeze({
  VERIFIED: 'VERIFIED',
  SUBSTANTIALLY_VERIFIED: 'SUBSTANTIALLY_VERIFIED',
  PARTIALLY_VERIFIED: 'PARTIALLY_VERIFIED',
  LIMITED: 'LIMITED',
  MATERIAL_EXCEPTIONS: 'MATERIAL_EXCEPTIONS',
  UNSUITABLE_FOR_ASSESSMENT: 'UNSUITABLE_FOR_ASSESSMENT',
});

export const ReadinessBand = Object.freeze({
  STRONG_INTERNAL_READINESS: 'STRONG_INTERNAL_READINESS',
  GENERALLY_READY_WITH_ITEMS_TO_CONFIRM: 'GENERALLY_READY_WITH_ITEMS_TO_CONFIRM',
  MODERATE_READINESS_WITH_MATERIAL_GAPS: 'MODERATE_READINESS_WITH_MATERIAL_GAPS',
  WEAK_READINESS: 'WEAK_READINESS',
  NOT_READY_UNDER_CURRENT_ASSUMPTIONS: 'NOT_READY_UNDER_CURRENT_ASSUMPTIONS',
});

export const PROHIBITED_SCORE_ATTRIBUTES = Object.freeze([
  'race',
  'ethnicity',
  'religion',
  'gender',
  'sex',
  'politicalAffiliation',
  'health',
  'disability',
  'sexualOrientation',
]);

export const SCORE_MODEL_VERSION = 'READINESS_SCORE_V1';
export const DSCR_FORMULA_VERSION = 'DSCR_CFADS_OVER_DEBT_SERVICE_V1';
export const ICR_FORMULA_VERSION = 'ICR_EBITDA_OVER_INTEREST_V1';
export const DEBT_CAPACITY_FORMULA_VERSION = 'DEBT_CAPACITY_CFADS_TARGET_DSCR_V1';

export const ADVISORY_DISCLAIMER =
  'Internal advisory Loan Readiness estimate only — not a lender decision, credit bureau score, or guarantee of funding.';
