export const ActorType = Object.freeze({
  USER: 'USER',
  SERVICE_ACCOUNT: 'SERVICE_ACCOUNT',
  BACKGROUND_JOB: 'BACKGROUND_JOB',
  SCHEDULED_JOB: 'SCHEDULED_JOB',
  WEBHOOK: 'WEBHOOK',
  SYSTEM_PROCESS: 'SYSTEM_PROCESS',
  MIGRATION_PROCESS: 'MIGRATION_PROCESS',
  SUPPORT_AGENT: 'SUPPORT_AGENT',
  SUPER_ADMIN_IMPERSONATION: 'SUPER_ADMIN_IMPERSONATION',
  EMERGENCY_ACCESS: 'EMERGENCY_ACCESS',
});

export const AuthzDecision = Object.freeze({
  ALLOW: 'ALLOW',
  DENY: 'DENY',
  REQUIRE_REAUTHENTICATION: 'REQUIRE_REAUTHENTICATION',
  REQUIRE_MFA: 'REQUIRE_MFA',
  REQUIRE_APPROVAL: 'REQUIRE_APPROVAL',
  REQUIRE_ELEVATED_REVIEW: 'REQUIRE_ELEVATED_REVIEW',
});

export const ApprovalRequestStatus = Object.freeze({
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  IN_REVIEW: 'IN_REVIEW',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  SUPERSEDED: 'SUPERSEDED',
  INVALIDATED: 'INVALIDATED',
  EXECUTED: 'EXECUTED',
});

export const ApprovalDecisionType = Object.freeze({
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  RETURN_FOR_CORRECTION: 'RETURN_FOR_CORRECTION',
  ABSTAIN: 'ABSTAIN',
  REQUEST_INFORMATION: 'REQUEST_INFORMATION',
});

export const ApprovalMode = Object.freeze({
  SEQUENTIAL: 'SEQUENTIAL',
  PARALLEL: 'PARALLEL',
  ANY_ONE: 'ANY_ONE',
  ALL_REQUIRED: 'ALL_REQUIRED',
  QUORUM: 'QUORUM',
  CONDITIONAL: 'CONDITIONAL',
});

export const DataClassification = Object.freeze({
  PUBLIC: 'PUBLIC',
  INTERNAL: 'INTERNAL',
  CONFIDENTIAL: 'CONFIDENTIAL',
  HIGHLY_CONFIDENTIAL: 'HIGHLY_CONFIDENTIAL',
  RESTRICTED_FINANCIAL: 'RESTRICTED_FINANCIAL',
  RESTRICTED_IDENTITY: 'RESTRICTED_IDENTITY',
  RESTRICTED_PAYROLL: 'RESTRICTED_PAYROLL',
  RESTRICTED_BANKING: 'RESTRICTED_BANKING',
  RESTRICTED_TAX: 'RESTRICTED_TAX',
  RESTRICTED_OWNERSHIP: 'RESTRICTED_OWNERSHIP',
  RESTRICTED_COLLATERAL: 'RESTRICTED_COLLATERAL',
  SECRET_CREDENTIAL: 'SECRET_CREDENTIAL',
});

export const AlertSeverity = Object.freeze({
  INFORMATIONAL: 'INFORMATIONAL',
  LOW: 'LOW',
  MODERATE: 'MODERATE',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

export const ScopeType = Object.freeze({
  PLATFORM: 'PLATFORM',
  BUSINESS: 'BUSINESS',
  BRANCH: 'BRANCH',
  DEPARTMENT: 'DEPARTMENT',
  PROJECT: 'PROJECT',
  COST_CENTRE: 'COST_CENTRE',
  OWN_RECORDS: 'OWN_RECORDS',
  ASSIGNED_RECORDS: 'ASSIGNED_RECORDS',
  DOCUMENT_CLASS: 'DOCUMENT_CLASS',
});

export const AUDIT_EVENT_TYPES = Object.freeze({
  LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  SESSION_REVOKED: 'SESSION_REVOKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  MFA_ENABLED: 'MFA_ENABLED',
  MFA_DISABLED: 'MFA_DISABLED',
  MFA_CHALLENGE_FAILED: 'MFA_CHALLENGE_FAILED',
  ACCESS_ALLOWED: 'ACCESS_ALLOWED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  CROSS_BUSINESS_ACCESS_BLOCKED: 'CROSS_BUSINESS_ACCESS_BLOCKED',
  SENSITIVE_FIELD_ACCESS: 'SENSITIVE_FIELD_ACCESS',
  SENSITIVE_DOCUMENT_ACCESS: 'SENSITIVE_DOCUMENT_ACCESS',
  EXPORT_REQUESTED: 'EXPORT_REQUESTED',
  EXPORT_COMPLETED: 'EXPORT_COMPLETED',
  EXPORT_DENIED: 'EXPORT_DENIED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  MEMBERSHIP_REVOKED: 'MEMBERSHIP_REVOKED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  IMPERSONATION_STARTED: 'IMPERSONATION_STARTED',
  IMPERSONATION_ENDED: 'IMPERSONATION_ENDED',
  EMERGENCY_ACCESS_STARTED: 'EMERGENCY_ACCESS_STARTED',
  EMERGENCY_ACCESS_ENDED: 'EMERGENCY_ACCESS_ENDED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  APPROVAL_APPROVED: 'APPROVAL_APPROVED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_INVALIDATED: 'APPROVAL_INVALIDATED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  SOD_CONFLICT: 'SOD_CONFLICT',
  RATE_LIMIT_TRIGGERED: 'RATE_LIMIT_TRIGGERED',
  SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
  WEBHOOK_SIGNATURE_FAILED: 'WEBHOOK_SIGNATURE_FAILED',
  FILE_REJECTED: 'FILE_REJECTED',
  AUDIT_INTEGRITY_FAILURE: 'AUDIT_INTEGRITY_FAILURE',
  PRIVILEGE_ESCALATION_ATTEMPT: 'PRIVILEGE_ESCALATION_ATTEMPT',
  POLICY_BYPASS_ATTEMPT: 'POLICY_BYPASS_ATTEMPT',
  AI_GOVERNANCE_BLOCKED: 'AI_GOVERNANCE_BLOCKED',
});
