/** Product areas — repo-backed taxonomy (Phase 9 Wave 1). */

export const PRODUCT_AREAS = Object.freeze({
  CUSTOMER_AND_SALES: 'CUSTOMER_AND_SALES',
  INVENTORY_AND_COMMERCE: 'INVENTORY_AND_COMMERCE',
  PURCHASING_AND_EXPENSES: 'PURCHASING_AND_EXPENSES',
  ACCOUNTING_AND_FINANCE: 'ACCOUNTING_AND_FINANCE',
  REPORTING_AND_INTELLIGENCE: 'REPORTING_AND_INTELLIGENCE',
  WORKFORCE_AND_PAYROLL: 'WORKFORCE_AND_PAYROLL',
  ASSETS_AND_LIABILITIES: 'ASSETS_AND_LIABILITIES',
  RENTAL_AND_HIRING: 'RENTAL_AND_HIRING',
  TAX_AND_COMPLIANCE: 'TAX_AND_COMPLIANCE',
  MRA_EIS: 'MRA_EIS',
  BANKING_AND_CASH: 'BANKING_AND_CASH',
  CORE_PLATFORM: 'CORE_PLATFORM',
  ADMINISTRATION_AND_SECURITY: 'ADMINISTRATION_AND_SECURITY',
});
