/** Feature / module lifecycle states for catalogue entries. */

export const PRODUCT_LIFECYCLE = Object.freeze({
  ACTIVE: 'ACTIVE',
  BETA: 'BETA',
  DEPRECATED: 'DEPRECATED',
  RETIRED: 'RETIRED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

export const INSTRUMENTATION_STATE = Object.freeze({
  INSTRUMENTED: 'INSTRUMENTED',
  NOT_INSTRUMENTED: 'NOT_INSTRUMENTED',
  DISCOVERY_ONLY: 'DISCOVERY_ONLY',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});
