/**
 * Maps comprehensive_chart_of_accounts_template.xlsx rows to Insight Books CoA blueprint.
 * Template numbering differs from our hierarchy (1000=Assets root, not "Cash on Hand").
 */

/** @type {Array<{ templateCode: string, templateName: string, targetCode: string, parentCode: string, accountType: string, accountName?: string, createIfMissing?: boolean }>} */
export const COMPREHENSIVE_TEMPLATE_TO_BLUEPRINT = [
  { templateCode: '1000', templateName: 'Cash on Hand', targetCode: '1110', parentCode: '1100', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1010', templateName: 'Petty Cash', targetCode: '1120', parentCode: '1100', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1020', templateName: 'Bank - Operating', targetCode: '1130-03', parentCode: '1130', accountType: 'Asset', accountName: 'Bank - Operating', createIfMissing: true },
  { templateCode: '1030', templateName: 'Bank - Savings', targetCode: '1130-04', parentCode: '1130', accountType: 'Asset', accountName: 'Bank - Savings', createIfMissing: true },
  { templateCode: '1040', templateName: 'Mobile Money / Digital Wallet', targetCode: '1130-05', parentCode: '1130', accountType: 'Asset', accountName: 'Mobile Money / Digital Wallet', createIfMissing: true },
  { templateCode: '1050', templateName: 'Accounts Receivable', targetCode: '1200', parentCode: '1100', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1060', templateName: 'Allowance for Doubtful Debts', targetCode: '1205', parentCode: '1100', accountType: 'Asset', accountName: 'Allowance for Doubtful Debts', createIfMissing: true },
  { templateCode: '1070', templateName: 'Staff Advances', targetCode: '1215', parentCode: '1100', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1080', templateName: 'Inventory - Raw Materials', targetCode: '1320', parentCode: '1300', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1090', templateName: 'Inventory - Work in Progress', targetCode: '1335', parentCode: '1300', accountType: 'Asset', accountName: 'Work in Progress', createIfMissing: true },
  { templateCode: '1100', templateName: 'Inventory - Finished Goods', targetCode: '1310', parentCode: '1300', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1110', templateName: 'Prepaid Expenses', targetCode: '1210', parentCode: '1100', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1120', templateName: 'VAT Input / VAT Receivable', targetCode: '1220', parentCode: '1100', accountType: 'Asset', accountName: 'VAT Input / VAT Receivable', createIfMissing: true },
  { templateCode: '1130', templateName: 'Other Receivables', targetCode: '1230', parentCode: '1100', accountType: 'Asset', accountName: 'Other Receivables', createIfMissing: true },
  { templateCode: '1300', templateName: 'Land', targetCode: '1515', parentCode: '1500', accountType: 'Asset', accountName: 'Land', createIfMissing: true },
  { templateCode: '1310', templateName: 'Buildings', targetCode: '1516', parentCode: '1500', accountType: 'Asset', accountName: 'Buildings', createIfMissing: true },
  { templateCode: '1320', templateName: 'Machinery & Equipment', targetCode: '1517', parentCode: '1500', accountType: 'Asset', accountName: 'Machinery & Equipment', createIfMissing: true },
  { templateCode: '1330', templateName: 'Furniture & Fixtures', targetCode: '1520', parentCode: '1500', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1340', templateName: 'Vehicles', targetCode: '1530', parentCode: '1500', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1350', templateName: 'Computers & IT Equipment', targetCode: '1540', parentCode: '1500', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1360', templateName: 'Leasehold Improvements', targetCode: '1550', parentCode: '1500', accountType: 'Asset', accountName: 'Leasehold Improvements', createIfMissing: true },
  { templateCode: '1370', templateName: 'Intangible Assets', targetCode: '1920', parentCode: '1900', accountType: 'Asset', createIfMissing: false },
  { templateCode: '1380', templateName: 'Investments', targetCode: '1930', parentCode: '1900', accountType: 'Asset', accountName: 'Long-term Investments', createIfMissing: true },
  { templateCode: '1390', templateName: 'Accumulated Depreciation', targetCode: '1590', parentCode: '1500', accountType: 'Asset', createIfMissing: false },
  { templateCode: '2000', templateName: 'Accounts Payable', targetCode: '2110', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2010', templateName: 'Accrued Expenses', targetCode: '2140', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2020', templateName: 'Salaries Payable', targetCode: '2145', parentCode: '2100', accountType: 'Liability', accountName: 'Salaries Payable', createIfMissing: true },
  { templateCode: '2030', templateName: 'Interest Payable', targetCode: '2146', parentCode: '2100', accountType: 'Liability', accountName: 'Interest Payable', createIfMissing: true },
  { templateCode: '2040', templateName: 'Short-term Loan', targetCode: '2160', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2050', templateName: 'Tax Payable - Corporate Income Tax', targetCode: '2170', parentCode: '2100', accountType: 'Liability', accountName: 'Corporate Income Tax Payable', createIfMissing: true },
  { templateCode: '2060', templateName: 'VAT Output / VAT Payable', targetCode: '2120', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2070', templateName: 'Withholding Tax Payable', targetCode: '2125', parentCode: '2100', accountType: 'Liability', accountName: 'Withholding Tax Payable', createIfMissing: true },
  { templateCode: '2080', templateName: 'Dividends Payable', targetCode: '2147', parentCode: '2100', accountType: 'Liability', accountName: 'Dividends Payable', createIfMissing: true },
  { templateCode: '2090', templateName: 'Unearned Revenue', targetCode: '2150', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2100', templateName: 'PAYE Payable', targetCode: '2130', parentCode: '2100', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2110', templateName: 'Pension Contributions Payable', targetCode: '2135', parentCode: '2100', accountType: 'Liability', accountName: 'Pension Contributions Payable', createIfMissing: true },
  { templateCode: '2120', templateName: 'TEVET Levy Payable', targetCode: '2136', parentCode: '2100', accountType: 'Liability', accountName: 'TEVET Levy Payable', createIfMissing: true },
  { templateCode: '2300', templateName: 'Long-term Loan', targetCode: '2510', parentCode: '2500', accountType: 'Liability', createIfMissing: false },
  { templateCode: '2310', templateName: 'Lease Liability', targetCode: '2530', parentCode: '2500', accountType: 'Liability', accountName: 'Lease Liability', createIfMissing: true },
  { templateCode: '2320', templateName: 'Deferred Tax Liability', targetCode: '2540', parentCode: '2500', accountType: 'Liability', accountName: 'Deferred Tax Liability', createIfMissing: true },
  { templateCode: '3000', templateName: 'Share Capital', targetCode: '3100', parentCode: '3000', accountType: 'Equity', createIfMissing: false },
  { templateCode: '3010', templateName: 'Additional Paid-in Capital', targetCode: '3110', parentCode: '3000', accountType: 'Equity', accountName: 'Additional Paid-in Capital', createIfMissing: true },
  { templateCode: '3020', templateName: 'Retained Earnings', targetCode: '3200', parentCode: '3000', accountType: 'Equity', createIfMissing: false },
  { templateCode: '3030', templateName: 'Reserves', targetCode: '3210', parentCode: '3000', accountType: 'Equity', accountName: 'Reserves', createIfMissing: true },
  { templateCode: '3040', templateName: 'Owner Drawings / Dividends', targetCode: '3220', parentCode: '3000', accountType: 'Equity', accountName: 'Owner Drawings / Dividends', createIfMissing: true },
  { templateCode: '3050', templateName: 'Current Year Profit / Loss', targetCode: '3300', parentCode: '3000', accountType: 'Equity', createIfMissing: false },
  { templateCode: '4000', templateName: 'Sales Revenue', targetCode: '4100', parentCode: '4000', accountType: 'Income', createIfMissing: false },
  { templateCode: '4010', templateName: 'Service Revenue', targetCode: '4150', parentCode: '4000', accountType: 'Income', createIfMissing: false },
  { templateCode: '4020', templateName: 'Consultancy Fees', targetCode: '4160', parentCode: '4000', accountType: 'Income', accountName: 'Consultancy Fees', createIfMissing: true },
  { templateCode: '4030', templateName: 'Commission Income', targetCode: '4170', parentCode: '4000', accountType: 'Income', accountName: 'Commission Income', createIfMissing: true },
  { templateCode: '4040', templateName: 'Rental Income', targetCode: '4180', parentCode: '4000', accountType: 'Income', accountName: 'Rental Income', createIfMissing: true },
  { templateCode: '4050', templateName: 'Interest Income', targetCode: '4300', parentCode: '4000', accountType: 'Income', createIfMissing: false },
  { templateCode: '4060', templateName: 'Grant / Donation Income', targetCode: '4310', parentCode: '4000', accountType: 'Income', accountName: 'Grant / Donation Income', createIfMissing: true },
  { templateCode: '4070', templateName: 'Other Operating Income', targetCode: '4900', parentCode: '4000', accountType: 'Income', createIfMissing: false },
  { templateCode: '5010', templateName: 'Purchases', targetCode: '5110', parentCode: '5100', accountType: 'Expense', createIfMissing: false },
  { templateCode: '5020', templateName: 'Import Duties', targetCode: '5135', parentCode: '5100', accountType: 'Expense', accountName: 'Import Duties', createIfMissing: true },
  { templateCode: '5030', templateName: 'Freight Inwards', targetCode: '5130', parentCode: '5100', accountType: 'Expense', createIfMissing: false },
  { templateCode: '5040', templateName: 'Direct Labor', targetCode: '5140', parentCode: '5100', accountType: 'Expense', createIfMissing: false },
  { templateCode: '5050', templateName: 'Production Supplies', targetCode: '5145', parentCode: '5100', accountType: 'Expense', accountName: 'Production Supplies', createIfMissing: true },
  { templateCode: '5060', templateName: 'Manufacturing Overheads', targetCode: '5146', parentCode: '5100', accountType: 'Expense', accountName: 'Manufacturing Overheads', createIfMissing: true },
  { templateCode: '6000', templateName: 'Salaries & Wages', targetCode: '5200', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6010', templateName: 'Staff Benefits', targetCode: '5210', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6020', templateName: 'Office Rent', targetCode: '5300', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6030', templateName: 'Utilities', targetCode: '5310', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6040', templateName: 'Office Supplies', targetCode: '5320', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6050', templateName: 'Internet & Communication', targetCode: '5315', parentCode: '5000', accountType: 'Expense', accountName: 'Internet & Communication', createIfMissing: true },
  { templateCode: '6060', templateName: 'Insurance', targetCode: '5350', parentCode: '5000', accountType: 'Expense', accountName: 'Insurance', createIfMissing: true },
  { templateCode: '6070', templateName: 'Depreciation Expense', targetCode: '5400', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6080', templateName: 'Bank Charges', targetCode: '5500', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6090', templateName: 'Legal & Professional Fees', targetCode: '5360', parentCode: '5000', accountType: 'Expense', accountName: 'Legal & Professional Fees', createIfMissing: true },
  { templateCode: '6100', templateName: 'Advertising & Marketing', targetCode: '5330', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6110', templateName: 'Sales Commissions', targetCode: '5335', parentCode: '5000', accountType: 'Expense', accountName: 'Sales Commissions', createIfMissing: true },
  { templateCode: '6120', templateName: 'Delivery Expenses', targetCode: '5345', parentCode: '5000', accountType: 'Expense', accountName: 'Delivery Expenses', createIfMissing: true },
  { templateCode: '6130', templateName: 'Travel & Transport', targetCode: '5340', parentCode: '5000', accountType: 'Expense', createIfMissing: false },
  { templateCode: '6140', templateName: 'Fuel & Vehicle Expenses', targetCode: '5341', parentCode: '5340', accountType: 'Expense', accountName: 'Fuel & Vehicle Expenses', createIfMissing: true },
  { templateCode: '6150', templateName: 'Packaging', targetCode: '5147', parentCode: '5100', accountType: 'Expense', accountName: 'Packaging', createIfMissing: true },
  { templateCode: '7000', templateName: 'Interest Expense', targetCode: '5510', parentCode: '5000', accountType: 'Expense', accountName: 'Interest Expense', createIfMissing: true },
  { templateCode: '7010', templateName: 'Foreign Exchange Loss', targetCode: '5520', parentCode: '5000', accountType: 'Expense', accountName: 'Foreign Exchange Loss', createIfMissing: true },
  { templateCode: '7020', templateName: 'Bad Debts Write-off', targetCode: '5530', parentCode: '5000', accountType: 'Expense', accountName: 'Bad Debts Write-off', createIfMissing: true },
  { templateCode: '7030', templateName: 'Loss on Asset Disposal', targetCode: '5540', parentCode: '5000', accountType: 'Expense', accountName: 'Loss on Asset Disposal', createIfMissing: true },
  { templateCode: '7040', templateName: 'Penalties & Fines', targetCode: '5550', parentCode: '5000', accountType: 'Expense', accountName: 'Penalties & Fines', createIfMissing: true },
];

export const STRUCTURAL_ROOT_CODES = new Set(['1000', '2000', '3000', '4000', '5000']);

export const PARENT_DIRECT_RECLASS_TARGETS = {
  '1000': '1999',
  '2000': '2999',
  '3000': '3999',
  '4000': '4900',
  '5000': '5909',
  '3100': '500000',
  '5200': '5201',
  '5340': '5341',
  '5900': '5909',
  '1300': '1310',
  '5330': '5240',
};

export const MISPLACED_UNDER_5200 = {
  '5220': '5310',
  '5240': '5330',
  '5250': '5320',
  '5260': '5360',
  '5280': '5340',
};

export const DUPLICATE_SEMANTIC_MERGE = [
  { fromCode: '5017', toCode: '5018', reason: 'Duplicate Overtime allowance (typo Ovetime)' },
  { fromCode: '5019', toCode: '5350', reason: 'Software → IT & Hosting' },
  { fromCode: '5015', toCode: '5350', reason: 'Duplicate IT & Hosting' },
  { fromCode: '5230', toCode: '5201', reason: 'Salaries Expense → Admin & Management Salaries' },
  { fromCode: '1020', toCode: '1131', reason: 'Legacy Bank → National Bank of Malawi' },
];

/** Legacy tenant codes → official blueprint / template extension targets */
export const LEGACY_TO_OFFICIAL = [
  { fromCode: '1030', toCode: '1140', reason: 'Legacy Airtel Money → 1140' },
  { fromCode: '1040', toCode: '1141', reason: 'Legacy Mpamba → 1141' },
  { fromCode: '1050', toCode: '1131', reason: 'Legacy PayChangu → National Bank of Malawi' },
  { fromCode: '1130-01', toCode: '1131', reason: 'Retired bank slot → National Bank of Malawi' },
  { fromCode: '1130-02', toCode: '1132', reason: 'Retired bank slot → Standard Bank Malawi' },
  { fromCode: '1400', toCode: '1210', reason: 'Legacy prepaid → 1210' },
  { fromCode: '2200', toCode: '2140', reason: 'Legacy accrued → 2140' },
  { fromCode: '2300', toCode: '2160', reason: 'Legacy short-term loan → 2160' },
  { fromCode: '2400', toCode: '2510', reason: 'Legacy long-term loan → 2510' },
  { fromCode: '5003', toCode: '5360', reason: 'Professional Services → Legal & Professional Fees' },
  { fromCode: '5007', toCode: '5909', reason: 'Meals & Entertainment → unclassified expense' },
  { fromCode: '5009', toCode: '5909', reason: 'Meals duplicate → unclassified expense' },
  { fromCode: '5010', toCode: '5930', reason: 'Tax → Tax Expense' },
  { fromCode: '5016', toCode: '5930', reason: 'Taxes & Statutory → Tax Expense' },
  { fromCode: '5133', toCode: '5315', reason: 'Internet & Phone → Internet & Communication' },
  { fromCode: '5220', toCode: '5310', reason: 'Duplicate utilities → Utilities' },
  { fromCode: '5250', toCode: '5320', reason: 'Duplicate office supplies → Office Supplies' },
  { fromCode: '5260', toCode: '5360', reason: 'Duplicate professional services → Legal & Professional' },
  { fromCode: '5280', toCode: '5341', reason: 'Duplicate vehicle → Fuel & Vehicle Expenses' },
  { fromCode: '5240', toCode: '5330', reason: 'Duplicate marketing leaf → Marketing & Advertising' },
  { fromCode: '5150', toCode: '5330', reason: 'Legacy marketing expense → Marketing & Advertising' },
  { fromCode: '5160', toCode: '5350', reason: 'Legacy insurance → Insurance' },
  { fromCode: '5180', toCode: '5360', reason: 'Legacy professional fees → Legal & Professional Fees' },
  { fromCode: '5181', toCode: '5360', reason: 'Accounting fees → Legal & Professional Fees' },
  { fromCode: '5182', toCode: '5360', reason: 'Legal fees → Legal & Professional Fees' },
  { fromCode: '5195', toCode: '5400', reason: 'Legacy depreciation → Depreciation Expense' },
  { fromCode: '5196', toCode: '5530', reason: 'Legacy bad debt → Bad Debts Write-off' },
  { fromCode: '5199', toCode: '5341', reason: 'Legacy fuel/vehicle → Fuel & Vehicle Expenses' },
  { fromCode: '5202', toCode: '5201', reason: 'Sales wages → Admin & Management Salaries' },
  { fromCode: '5203', toCode: '5201', reason: 'Production wages → Admin & Management Salaries' },
  { fromCode: '5600', toCode: '5350', reason: 'Hosting → IT & Hosting' },
  { fromCode: '5601', toCode: '5350', reason: 'IT and Hosting duplicate → IT & Hosting' },
  { fromCode: '5701', toCode: '5350', reason: 'AI Subscriptions → IT & Hosting' },
  { fromCode: '5702', toCode: '5350', reason: 'Legacy custom IT & Hosting → IT & Hosting' },
  { fromCode: '5703', toCode: '5315', reason: 'Airtime and Internet → Internet & Communication' },
  { fromCode: '5970', toCode: '5201', reason: 'Legacy salary shell → Admin & Management Salaries' },
  { fromCode: '5971', toCode: '5201', reason: 'Legacy salary shell → Admin & Management Salaries' },
  { fromCode: '5101', toCode: '5340', reason: 'Legacy travel → Travel & Transport' },
  { fromCode: '5270', toCode: '5340', reason: 'Legacy travel → Travel & Transport' },
  { fromCode: '5630', toCode: '5340', reason: 'Legacy travel → Travel & Transport' },
  { fromCode: '5197', toCode: '5340', reason: 'Legacy travel → Travel & Transport' },
  { fromCode: '5198', toCode: '5340', reason: 'Legacy transport → Travel & Transport' },
  { fromCode: '5910', toCode: '5510', reason: 'Interest under 5900 → Interest Expense' },
  { fromCode: '5301', toCode: '5200', reason: 'Retired duplicate salary → Salaries & Wages' },
  { fromCode: '5920', toCode: '5540', reason: 'Loss on assets → Loss on Asset Disposal' },
  { fromCode: '2041', toCode: '2120', reason: 'Tax inflow → VAT Payable (MRA)' },
];
