import * as XLSX from 'xlsx';

/**
 * @param {Awaited<ReturnType<import('./openingBalanceReport.js').buildOpeningBalanceStatusReport>>} report
 * @param {{ businessName: string, generatedBy: string, generatedAt: Date }} meta
 */
export function generateOpeningBalanceWorkbook(report, meta) {
  const wb = XLSX.utils.book_new();
  const s = report.summary;

  const summaryRows = [
    ['Opening Balances Report'],
    ['Business', meta.businessName],
    ['Starting date', s.startingDate ? new Date(s.startingDate).toLocaleDateString() : '—'],
    ['Generated by', meta.generatedBy],
    ['Generated at', meta.generatedAt.toISOString()],
    ['Locked', s.locked ? 'Yes' : 'No'],
    [],
    ['Category', 'Total (MWK)'],
    ['Opening stock', s.stockTotal],
    ['Payment accounts', s.paymentAccountsTotal],
    ['Receivables', s.receivablesTotal],
    ['Payables', s.payablesTotal],
    ['Fixed assets', s.fixedAssetsTotal],
    ['Other liabilities', s.liabilitiesTotal],
    ['Bulk COA entry', s.bulkTotal],
    [],
    ['Opening Balance Equity (3190)', s.equityAccount.balance],
    ['Total debits (journals)', s.totalDebits],
    ['Total credits (journals)', s.totalCredits],
  ];

  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryRows), 'Summary');

  const detailHeader = [
    'Reference',
    'Date',
    'Type',
    'Description',
    'Amount',
    'Debits',
    'Credits',
  ];
  const detailRows = (report.journalEntries || []).map((j) => [
    j.reference || '',
    j.date ? new Date(j.date).toLocaleDateString() : '',
    j.type,
    j.description,
    j.amount,
    j.debits,
    j.credits,
  ]);

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.aoa_to_sheet([detailHeader, ...detailRows]),
    'Journal entries',
  );

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}
