// lib/permissionsMap.js
// Single source of truth for RBAC modules/actions + UI labels (Roles & Permissions in /users).

export const permissionModules = {
  dashboard: { label: 'Dashboard', actions: ['view'] },
  users: { label: 'User Management', actions: ['create', 'view', 'update', 'delete', 'export'] },
  roles: { label: 'Role Management', actions: ['create', 'view', 'update', 'delete', 'assign'] },
  system: { label: 'System / Tenant', actions: ['view', 'update', 'switchTenant'] },
  settings: { label: 'Settings', actions: ['view', 'update'] },
  eis: {
    label: 'MRA EIS Controls',
    actions: [
      'availabilityView',
      'participationView',
      'participationEnable',
      'participationPause',
      'participationDisable',
      'businessSettingsView',
      'businessSettingsManage',
      'setupStart',
      'setupResume',
      'readinessView',
      'auditView',
    ],
  },
  clients: { label: 'Client Management', actions: ['create', 'view', 'update', 'delete', 'export'] },
  sales: { label: 'POS', actions: ['create', 'view', 'update', 'delete', 'void', 'refund', 'export'] },
  quotations: { label: 'Quotations', actions: ['create', 'view', 'update', 'delete', 'convert', 'approve', 'export'] },
  invoices: { label: 'Invoicing', actions: ['create', 'view', 'update', 'delete', 'send', 'markAsPaid', 'export'] },
  expenses: { label: 'Expense Tracking', actions: ['create', 'view', 'update', 'delete', 'approve', 'export'] },
  payments: { label: 'Payment Accounts', actions: ['create', 'view', 'update', 'delete', 'export'] },
  budgets: { label: 'Budget & Forecast', actions: ['create', 'view', 'update', 'delete', 'approve', 'export'] },
  branches: { label: 'Branches', actions: ['create', 'view', 'update', 'delete'] },
  reports: { label: 'Reports', actions: ['view', 'export'] },
  inventory: { label: 'Stock / Inventory', actions: ['create', 'view', 'update', 'delete', 'adjust', 'export'] },
  purchases: { label: 'Purchases & Procurement', actions: ['create', 'view', 'update', 'delete', 'approve', 'export'] },
  suppliers: { label: 'Suppliers', actions: ['create', 'view', 'update', 'delete', 'export'] },
  hr: { label: 'HR Management', actions: ['create', 'view', 'update', 'delete', 'export'] },
  payroll: { label: 'Payroll', actions: ['create', 'view', 'update', 'delete', 'process', 'export'] },
  leave: { label: 'Leave Management', actions: ['create', 'view', 'update', 'delete', 'approve', 'export'] },
  tax: { label: 'Tax', actions: ['view', 'update', 'export', 'settle'] },
  taxManagement: {
    label: 'Tax Management',
    actions: ['view', 'update', 'export', 'settle'],
  },

  generalLedger: { label: 'General Ledger', actions: ['view', 'export'] },
  journalEntries: { label: 'Journal Entries', actions: ['create', 'view', 'update', 'delete', 'post', 'export'] },
  accounts: { label: 'Chart of Accounts', actions: ['create', 'view', 'update', 'delete', 'export'] },
  openingBalances: { label: 'Opening Balances', actions: ['view', 'manage', 'post', 'export'] },
  trialBalance: { label: 'Trial Balance', actions: ['view', 'export'] },
  assets: { label: 'Fixed Assets', actions: ['create', 'view', 'update', 'delete', 'export'] },
  rentals: {
    label: 'Rentals & Hiring',
    actions: ['create', 'view', 'update', 'delete', 'export'],
  },
  accounting: { label: 'Accounting Hub', actions: ['view', 'manage', 'export'] },
  bankReconciliation: {
    label: 'Bank Reconciliation',
    actions: [
      'view',
      'configure',
      'import',
      'match',
      'adjust',
      'review',
      'approve',
      'complete',
      'reopen',
      'reverse',
      'export',
    ],
  },
  equity: {
    label: 'Equity Management',
    actions: [
      'view',
      'viewDashboard',
      'viewOwners',
      'manageOwners',
      'verifyOwners',
      'viewShareholders',
      'manageShareholders',
      'viewHoldings',
      'manageShareClasses',
      'issueShares',
      'transferShares',
      'redeemShares',
      'viewContributions',
      'createContribution',
      'approveContribution',
      'postContribution',
      'createDrawing',
      'approveDrawing',
      'postDrawing',
      'viewDividends',
      'declareDividend',
      'approveDividend',
      'payDividend',
      'manageReserves',
      'createPriorPeriodAdjustment',
      'approvePriorPeriodAdjustment',
      'requestReversal',
      'reconcile',
      'viewStatements',
      'export',
      'viewDocuments',
      'manageDocuments',
      'viewAudit',
      'manageConfiguration',
      'viewSensitiveOwnershipDetails',
    ],
  },
  accountingClose: {
    label: 'Month-End / Year-End Close',
    actions: [
      'view',
      'viewDashboard',
      'createRun',
      'runReadiness',
      'completeTasks',
      'addEvidence',
      'manageExceptions',
      'createAdjustments',
      'approveAdjustments',
      'postAdjustments',
      'generateAdjustedTrialBalance',
      'reviewFinancialStatements',
      'generateClosingJournals',
      'reviewClosingJournals',
      'approveClosingJournals',
      'postClosingJournals',
      'generatePostClosingTrialBalance',
      'generateSnapshots',
      'approveYearClose',
      'closeYear',
      'requestReopen',
      'approveReopen',
      'reopenYear',
      'reverseClosingJournals',
      'recloseYear',
      'export',
      'viewAudit',
      'manageConfiguration',
      'overrideMateriality',
      'acceptCriticalException',
    ],
  },
  loanReadiness: {
    label: 'Loan Readiness Centre',
    actions: [
      'view',
      'viewDashboard',
      'manageConfiguration',
      'createAssessment',
      'calculateAssessment',
      'reviewAssessment',
      'approveAssessment',
      'createLoanRequest',
      'approveLoanRequest',
      'manageLenderProfiles',
      'manageProductProfiles',
      'calculateDebtCapacity',
      'runStressTests',
      'viewSensitiveRatios',
      'manageCovenants',
      'viewDocuments',
      'manageDocuments',
      'reviewDocuments',
      'viewCollateral',
      'manageCollateral',
      'reviewCollateral',
      'createScoreOverride',
      'approveScoreOverride',
      'manageRiskFindings',
      'manageActions',
      'runAICommentary',
      'reviewAICommentary',
      'generateLenderPackage',
      'generateBoardPack',
      'export',
      'viewAudit',
    ],
  },
  financialPlanning: {
    label: 'Financial Planning & Forecasting',
    actions: [
      'view',
      'viewDashboard',
      'manageConfiguration',
      'viewBudgets',
      'createBudget',
      'editDraftBudget',
      'reviewBudget',
      'approveBudget',
      'viewForecasts',
      'createForecast',
      'recalculateForecast',
      'manageScenarios',
      'manageAssumptions',
      'approveAssumptions',
      'createOverrides',
      'approveOverrides',
      'viewDetailedDrivers',
      'viewSensitivePayrollPlans',
      'runAISuggestions',
      'reviewAISuggestions',
      'reviewForecast',
      'approveForecast',
      'snapshotForecast',
      'export',
      'viewAudit',
      'manageImports',
    ],
  },
  securityGovernance: {
    label: 'Security & Governance',
    actions: [
      'viewDashboard',
      'viewUsers',
      'manageUsers',
      'viewRoles',
      'manageRoles',
      'assignSensitivePermission',
      'viewApprovals',
      'manageApprovalPolicies',
      'decideApproval',
      'viewSod',
      'manageSod',
      'viewAudit',
      'exportAudit',
      'viewAlerts',
      'manageIncidents',
      'manageSessions',
      'manageApiKeys',
      'manageServiceAccounts',
      'impersonate',
      'emergencyAccess',
      'manageDelegations',
      'viewExportHistory',
      'manageConfiguration',
    ],
  },
};

export function generateFullPermissions() {
  const permissions = {};
  for (const [module, { actions }] of Object.entries(permissionModules)) {
    permissions[module] = {};
    for (const action of actions) {
      permissions[module][action] = true;
    }
  }
  return permissions;
}
