import * as XLSX from 'xlsx';

/**
 * @param {Awaited<ReturnType<import('./payeSummaryService.js').buildPayeSummaryReport>>} report
 * @param {{ businessName: string, periodLabel: string, generatedBy: string, generatedAt: Date }} meta
 */
export function generatePayeSummaryWorkbook(report, meta) {
  const wb = XLSX.utils.book_new();

  const summaryRows = [
    ['PAYE Summary Report'],
    ['Business', meta.businessName],
    ['Period', meta.periodLabel],
    ['Generated by', meta.generatedBy],
    ['Generated at', meta.generatedAt.toISOString()],
    [],
    ['Metric', 'Amount (MWK)'],
    ['Employees in payroll', report.summary.employeeCount],
    ['Payroll lines', report.summary.payrollLineCount],
    ['Total gross pay', report.summary.totalGrossPay],
    ['Total taxable income', report.summary.totalTaxableIncome],
    ['Total PAYE deducted', report.summary.totalPayeDeducted],
    ['Total PAYE remitted to MRA', report.summary.totalPayeRemitted ?? 0],
    ['PAYE outstanding (MRA)', report.summary.totalPayeOutstanding ?? 0],
    ['Total net pay', report.summary.totalNetPay],
    ['Pension employee', report.summary.totalPensionEmployee],
    ['Pension employer', report.summary.totalPensionEmployer],
    ['Salary advance recovery', report.summary.totalAdvanceRecovery],
    ['Other deductions', report.summary.totalOtherDeductions],
  ];

  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryRows), 'Summary');

  const detailHeader = [
    'Employee No',
    'Employee Name',
    'Department',
    'Basic Salary',
    'Taxable Allowances',
    'Non-taxable Allowances',
    'Gross Pay',
    'Taxable Income',
    'PAYE',
    'Pension (Emp)',
    'Pension (Er)',
    'Advance Recovery',
    'Other Deductions',
    'Net Pay',
    'Period',
    'Payroll Status',
    'Journal Status',
  ];

  const detailRows = report.rows.map((r) => [
    r.employeeNumber,
    r.employeeName,
    r.department,
    r.basicSalary,
    r.taxableAllowances,
    r.nonTaxableAllowances,
    r.grossPay,
    r.taxableIncome,
    r.payeDeducted,
    r.pensionEmployee,
    r.pensionEmployer,
    r.advanceRecovery,
    r.otherDeductions,
    r.netPay,
    r.payrollPeriod?.label || '',
    r.payrollStatus,
    r.journalStatus,
  ]);

  const totalRow = [
    'TOTALS',
    '',
    '',
    '',
    '',
    '',
    report.summary.totalGrossPay,
    report.summary.totalTaxableIncome,
    report.summary.totalPayeDeducted,
    report.summary.totalPensionEmployee,
    report.summary.totalPensionEmployer,
    report.summary.totalAdvanceRecovery,
    report.summary.totalOtherDeductions,
    report.summary.totalNetPay,
    '',
    '',
    '',
  ];

  XLSX.utils.book_append_sheet(
    wb,
    XLSX.utils.aoa_to_sheet([detailHeader, ...detailRows, totalRow]),
    'Detail',
  );

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}
