/**
 * Phase 17 — Restriction capability matrix.
 * ALLOW / BLOCK / CONDITIONAL per operation × reason.
 */

export const COMPLIANCE_OPERATION = Object.freeze({
  ACTIVATE_TERMINAL: 'ACTIVATE_TERMINAL',
  FINALIZE_EIS_SALE: 'FINALIZE_EIS_SALE',
  CREATE_FISCAL_SNAPSHOT: 'CREATE_FISCAL_SNAPSHOT',
  ALLOCATE_FISCAL_NUMBER: 'ALLOCATE_FISCAL_NUMBER',
  TRANSMIT_ONLINE: 'TRANSMIT_ONLINE',
  RETRY_ONLINE: 'RETRY_ONLINE',
  RUN_RECONCILIATION: 'RUN_RECONCILIATION',
  SYNC_CONFIGURATION: 'SYNC_CONFIGURATION',
  QUERY_BLOCK_STATUS: 'QUERY_BLOCK_STATUS',
  REQUEST_UNBLOCK: 'REQUEST_UNBLOCK',
  VIEW_ACCEPTED_RECEIPT: 'VIEW_ACCEPTED_RECEIPT',
  REPRINT_ACCEPTED_RECEIPT: 'REPRINT_ACCEPTED_RECEIPT',
  ENTER_OFFLINE: 'ENTER_OFFLINE',
  CREATE_OFFLINE_SALE: 'CREATE_OFFLINE_SALE',
  SIGN_OFFLINE_ENVELOPE: 'SIGN_OFFLINE_ENVELOPE',
  UPLOAD_OFFLINE_QUEUE: 'UPLOAD_OFFLINE_QUEUE',
});

const BLOCK = 'BLOCK';
const ALLOW = 'ALLOW';

/** Default matrix rows for critical reasons */
const MATRIX = Object.freeze({
  MRA_TERMINAL_BLOCKED: {
    [COMPLIANCE_OPERATION.FINALIZE_EIS_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.CREATE_FISCAL_SNAPSHOT]: BLOCK,
    [COMPLIANCE_OPERATION.ALLOCATE_FISCAL_NUMBER]: BLOCK,
    [COMPLIANCE_OPERATION.TRANSMIT_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.RETRY_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.ENTER_OFFLINE]: BLOCK,
    [COMPLIANCE_OPERATION.CREATE_OFFLINE_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.SIGN_OFFLINE_ENVELOPE]: BLOCK,
    [COMPLIANCE_OPERATION.UPLOAD_OFFLINE_QUEUE]: BLOCK,
    [COMPLIANCE_OPERATION.RUN_RECONCILIATION]: ALLOW,
    [COMPLIANCE_OPERATION.SYNC_CONFIGURATION]: ALLOW,
    [COMPLIANCE_OPERATION.QUERY_BLOCK_STATUS]: ALLOW,
    [COMPLIANCE_OPERATION.REQUEST_UNBLOCK]: ALLOW,
    [COMPLIANCE_OPERATION.VIEW_ACCEPTED_RECEIPT]: ALLOW,
    [COMPLIANCE_OPERATION.REPRINT_ACCEPTED_RECEIPT]: ALLOW,
  },
  PLATFORM_EMERGENCY_PAUSE: {
    [COMPLIANCE_OPERATION.FINALIZE_EIS_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.TRANSMIT_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.RETRY_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.ENTER_OFFLINE]: BLOCK,
    [COMPLIANCE_OPERATION.CREATE_OFFLINE_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.SIGN_OFFLINE_ENVELOPE]: BLOCK,
    [COMPLIANCE_OPERATION.UPLOAD_OFFLINE_QUEUE]: BLOCK,
    [COMPLIANCE_OPERATION.ALLOCATE_FISCAL_NUMBER]: BLOCK,
    [COMPLIANCE_OPERATION.VIEW_ACCEPTED_RECEIPT]: ALLOW,
    [COMPLIANCE_OPERATION.RUN_RECONCILIATION]: ALLOW,
    [COMPLIANCE_OPERATION.QUERY_BLOCK_STATUS]: ALLOW,
  },
  FISCAL_SEQUENCE_CONFLICT: {
    [COMPLIANCE_OPERATION.ALLOCATE_FISCAL_NUMBER]: BLOCK,
    [COMPLIANCE_OPERATION.FINALIZE_EIS_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.CREATE_FISCAL_SNAPSHOT]: BLOCK,
    [COMPLIANCE_OPERATION.TRANSMIT_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.RUN_RECONCILIATION]: ALLOW,
    [COMPLIANCE_OPERATION.VIEW_ACCEPTED_RECEIPT]: ALLOW,
  },
  TERMINAL_CONFIGURATION_STALE: {
    [COMPLIANCE_OPERATION.FINALIZE_EIS_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.TRANSMIT_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.RETRY_ONLINE]: BLOCK,
    [COMPLIANCE_OPERATION.SYNC_CONFIGURATION]: ALLOW,
    [COMPLIANCE_OPERATION.RUN_RECONCILIATION]: ALLOW,
    [COMPLIANCE_OPERATION.VIEW_ACCEPTED_RECEIPT]: ALLOW,
  },
  OFFLINE_DEVICE_COMPROMISED: {
    [COMPLIANCE_OPERATION.ENTER_OFFLINE]: BLOCK,
    [COMPLIANCE_OPERATION.CREATE_OFFLINE_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.SIGN_OFFLINE_ENVELOPE]: BLOCK,
    [COMPLIANCE_OPERATION.UPLOAD_OFFLINE_QUEUE]: BLOCK,
    [COMPLIANCE_OPERATION.TRANSMIT_ONLINE]: ALLOW, // unrelated online terminal may continue
    [COMPLIANCE_OPERATION.VIEW_ACCEPTED_RECEIPT]: ALLOW,
  },
  OFFLINE_QUEUE_INTEGRITY_FAILURE: {
    [COMPLIANCE_OPERATION.CREATE_OFFLINE_SALE]: BLOCK,
    [COMPLIANCE_OPERATION.UPLOAD_OFFLINE_QUEUE]: BLOCK,
    [COMPLIANCE_OPERATION.SIGN_OFFLINE_ENVELOPE]: BLOCK,
    [COMPLIANCE_OPERATION.RUN_RECONCILIATION]: ALLOW,
  },
});

export function evaluateCapabilityAgainstRestrictions({
  requestedOperation,
  restrictions = [],
} = {}) {
  const blockers = [];
  for (const r of restrictions) {
    if (!['ACTIVE', 'ACKNOWLEDGED', 'REMEDIATION_PENDING', 'UNBLOCK_REQUEST_PENDING', 'CLEARANCE_PENDING_VERIFICATION'].includes(r.state)) {
      continue;
    }
    const row = MATRIX[r.reasonCode] || MATRIX.MRA_TERMINAL_BLOCKED;
    const decision = row[requestedOperation];
    if (decision === BLOCK) {
      blockers.push({
        restrictionId: r.id,
        reasonCode: r.reasonCode,
        sourceType: r.sourceType,
        decision: BLOCK,
      });
    }
  }
  return {
    allowed: blockers.length === 0,
    blockers,
    matrixVersion: 'restriction-capability-matrix-v1',
  };
}

export function getRestrictionCapabilityMatrix() {
  return MATRIX;
}
