export const LegalStructure = Object.freeze({
  SOLE_PROPRIETORSHIP: 'SOLE_PROPRIETORSHIP',
  PARTNERSHIP: 'PARTNERSHIP',
  PRIVATE_COMPANY: 'PRIVATE_COMPANY',
  PUBLIC_COMPANY: 'PUBLIC_COMPANY',
  NON_PROFIT: 'NON_PROFIT',
  COOPERATIVE: 'COOPERATIVE',
  OTHER_SUPPORTED_STRUCTURE: 'OTHER_SUPPORTED_STRUCTURE',
});

export const EquityModel = Object.freeze({
  OWNER_CAPITAL: 'OWNER_CAPITAL',
  PARTNER_CAPITAL: 'PARTNER_CAPITAL',
  SHARE_CAPITAL: 'SHARE_CAPITAL',
  FUND_BALANCE: 'FUND_BALANCE',
  HYBRID_APPROVED_MODEL: 'HYBRID_APPROVED_MODEL',
});

export const RelationshipType = Object.freeze({
  OWNER: 'OWNER',
  PARTNER: 'PARTNER',
  SHAREHOLDER: 'SHAREHOLDER',
  MEMBER: 'MEMBER',
  BENEFICIAL_OWNER: 'BENEFICIAL_OWNER',
  TRUSTEE: 'TRUSTEE',
  OTHER: 'OTHER',
});

export const OwnershipStatus = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXIT_PENDING: 'EXIT_PENDING',
  EXITED: 'EXITED',
  DECEASED: 'DECEASED',
  ARCHIVED: 'ARCHIVED',
});

export const EquityTransactionType = Object.freeze({
  CAPITAL_CONTRIBUTION: 'CAPITAL_CONTRIBUTION',
  NON_CASH_CONTRIBUTION: 'NON_CASH_CONTRIBUTION',
  SHARE_ISSUANCE: 'SHARE_ISSUANCE',
  SHARE_PREMIUM: 'SHARE_PREMIUM',
  CAPITAL_CALL: 'CAPITAL_CALL',
  OWNER_DRAWING: 'OWNER_DRAWING',
  PARTNER_DRAWING: 'PARTNER_DRAWING',
  DIVIDEND_DECLARATION: 'DIVIDEND_DECLARATION',
  DIVIDEND_PAYMENT: 'DIVIDEND_PAYMENT',
  SHARE_TRANSFER: 'SHARE_TRANSFER',
  SHARE_REDEMPTION: 'SHARE_REDEMPTION',
  CAPITAL_REDUCTION: 'CAPITAL_REDUCTION',
  OWNER_LOAN_ADVANCE: 'OWNER_LOAN_ADVANCE',
  OWNER_LOAN_REPAYMENT: 'OWNER_LOAN_REPAYMENT',
  OWNER_LOAN_CONVERSION: 'OWNER_LOAN_CONVERSION',
  EQUITY_RECLASSIFICATION: 'EQUITY_RECLASSIFICATION',
  OPENING_EQUITY: 'OPENING_EQUITY',
  PRIOR_PERIOD_EQUITY_ADJUSTMENT: 'PRIOR_PERIOD_EQUITY_ADJUSTMENT',
  RESERVE_TRANSFER: 'RESERVE_TRANSFER',
  OTHER_APPROVED_EQUITY_EVENT: 'OTHER_APPROVED_EQUITY_EVENT',
});

export const EquityTxStatus = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  POSTING: 'POSTING',
  POSTED: 'POSTED',
  REJECTED: 'REJECTED',
  CANCELLED_BEFORE_POSTING: 'CANCELLED_BEFORE_POSTING',
  REVERSAL_PENDING: 'REVERSAL_PENDING',
  REVERSED: 'REVERSED',
  FAILED: 'FAILED',
  REQUIRES_REVIEW: 'REQUIRES_REVIEW',
});

/** Max ownership in basis points of scale-8 decimal (100% = 10000000000 for scale 8? use minor of 100.00000000) */
export const OWNERSHIP_PERCENT_SCALE = 8;
export const ONE_HUNDRED_PERCENT_MINOR = 100 * 10 ** OWNERSHIP_PERCENT_SCALE; // 10_000_000_000 for scale 8 → wait 100 * 10^8 = 10_000_000_000

export const EQUITY_MAPPING_PURPOSES = Object.freeze([
  'OWNER_CAPITAL',
  'PARTNER_CAPITAL',
  'SHARE_CAPITAL',
  'SHARE_PREMIUM',
  'CAPITAL_CONTRIBUTIONS',
  'OWNER_DRAWINGS',
  'PARTNER_DRAWINGS',
  'DIVIDENDS_DECLARED',
  'DIVIDENDS_PAYABLE',
  'RETAINED_EARNINGS',
  'CURRENT_YEAR_EARNINGS',
  'OTHER_EQUITY_RESERVE',
  'REVALUATION_RESERVE',
  'OPENING_BALANCE_EQUITY',
  'OWNER_LOAN_LIABILITY',
  'OWNER_LOAN_RECEIVABLE',
]);

export const HIGH_RISK_TYPES = Object.freeze([
  EquityTransactionType.SHARE_ISSUANCE,
  EquityTransactionType.SHARE_REDEMPTION,
  EquityTransactionType.CAPITAL_REDUCTION,
  EquityTransactionType.NON_CASH_CONTRIBUTION,
  EquityTransactionType.DIVIDEND_DECLARATION,
  EquityTransactionType.PRIOR_PERIOD_EQUITY_ADJUSTMENT,
  EquityTransactionType.RESERVE_TRANSFER,
  EquityTransactionType.OWNER_LOAN_CONVERSION,
]);
