/**
 * CRM nav — Phase 11–13 Activities / Reminders / templates / automation / Activity reports.
 * Routes gated via NAV_PERMISSION_MAP; Lead ≠ Opportunity ≠ SupportTicket ≠ CsCase.
 * Activity ≠ Audit/Analytics; never alias CsTask / Support email threads.
 */

export const CRM_BASE = '/insightbooks/crm';

export const CRM_PERMISSIONS = Object.freeze({
  view: 'systemAdmin.crm.view',
  viewLeads: 'systemAdmin.crm.viewLeads',
  viewAccounts: 'systemAdmin.crm.viewAccounts',
  viewContacts: 'systemAdmin.crm.viewContacts',
  pipelineView: 'systemAdmin.crm.pipeline.view',
  opportunitiesView: 'systemAdmin.crm.opportunities.view',
  activitiesView: 'systemAdmin.crm.activities.view',
});

export const CRM_NAV_ITEM = Object.freeze({
  href: CRM_BASE,
  text: 'CRM',
  textKey: 'admin-shell.nav.items.crm',
  icon: 'Briefcase',
  subItems: Object.freeze([
    {
      href: `${CRM_BASE}/my-work`,
      text: 'My Work',
      textKey: 'admin-shell.nav.items.crmMyWork',
    },
    {
      href: `${CRM_BASE}/leads`,
      text: 'Leads',
      textKey: 'admin-shell.nav.items.crmLeads',
    },
    {
      href: `${CRM_BASE}/pipeline`,
      text: 'Pipeline',
      textKey: 'admin-shell.nav.items.crmPipeline',
    },
    {
      href: `${CRM_BASE}/opportunities`,
      text: 'Opportunities',
      textKey: 'admin-shell.nav.items.crmOpportunities',
    },
    {
      href: `${CRM_BASE}/activities`,
      text: 'Activities',
      textKey: 'admin-shell.nav.items.crmActivities',
    },
    {
      href: `${CRM_BASE}/tasks`,
      text: 'Tasks',
      textKey: 'admin-shell.nav.items.crmTasks',
    },
    {
      href: `${CRM_BASE}/follow-ups`,
      text: 'Follow-Ups',
      textKey: 'admin-shell.nav.items.crmFollowUps',
    },
    {
      href: `${CRM_BASE}/calls`,
      text: 'Calls',
      textKey: 'admin-shell.nav.items.crmCalls',
    },
    {
      href: `${CRM_BASE}/emails`,
      text: 'Emails',
      textKey: 'admin-shell.nav.items.crmEmails',
    },
    {
      href: `${CRM_BASE}/meetings`,
      text: 'Meetings',
      textKey: 'admin-shell.nav.items.crmMeetings',
    },
    {
      href: `${CRM_BASE}/demos`,
      text: 'Demos',
      textKey: 'admin-shell.nav.items.crmDemos',
    },
    {
      href: `${CRM_BASE}/calendar`,
      text: 'Calendar',
      textKey: 'admin-shell.nav.items.crmCalendar',
    },
    {
      href: `${CRM_BASE}/reminders`,
      text: 'Reminders',
      textKey: 'admin-shell.nav.items.crmReminders',
    },
    {
      href: `${CRM_BASE}/activity-reports`,
      text: 'Activity Reports',
      textKey: 'admin-shell.nav.items.crmActivityReports',
    },
    {
      href: `${CRM_BASE}/accounts`,
      text: 'Accounts',
      textKey: 'admin-shell.nav.items.crmAccounts',
    },
    {
      href: `${CRM_BASE}/contacts`,
      text: 'Contacts',
      textKey: 'admin-shell.nav.items.crmContacts',
    },
  ]),
});

/** @type {Array<{ id: string, label: string, labelKey: string, hintKey: string, href: string, exact?: boolean, wave: number, readiness: string, permission: string }>} */
export const CRM_SECTIONS = [
  {
    id: 'my-work',
    label: 'My Work',
    labelKey: 'admin-pages.crm.sections.myWork',
    hintKey: 'admin-pages.crm.sectionHints.myWork',
    href: `${CRM_BASE}/my-work`,
    wave: 4,
    readiness: 'live',
    permission: CRM_PERMISSIONS.viewLeads,
  },
  {
    id: 'leads',
    label: 'Leads',
    labelKey: 'admin-pages.crm.sections.leads',
    hintKey: 'admin-pages.crm.sectionHints.leads',
    href: `${CRM_BASE}/leads`,
    wave: 4,
    readiness: 'live',
    permission: CRM_PERMISSIONS.viewLeads,
  },
  {
    id: 'pipeline',
    label: 'Pipeline',
    labelKey: 'admin-pages.crm.sections.pipeline',
    hintKey: 'admin-pages.crm.sectionHints.pipeline',
    href: `${CRM_BASE}/pipeline`,
    wave: 12,
    readiness: 'live',
    permission: CRM_PERMISSIONS.pipelineView,
  },
  {
    id: 'opportunities',
    label: 'Opportunities',
    labelKey: 'admin-pages.crm.sections.opportunities',
    hintKey: 'admin-pages.crm.sectionHints.opportunities',
    href: `${CRM_BASE}/opportunities`,
    wave: 12,
    readiness: 'live',
    permission: CRM_PERMISSIONS.opportunitiesView,
  },
  {
    id: 'activities',
    label: 'Activities',
    labelKey: 'admin-pages.crm.sections.activities',
    hintKey: 'admin-pages.crm.sectionHints.activities',
    href: `${CRM_BASE}/activities`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'tasks',
    label: 'Tasks',
    labelKey: 'admin-pages.crm.sections.tasks',
    hintKey: 'admin-pages.crm.sectionHints.tasks',
    href: `${CRM_BASE}/tasks`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'follow-ups',
    label: 'Follow-Ups',
    labelKey: 'admin-pages.crm.sections.followUps',
    hintKey: 'admin-pages.crm.sectionHints.followUps',
    href: `${CRM_BASE}/follow-ups`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'calls',
    label: 'Calls',
    labelKey: 'admin-pages.crm.sections.calls',
    hintKey: 'admin-pages.crm.sectionHints.calls',
    href: `${CRM_BASE}/calls`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'emails',
    label: 'Emails',
    labelKey: 'admin-pages.crm.sections.emails',
    hintKey: 'admin-pages.crm.sectionHints.emails',
    href: `${CRM_BASE}/emails`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'meetings',
    label: 'Meetings',
    labelKey: 'admin-pages.crm.sections.meetings',
    hintKey: 'admin-pages.crm.sectionHints.meetings',
    href: `${CRM_BASE}/meetings`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'demos',
    label: 'Demos',
    labelKey: 'admin-pages.crm.sections.demos',
    hintKey: 'admin-pages.crm.sectionHints.demos',
    href: `${CRM_BASE}/demos`,
    wave: 14,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'demo-requests',
    label: 'Demo Requests',
    labelKey: 'admin-pages.crm.sections.demoRequests',
    hintKey: 'admin-pages.crm.sectionHints.demoRequests',
    href: `${CRM_BASE}/demos/requests`,
    wave: 14,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'calendar',
    label: 'Calendar',
    labelKey: 'admin-pages.crm.sections.calendar',
    hintKey: 'admin-pages.crm.sectionHints.calendar',
    href: `${CRM_BASE}/calendar`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'reminders',
    label: 'Reminders',
    labelKey: 'admin-pages.crm.sections.reminders',
    hintKey: 'admin-pages.crm.sectionHints.reminders',
    href: `${CRM_BASE}/reminders`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'templates',
    label: 'Templates',
    labelKey: 'admin-pages.crm.sections.templates',
    hintKey: 'admin-pages.crm.sectionHints.templates',
    href: `${CRM_BASE}/templates`,
    wave: 13,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'rules',
    label: 'Automation rules',
    labelKey: 'admin-pages.crm.sections.rules',
    hintKey: 'admin-pages.crm.sectionHints.rules',
    href: `${CRM_BASE}/rules`,
    wave: 13,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'activity-reports',
    label: 'Activity reports',
    labelKey: 'admin-pages.crm.sections.activityReports',
    hintKey: 'admin-pages.crm.sectionHints.activityReports',
    href: `${CRM_BASE}/activity-reports`,
    wave: 13,
    readiness: 'foundation',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'accounts',
    label: 'Accounts',
    labelKey: 'admin-pages.crm.sections.accounts',
    hintKey: 'admin-pages.crm.sectionHints.accounts',
    href: `${CRM_BASE}/accounts`,
    wave: 4,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.viewAccounts,
  },
  {
    id: 'contacts',
    label: 'Contacts',
    labelKey: 'admin-pages.crm.sections.contacts',
    hintKey: 'admin-pages.crm.sectionHints.contacts',
    href: `${CRM_BASE}/contacts`,
    wave: 4,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.viewContacts,
  },
  {
    id: 'duplicates',
    label: 'Duplicates',
    labelKey: 'admin-pages.crm.sections.duplicates',
    hintKey: 'admin-pages.crm.sectionHints.duplicates',
    href: `${CRM_BASE}/duplicates`,
    wave: 4,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.viewLeads,
  },
  {
    id: 'reports',
    label: 'Reports',
    labelKey: 'admin-pages.crm.sections.reports',
    hintKey: 'admin-pages.crm.sectionHints.reports',
    href: `${CRM_BASE}/reports`,
    wave: 4,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.view,
  },
  {
    id: 'foundations',
    label: 'Foundations',
    labelKey: 'admin-pages.crm.sections.foundations',
    hintKey: 'admin-pages.crm.sectionHints.foundations',
    href: `${CRM_BASE}/foundations`,
    wave: 4,
    readiness: 'stub',
    permission: CRM_PERMISSIONS.view,
  },
];

export function isCrmSectionActive(pathname, section) {
  if (!pathname || !section?.href) return false;
  if (section.exact) {
    return pathname === section.href || pathname === `${section.href}/`;
  }
  return pathname === section.href || pathname.startsWith(`${section.href}/`);
}
