/**
 * Phase 17 Wave 1 — Customer Onboarding catalogue (Request + Project spine).
 * Handoff ≠ Request ≠ Project. Never fabricates onboarding complete.
 */

import { CRM_NUMBER_PREFIX } from '../../crm/catalogue.js';

export const ONBOARDING_REQUEST_NUMBER_RE = /^ONR-\d{4}-\d{6}$/;
export const ONBOARDING_PROJECT_NUMBER_RE = /^ONB-\d{4}-\d{6}$/;

export const ONBOARDING_REQUEST_SOURCE = Object.freeze({
  PHASE_16_ONBOARDING_HANDOFF: 'PHASE_16_ONBOARDING_HANDOFF',
  EXISTING_CUSTOMER_EXPANSION: 'EXISTING_CUSTOMER_EXPANSION',
  PLAN_UPGRADE: 'PLAN_UPGRADE',
  ADD_ON_ACTIVATION: 'ADD_ON_ACTIVATION',
  CUSTOMER_SUCCESS_REQUEST: 'CUSTOMER_SUCCESS_REQUEST',
  MANUAL_APPROVED: 'MANUAL_APPROVED',
  LEGACY_MIGRATION: 'LEGACY_MIGRATION',
  API: 'API',
  OTHER: 'OTHER',
});

export const ONBOARDING_REQUEST_STATUS = Object.freeze({
  NEW: 'NEW',
  VALIDATING: 'VALIDATING',
  INFORMATION_REQUIRED: 'INFORMATION_REQUIRED',
  DUPLICATE_REVIEW_REQUIRED: 'DUPLICATE_REVIEW_REQUIRED',
  READY: 'READY',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CONVERTED_TO_PROJECT: 'CONVERTED_TO_PROJECT',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  CANCELLED: 'CANCELLED',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
});

export const ONBOARDING_REQUEST_STATUSES = Object.freeze(
  Object.values(ONBOARDING_REQUEST_STATUS)
);

export const ONBOARDING_TYPE = Object.freeze({
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS',
  ENTERPRISE: 'ENTERPRISE',
  MULTI_BUSINESS: 'MULTI_BUSINESS',
  MULTI_BRANCH: 'MULTI_BRANCH',
  MRA_EIS: 'MRA_EIS',
  DATA_MIGRATION: 'DATA_MIGRATION',
  TRAINING_LED: 'TRAINING_LED',
  CUSTOMER_EXPANSION: 'CUSTOMER_EXPANSION',
  PLAN_UPGRADE: 'PLAN_UPGRADE',
  ADD_ON: 'ADD_ON',
  PARTNER_LED: 'PARTNER_LED',
  RESELLER_LED: 'RESELLER_LED',
  CUSTOM_APPROVED: 'CUSTOM_APPROVED',
});

export const ONBOARDING_PROJECT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  REQUEST_VALIDATION: 'REQUEST_VALIDATION',
  READY_FOR_KICKOFF: 'READY_FOR_KICKOFF',
  KICKOFF_SCHEDULING: 'KICKOFF_SCHEDULING',
  KICKOFF_COMPLETED: 'KICKOFF_COMPLETED',
  PLANNING: 'PLANNING',
  IN_PROGRESS: 'IN_PROGRESS',
  GO_LIVE_READINESS: 'GO_LIVE_READINESS',
  READY_FOR_GO_LIVE: 'READY_FOR_GO_LIVE',
  GO_LIVE_SCHEDULED: 'GO_LIVE_SCHEDULED',
  GO_LIVE_IN_PROGRESS: 'GO_LIVE_IN_PROGRESS',
  LIVE: 'LIVE',
  STABILISATION: 'STABILISATION',
  HANDOVER_PENDING: 'HANDOVER_PENDING',
  COMPLETION_PENDING: 'COMPLETION_PENDING',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_OPEN_ITEMS: 'COMPLETED_WITH_OPEN_ITEMS',
  /** Explicit Phase 21 completion-with-gaps (alias surface; same terminal family). */
  COMPLETED_WITH_GAPS: 'COMPLETED_WITH_GAPS',
  PAUSED: 'PAUSED',
  BLOCKED: 'BLOCKED',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  ARCHIVED: 'ARCHIVED',
});

export const ONBOARDING_TEMPLATE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
});

export const WAVE1_STANDARD_TEMPLATE_CODE = 'STANDARD_WAVE1';

export const ONBOARDING_TASK_ACTOR_TYPE = Object.freeze({
  INTERNAL: 'INTERNAL',
  CUSTOMER: 'CUSTOMER',
  SHARED: 'SHARED',
  SYSTEM_VERIFICATION: 'SYSTEM_VERIFICATION',
});

export const ONBOARDING_TASK_STATUS = Object.freeze({
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  WAIVED: 'WAIVED',
});

export const ONBOARDING_EVIDENCE_STATUS = Object.freeze({
  EVIDENCE_SUBMITTED: 'EVIDENCE_SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
});

export const ONBOARDING_DEPENDENCY_TYPE = Object.freeze({
  FINISH_TO_START: 'FINISH_TO_START',
  START_TO_START: 'START_TO_START',
  FINISH_TO_FINISH: 'FINISH_TO_FINISH',
  START_TO_FINISH: 'START_TO_FINISH',
});

export const ONBOARDING_RESPONSIBILITY_PARTY = Object.freeze({
  CUSTOMER: 'CUSTOMER',
  INSIGHTBOOKS: 'INSIGHTBOOKS',
  SHARED: 'SHARED',
});

export const ONBOARDING_CHANGE_REQUEST_REASON = Object.freeze({
  SCOPE_MISMATCH: 'SCOPE_MISMATCH',
  COMMERCIAL_AMENDMENT_REQUIRED: 'COMMERCIAL_AMENDMENT_REQUIRED',
  OTHER: 'OTHER',
});

export const CUSTOMER_PORTAL_NOT_CONFIGURED = 'CUSTOMER_PORTAL_NOT_CONFIGURED';

export const MEETING_SERVICE_UNAVAILABLE = 'MEETING_SERVICE_UNAVAILABLE';

export const ONBOARDING_READINESS_STATUS = Object.freeze({
  READY: 'READY',
  NOT_READY: 'NOT_READY',
  UNKNOWN: 'UNKNOWN',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

/** Phase 21 Wave 1 — handoff package validation. UNKNOWN never equals VALID. */
export const ONBOARDING_HANDOFF_VALIDATION_STATUS = Object.freeze({
  VALID: 'VALID',
  VALID_WITH_WARNINGS: 'VALID_WITH_WARNINGS',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  UNKNOWN: 'UNKNOWN',
  INVALID: 'INVALID',
});

/** Phase 21 Wave 3 — go-live decision (SoD; ≠ schedule/execute alone). */
export const GO_LIVE_DECISION = Object.freeze({
  GO: 'GO',
  GO_WITH_CONDITIONS: 'GO_WITH_CONDITIONS',
  NO_GO: 'NO_GO',
  DEFERRED: 'DEFERRED',
  CANCELLED: 'CANCELLED',
});

/** Phase 21 Wave 3 — Phase 22 Training handoff package states (handoff only). */
export const PHASE22_TRAINING_HANDOFF_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  READY: 'READY',
  SENT: 'SENT',
  ACCEPTED_BY_TRAINING: 'ACCEPTED_BY_TRAINING',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
  SUPERSEDED: 'SUPERSEDED',
});

export const ONBOARDING_DOMAIN_CONTRACT = Object.freeze({
  surface: '/insightbooks/customer-success/onboarding',
  /** PRD Phase 21 (tree phase-17 alias retained in docs / code path) */
  phase: 21,
  prdPhase: 21,
  treePhaseAlias: 17,
  wave: 4,
  handoffImpliesExecution: false,
  fabricateOnboardingCompleteForbidden: true,
  tenantGlForbidden: true,
  trainingCompletionForbidden: true,
  trainingDeliveryForbidden: true,
  workstreamMaterialisationDeferred: false,
  inventZeroesForbidden: true,
  rsvpEqualsAttendanceForbidden: true,
  customerPortalStatus: CUSTOMER_PORTAL_NOT_CONFIGURED,
  silentEntitlementEscalationForbidden: true,
  unknownReadinessEqualsReadyForbidden: true,
  goLiveSuccessImpliesCompletedForbidden: true,
  progressEqualsCompletionForbidden: true,
  progressEqualsReadinessForbidden: true,
  readinessEqualsCompletionForbidden: true,
  completionEqualsAdoptionForbidden: true,
  phase8InventCompletedForbidden: true,
  inventLineageIntactForbidden: true,
});

export function getOnboardingDomainContract() {
  return { ...ONBOARDING_DOMAIN_CONTRACT };
}

export { CRM_NUMBER_PREFIX };
