/**
 * PRD Phase 22 Customer Training catalogue (tree phase-18 code alias).
 * Handoff ≠ Request ≠ Program. RSVP ≠ attendance. Never fabricates trainingCompleted.
 */

import { CRM_NUMBER_PREFIX } from '../../crm/catalogue.js';

export const TRAINING_REQUEST_NUMBER_RE = /^TRQ-\d{4}-\d{6}$/;
export const TRAINING_PROGRAM_NUMBER_RE = /^TRN-\d{4}-\d{6}$/;
export const TRAINING_COHORT_NUMBER_RE = /^COH-\d{4}-\d{6}$/;
export const TRAINING_SESSION_NUMBER_RE = /^TRS-\d{4}-\d{6}$/;
export const TRAINING_CERTIFICATE_NUMBER_RE = /^IB-TRN-CERT-\d{4}-\d{6}$/;

export const TRAINING_REQUEST_SOURCE = Object.freeze({
  /** Primary — Phase 21 onboarding → Phase 22 Training handoff */
  PHASE_21_TRAINING_HANDOFF: 'PHASE_21_TRAINING_HANDOFF',
  /** Legacy aliases (resolve → PHASE_21_TRAINING_HANDOFF) */
  PHASE_16_TRAINING_HANDOFF: 'PHASE_16_TRAINING_HANDOFF',
  PHASE_17_ONBOARDING_REQUIREMENT: 'PHASE_17_ONBOARDING_REQUIREMENT',
  CUSTOMER_SUCCESS_REQUEST: 'CUSTOMER_SUCCESS_REQUEST',
  SUPPORT_RECOMMENDATION: 'SUPPORT_RECOMMENDATION',
  PRODUCT_ADOPTION_INTERVENTION: 'PRODUCT_ADOPTION_INTERVENTION',
  CUSTOMER_REQUEST: 'CUSTOMER_REQUEST',
  PLAN_UPGRADE: 'PLAN_UPGRADE',
  ADD_ON_ACTIVATION: 'ADD_ON_ACTIVATION',
  NEW_USER_REQUEST: 'NEW_USER_REQUEST',
  REFRESHER_REQUEST: 'REFRESHER_REQUEST',
  MRA_EIS_REQUEST: 'MRA_EIS_REQUEST',
  MANUAL_APPROVED: 'MANUAL_APPROVED',
  LEGACY_MIGRATION: 'LEGACY_MIGRATION',
  API: 'API',
  OTHER: 'OTHER',
});

/** Mislabelled legacy source codes → PRD-correct primary. */
export const TRAINING_REQUEST_SOURCE_ALIASES = Object.freeze({
  [TRAINING_REQUEST_SOURCE.PHASE_16_TRAINING_HANDOFF]:
    TRAINING_REQUEST_SOURCE.PHASE_21_TRAINING_HANDOFF,
  [TRAINING_REQUEST_SOURCE.PHASE_17_ONBOARDING_REQUIREMENT]:
    TRAINING_REQUEST_SOURCE.PHASE_21_TRAINING_HANDOFF,
});

/**
 * Resolve a request source to its PRD-canonical code.
 * Legacy PHASE_16 / PHASE_17 training/onboarding labels map → PHASE_21_TRAINING_HANDOFF.
 */
export function resolveTrainingRequestSource(source) {
  const code = source != null ? String(source).trim().toUpperCase() : '';
  if (!code) return null;
  return TRAINING_REQUEST_SOURCE_ALIASES[code] || code;
}

/** Phase 22 Wave 1 — handoff package validation. UNKNOWN never equals VALID. */
export const TRAINING_HANDOFF_VALIDATION_STATUS = Object.freeze({
  VALID: 'VALID',
  VALID_WITH_WARNINGS: 'VALID_WITH_WARNINGS',
  CORRECTION_REQUIRED: 'CORRECTION_REQUIRED',
  RECONCILIATION_FAILED: 'RECONCILIATION_FAILED',
  INFORMATION_REQUIRED: 'INFORMATION_REQUIRED',
  DATA_QUALITY_BLOCKED: 'DATA_QUALITY_BLOCKED',
  DUPLICATE_HANDOFF: 'DUPLICATE_HANDOFF',
  SUPERSEDED: 'SUPERSEDED',
  REJECTED: 'REJECTED',
  BLOCKED: 'BLOCKED',
  UNKNOWN: 'UNKNOWN',
  INVALID: 'INVALID',
});

export const TRAINING_REQUEST_STATUS = Object.freeze({
  NEW: 'NEW',
  VALIDATING: 'VALIDATING',
  INFORMATION_REQUIRED: 'INFORMATION_REQUIRED',
  DUPLICATE_REVIEW_REQUIRED: 'DUPLICATE_REVIEW_REQUIRED',
  READY: 'READY',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CONVERTED_TO_PROGRAM: 'CONVERTED_TO_PROGRAM',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  CANCELLED: 'CANCELLED',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
});

export const TRAINING_REQUEST_STATUSES = Object.freeze(
  Object.values(TRAINING_REQUEST_STATUS)
);

export const TRAINING_TYPE = Object.freeze({
  CUSTOMER_ONBOARDING: 'CUSTOMER_ONBOARDING',
  TENANT_ADMINISTRATOR: 'TENANT_ADMINISTRATOR',
  BUSINESS_ADMINISTRATOR: 'BUSINESS_ADMINISTRATOR',
  BRANCH_ADMINISTRATOR: 'BRANCH_ADMINISTRATOR',
  FINANCE_ACCOUNTING: 'FINANCE_ACCOUNTING',
  INVENTORY: 'INVENTORY',
  POINT_OF_SALE: 'POINT_OF_SALE',
  SALES_CRM: 'SALES_CRM',
  HR_PAYROLL: 'HR_PAYROLL',
  PROJECT_MANAGEMENT: 'PROJECT_MANAGEMENT',
  ASSET_MANAGEMENT: 'ASSET_MANAGEMENT',
  PROCUREMENT: 'PROCUREMENT',
  REPORTING: 'REPORTING',
  MRA_EIS: 'MRA_EIS',
  TECHNICAL_INTEGRATION: 'TECHNICAL_INTEGRATION',
  REFRESHER: 'REFRESHER',
  NEW_USER: 'NEW_USER',
  TRAIN_THE_TRAINER: 'TRAIN_THE_TRAINER',
  CUSTOMER_EXPANSION: 'CUSTOMER_EXPANSION',
  PLAN_UPGRADE: 'PLAN_UPGRADE',
  ADD_ON: 'ADD_ON',
  CUSTOM_APPROVED: 'CUSTOM_APPROVED',
});

export const TRAINING_PROGRAM_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  REQUIREMENTS_REVIEW: 'REQUIREMENTS_REVIEW',
  CURRICULUM_PINNED: 'CURRICULUM_PINNED',
  PARTICIPANT_PLANNING: 'PARTICIPANT_PLANNING',
  TRAINER_ASSIGNMENT: 'TRAINER_ASSIGNMENT',
  SCHEDULING: 'SCHEDULING',
  READY_TO_START: 'READY_TO_START',
  IN_PROGRESS: 'IN_PROGRESS',
  ASSESSMENT_IN_PROGRESS: 'ASSESSMENT_IN_PROGRESS',
  RETAKE_REVIEW: 'RETAKE_REVIEW',
  COMPLETION_REVIEW: 'COMPLETION_REVIEW',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_GAPS: 'COMPLETED_WITH_GAPS',
  PAUSED: 'PAUSED',
  AT_RISK: 'AT_RISK',
  BLOCKED: 'BLOCKED',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  ARCHIVED: 'ARCHIVED',
});

export const TRAINING_CURRICULUM_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
});

export const WAVE1_ONBOARDING_CURRICULUM_CODE = 'CUSTOMER_ONBOARDING_WAVE1';

export const VIRTUAL_PROVIDER_NOT_CONFIGURED = 'VIRTUAL_PROVIDER_NOT_CONFIGURED';
export const MEETING_SERVICE_UNAVAILABLE = 'MEETING_SERVICE_UNAVAILABLE';

export const TRAINING_PARTICIPANT_VERIFICATION = Object.freeze({
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  UNKNOWN: 'UNKNOWN',
  REJECTED: 'REJECTED',
});

export const TRAINING_ENROLMENT_STATUS = Object.freeze({
  ENROLLED: 'ENROLLED',
  REGISTERED: 'REGISTERED',
  WAITLISTED: 'WAITLISTED',
  COMPLETED: 'COMPLETED',
  WITHDRAWN: 'WITHDRAWN',
  DEFERRED: 'DEFERRED',
  TRANSFERRED: 'TRANSFERRED',
});

/** Invitation lifecycle — SENT ≠ DELIVERED ≠ REGISTERED ≠ attendance. */
export const TRAINING_INVITATION_STATUS = Object.freeze({
  QUEUED: 'QUEUED',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  REGISTERED: 'REGISTERED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

export const TRAINING_COHORT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const TRAINING_SESSION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  RESCHEDULED: 'RESCHEDULED',
  CANCELLED: 'CANCELLED',
});

export const TRAINING_CONFLICT_STATE = Object.freeze({
  NO_CONFLICT: 'NO_CONFLICT',
  WARNING: 'WARNING',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  BLOCKED: 'BLOCKED',
  UNKNOWN: 'UNKNOWN',
});

export const TRAINING_ATTENDANCE_STATUS = Object.freeze({
  PRESENT: 'PRESENT',
  PRESENT_LATE: 'PRESENT_LATE',
  PRESENT_PARTIAL: 'PRESENT_PARTIAL',
  LEFT_EARLY: 'LEFT_EARLY',
  EXCUSED_ABSENCE: 'EXCUSED_ABSENCE',
  UNEXCUSED_ABSENCE: 'UNEXCUSED_ABSENCE',
  NO_SHOW: 'NO_SHOW',
  MAKE_UP_REQUIRED: 'MAKE_UP_REQUIRED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  UNKNOWN: 'UNKNOWN',
});

export const TRAINING_ATTENDANCE_SOURCE = Object.freeze({
  TRAINER_CONFIRMED: 'TRAINER_CONFIRMED',
  PARTICIPANT_CHECK_IN: 'PARTICIPANT_CHECK_IN',
  SIGNED_DOCUMENT: 'SIGNED_DOCUMENT',
  AUTHORISED_CORRECTION: 'AUTHORISED_CORRECTION',
  PROVIDER_RECORD: 'PROVIDER_RECORD',
  INVITATION_DELIVERY: 'INVITATION_DELIVERY',
  CALENDAR_ACCEPTANCE: 'CALENDAR_ACCEPTANCE',
  MEETING_LINK_ACCESS: 'MEETING_LINK_ACCESS',
});

export const TRAINING_ATTENDANCE_FORBIDDEN_SOURCES = Object.freeze([
  TRAINING_ATTENDANCE_SOURCE.INVITATION_DELIVERY,
  TRAINING_ATTENDANCE_SOURCE.CALENDAR_ACCEPTANCE,
  TRAINING_ATTENDANCE_SOURCE.MEETING_LINK_ACCESS,
]);

export const TRAINING_MATERIAL_CLASSIFICATION = Object.freeze({
  PUBLIC: 'PUBLIC',
  INTERNAL: 'INTERNAL',
  RESTRICTED: 'RESTRICTED',
});

export const TRAINING_EXERCISE_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PASSED: 'PASSED',
  RETRY_REQUIRED: 'RETRY_REQUIRED',
  WAIVED: 'WAIVED',
});

export const TRAINING_ASSESSMENT_TYPE = Object.freeze({
  KNOWLEDGE_CHECK: 'KNOWLEDGE_CHECK',
  PRACTICAL: 'PRACTICAL',
  ROLE_BASED: 'ROLE_BASED',
  MRA_EIS: 'MRA_EIS',
});

export const TRAINING_ATTEMPT_STATUS = Object.freeze({
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMITTED: 'SUBMITTED',
  GRADED: 'GRADED',
  FINALISED: 'FINALISED',
  EXPIRED: 'EXPIRED',
});

export const TRAINING_RESULT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  FINALISED: 'FINALISED',
});

export const TRAINING_COMPLETION_STATUS = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_GAPS: 'COMPLETED_WITH_GAPS',
  NOT_COMPLETED: 'NOT_COMPLETED',
});

export const TRAINING_CERTIFICATE_TYPE = Object.freeze({
  PARTICIPATION: 'PARTICIPATION',
  COMPLETION: 'COMPLETION',
  TTT: 'TTT',
  MRA_EIS: 'MRA_EIS',
  ROLE_SPECIFIC: 'ROLE_SPECIFIC',
  CUSTOM_APPROVED: 'CUSTOM_APPROVED',
});

export const TRAINING_CERTIFICATE_VERIFICATION = Object.freeze({
  VALID: 'VALID',
  REVOKED: 'REVOKED',
  UNKNOWN: 'UNKNOWN',
});

export const TRAINING_COMPLETION_POLICY_V1 = 'training-completion-policy-v1';
export const TRAINING_HEALTH_RULES_VERSION = 'training-health-v1';
export const TRAINING_PROGRESS_RULES_VERSION = 'training-progress-v1';

export const TRAINING_DOMAIN_CONTRACT = Object.freeze({
  surface: '/insightbooks/customer-success/training',
  /** PRD Phase 22 (tree phase-18 alias retained in docs / code path) */
  phase: 22,
  prdPhase: 22,
  treePhaseAlias: 18,
  wave: 4,
  handoffImpliesExecution: false,
  fabricateTrainingCompleteForbidden: true,
  tenantGlForbidden: true,
  sessionsDeferred: false,
  attendanceDeferred: false,
  assessmentsDeferred: false,
  inventZeroesForbidden: true,
  rsvpEqualsAttendanceForbidden: true,
  certificateAccreditationForbidden: true,
  productionDataInPracticeEnvForbidden: true,
  productionFiscalInExercisesForbidden: true,
  csHandoffOverwritesCustomerHealthForbidden: true,
  paHandoffFabricatesProductEventsForbidden: true,
  participantsAutoLeadsForbidden: true,
  attendanceMarketingAttributionForbidden: true,
  progressEqualsQualityForbidden: true,
  progressEqualsCompletionForbidden: true,
  completionEqualsAdoptionForbidden: true,
  trainingEqualsMarketingAttributionForbidden: true,
  virtualProviderStatus: VIRTUAL_PROVIDER_NOT_CONFIGURED,
});

/** Certificate eligibility — UNKNOWN ≠ issue. */
export const TRAINING_CERTIFICATE_ELIGIBILITY = Object.freeze({
  ELIGIBLE: 'ELIGIBLE',
  INELIGIBLE: 'INELIGIBLE',
  UNKNOWN: 'UNKNOWN',
});

export const TRAINING_CS_OUTCOME_HANDOFF_TYPE = 'PHASE_22_TRAINING_CS_OUTCOME_HANDOFF';
export const TRAINING_PA_OUTCOME_HANDOFF_TYPE = 'PHASE_22_TRAINING_PA_OUTCOME_HANDOFF';

export const TRAINING_FORBIDDEN_FISCAL_PLANES = Object.freeze([
  'PRODUCTION_GL',
  'PRODUCTION_JOURNALS',
  'PRODUCTION_STOCK',
  'MRA_FISCAL',
  'PRODUCTION_MRA',
  'LIVE_GL',
  'LIVE_JOURNALS',
]);

export function getTrainingDomainContract() {
  return { ...TRAINING_DOMAIN_CONTRACT };
}

export function getVirtualProviderStatus() {
  return VIRTUAL_PROVIDER_NOT_CONFIGURED;
}

export { CRM_NUMBER_PREFIX };
