/**
 * Phase 15 Wave 1 — commercial document catalogue (statuses, families, sources).
 * APPROVED ≠ ISSUED. Tenant Quotation = WRONG_DOMAIN.
 */

export const CRM_PROPOSAL_REQUEST_STATUS = Object.freeze({
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  INFORMATION_REQUIRED: 'INFORMATION_REQUIRED',
  QUALIFIED: 'QUALIFIED',
  REJECTED: 'REJECTED',
  DUPLICATE: 'DUPLICATE',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  CONVERTED: 'CONVERTED',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_PROPOSAL_REQUEST_STATUSES = Object.freeze(
  Object.values(CRM_PROPOSAL_REQUEST_STATUS)
);

export const CRM_PROPOSAL_REQUEST_TRANSITION_TABLE = Object.freeze({
  [CRM_PROPOSAL_REQUEST_STATUS.NEW]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.UNDER_REVIEW,
    CRM_PROPOSAL_REQUEST_STATUS.QUALIFIED,
    CRM_PROPOSAL_REQUEST_STATUS.REJECTED,
    CRM_PROPOSAL_REQUEST_STATUS.DUPLICATE,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.UNDER_REVIEW]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.INFORMATION_REQUIRED,
    CRM_PROPOSAL_REQUEST_STATUS.QUALIFIED,
    CRM_PROPOSAL_REQUEST_STATUS.REJECTED,
    CRM_PROPOSAL_REQUEST_STATUS.DUPLICATE,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.INFORMATION_REQUIRED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.UNDER_REVIEW,
    CRM_PROPOSAL_REQUEST_STATUS.QUALIFIED,
    CRM_PROPOSAL_REQUEST_STATUS.REJECTED,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.QUALIFIED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.PENDING_APPROVAL,
    CRM_PROPOSAL_REQUEST_STATUS.APPROVED,
    CRM_PROPOSAL_REQUEST_STATUS.CONVERTED,
    CRM_PROPOSAL_REQUEST_STATUS.REJECTED,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.PENDING_APPROVAL]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.APPROVED,
    CRM_PROPOSAL_REQUEST_STATUS.REJECTED,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.APPROVED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.CONVERTED,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.REJECTED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.DUPLICATE]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.CONVERTED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.CUSTOMER_DEFERRED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.UNDER_REVIEW,
    CRM_PROPOSAL_REQUEST_STATUS.CANCELLED,
    CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.CANCELLED]: Object.freeze([
    CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED,
  ]),
  [CRM_PROPOSAL_REQUEST_STATUS.ARCHIVED]: Object.freeze([]),
});

/** Document version statuses — APPROVED ≠ ISSUED. */
export const CRM_COMMERCIAL_DOCUMENT_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PRICING_IN_PROGRESS: 'PRICING_IN_PROGRESS',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_REVIEW: 'INTERNAL_REVIEW',
  CHANGES_REQUIRED: 'CHANGES_REQUIRED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  READY_TO_ISSUE: 'READY_TO_ISSUE',
  ISSUED: 'ISSUED',
  DELIVERED: 'DELIVERED',
  VIEWED: 'VIEWED',
  CUSTOMER_REVIEW: 'CUSTOMER_REVIEW',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CUSTOMER_DEFERRED: 'CUSTOMER_DEFERRED',
  EXPIRED: 'EXPIRED',
  WITHDRAWN: 'WITHDRAWN',
  SUPERSEDED: 'SUPERSEDED',
  CANCELLED: 'CANCELLED',
  ARCHIVED: 'ARCHIVED',
});

export const CRM_COMMERCIAL_DOCUMENT_STATUSES = Object.freeze(
  Object.values(CRM_COMMERCIAL_DOCUMENT_STATUS)
);

export const CRM_COMMERCIAL_DOCUMENT_TRANSITION_TABLE = Object.freeze({
  [CRM_COMMERCIAL_DOCUMENT_STATUS.DRAFT]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.PRICING_IN_PROGRESS,
    CRM_COMMERCIAL_DOCUMENT_STATUS.INTERNAL_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CHANGES_REQUIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.PRICING_IN_PROGRESS]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.DRAFT,
    CRM_COMMERCIAL_DOCUMENT_STATUS.INTERNAL_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.VALIDATION_FAILED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.VALIDATION_FAILED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.DRAFT,
    CRM_COMMERCIAL_DOCUMENT_STATUS.PRICING_IN_PROGRESS,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.INTERNAL_REVIEW]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.CHANGES_REQUIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.PENDING_APPROVAL,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.CHANGES_REQUIRED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.DRAFT,
    CRM_COMMERCIAL_DOCUMENT_STATUS.INTERNAL_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.PENDING_APPROVAL]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.APPROVED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CHANGES_REQUIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.APPROVED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.READY_TO_ISSUE,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CHANGES_REQUIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.READY_TO_ISSUE]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ISSUED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.ISSUED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.DELIVERED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.VIEWED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.DELIVERED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.VIEWED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.VIEWED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW,
    CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED,
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.CANCELLED]: Object.freeze([
    CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED,
  ]),
  [CRM_COMMERCIAL_DOCUMENT_STATUS.ARCHIVED]: Object.freeze([]),
});

export const CRM_COMMERCIAL_DOCUMENT_FAMILY = Object.freeze({
  PROPOSAL: 'PROPOSAL',
  QUOTATION: 'QUOTATION',
});

export const CRM_COMMERCIAL_DOCUMENT_FAMILIES = Object.freeze(
  Object.values(CRM_COMMERCIAL_DOCUMENT_FAMILY)
);

export const CRM_REQUESTED_DOCUMENT_TYPE = Object.freeze({
  PROPOSAL: 'PROPOSAL',
  QUOTATION: 'QUOTATION',
  BOTH: 'BOTH',
});

export const CRM_PROPOSAL_REQUEST_SOURCE = Object.freeze({
  DEMO_HANDOFF: 'DEMO_HANDOFF',
  OPPORTUNITY: 'OPPORTUNITY',
  OPPORTUNITY_READINESS: 'OPPORTUNITY_READINESS',
  SALES: 'SALES',
  CS: 'CS',
  PARTNER: 'PARTNER',
  MANUAL: 'MANUAL',
});

const DOC_STATUS_SET = new Set(CRM_COMMERCIAL_DOCUMENT_STATUSES);
const REQ_STATUS_SET = new Set(CRM_PROPOSAL_REQUEST_STATUSES);

export function isValidCommercialDocumentStatus(status) {
  return DOC_STATUS_SET.has(String(status || '').trim().toUpperCase());
}

export function isValidProposalRequestStatus(status) {
  return REQ_STATUS_SET.has(String(status || '').trim().toUpperCase());
}

export function canTransitionCommercialDocumentStatus(from, to) {
  const f = String(from || '').trim().toUpperCase();
  const t = String(to || '').trim().toUpperCase();
  if (!DOC_STATUS_SET.has(t)) return false;
  const allowed = CRM_COMMERCIAL_DOCUMENT_TRANSITION_TABLE[f];
  return Array.isArray(allowed) && allowed.includes(t);
}

export function canTransitionProposalRequestStatus(from, to) {
  const f = String(from || '').trim().toUpperCase();
  const t = String(to || '').trim().toUpperCase();
  if (!REQ_STATUS_SET.has(t)) return false;
  const allowed = CRM_PROPOSAL_REQUEST_TRANSITION_TABLE[f];
  return Array.isArray(allowed) && allowed.includes(t);
}

export function isIssuedOrBeyond(status) {
  const s = String(status || '').trim().toUpperCase();
  return (
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.ISSUED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.DELIVERED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.VIEWED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_REVIEW ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.REVISION_REQUESTED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.ACCEPTED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.REJECTED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.CUSTOMER_DEFERRED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.EXPIRED ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.WITHDRAWN ||
    s === CRM_COMMERCIAL_DOCUMENT_STATUS.SUPERSEDED
  );
}

export const CRM_PRICE_BOOK_TYPE = Object.freeze({
  STANDARD: 'STANDARD',
  ENTERPRISE: 'ENTERPRISE',
  PARTNER: 'PARTNER',
  GOVERNMENT: 'GOVERNMENT',
  PROMOTIONAL: 'PROMOTIONAL',
  LEGACY: 'LEGACY',
  CUSTOMER_SPECIFIC: 'CUSTOMER_SPECIFIC',
});

export const CRM_PRICE_BOOK_VERSION_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  ACTIVE: 'ACTIVE',
  RETIRED: 'RETIRED',
  REJECTED: 'REJECTED',
});

export const CRM_FX_RELIABILITY = Object.freeze({
  OK: 'OK',
  FX_CONTEXT_MISSING: 'FX_CONTEXT_MISSING',
  STALE: 'STALE',
});

export const CRM_DISCOUNT_REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
});

export const CRM_APPROVAL_REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  INVALIDATED: 'INVALIDATED',
  CANCELLED: 'CANCELLED',
});

export const CRM_APPROVAL_STEP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SKIPPED: 'SKIPPED',
});

export const CRM_DEFAULT_SALESPERSON_DISCOUNT_MAX_PERCENT = 10;

export function getCommercialDomainContract() {
  return Object.freeze({
    tenantQuotationDomain: 'WRONG_DOMAIN',
    proposalEqualsQuotation: false,
    approvedEqualsIssued: false,
    issuedEqualsAccepted: false,
    acceptedEqualsClosedWon: false,
    quotedEqualsRevenue: false,
    autoOpportunityStageMutationForbidden: true,
    autoOpportunityProbabilityMutationForbidden: true,
    autoOpportunityCloseDateMutationForbidden: true,
    inventPriceBookForbidden: false,
    inventPdfForbidden: true,
    inventAcceptanceForbidden: true,
    inventCustomerTenantSubscriptionForbidden: true,
    opportunityEstimatesNonBinding: true,
    tenantTaxPostingForbidden: true,
    mraEisFiscalFromQuotationForbidden: true,
    silentFxForbidden: true,
    eSignProvider: 'NOT_CONFIGURED',
    deliveryEqualsView: false,
    viewEqualsAcceptance: false,
    wave: 3,
  });
}
