export const SECURITY_PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: 'securityGovernance.viewDashboard',
  VIEW_USERS: 'securityGovernance.viewUsers',
  MANAGE_USERS: 'securityGovernance.manageUsers',
  VIEW_ROLES: 'securityGovernance.viewRoles',
  MANAGE_ROLES: 'securityGovernance.manageRoles',
  ASSIGN_SENSITIVE_PERMISSION: 'securityGovernance.assignSensitivePermission',
  VIEW_APPROVALS: 'securityGovernance.viewApprovals',
  MANAGE_APPROVAL_POLICIES: 'securityGovernance.manageApprovalPolicies',
  DECIDE_APPROVAL: 'securityGovernance.decideApproval',
  VIEW_SOD: 'securityGovernance.viewSod',
  MANAGE_SOD: 'securityGovernance.manageSod',
  VIEW_AUDIT: 'securityGovernance.viewAudit',
  EXPORT_AUDIT: 'securityGovernance.exportAudit',
  VIEW_ALERTS: 'securityGovernance.viewAlerts',
  MANAGE_INCIDENTS: 'securityGovernance.manageIncidents',
  MANAGE_SESSIONS: 'securityGovernance.manageSessions',
  MANAGE_API_KEYS: 'securityGovernance.manageApiKeys',
  MANAGE_SERVICE_ACCOUNTS: 'securityGovernance.manageServiceAccounts',
  IMPERSONATE: 'securityGovernance.impersonate',
  EMERGENCY_ACCESS: 'securityGovernance.emergencyAccess',
  MANAGE_DELEGATIONS: 'securityGovernance.manageDelegations',
  VIEW_EXPORT_HISTORY: 'securityGovernance.viewExportHistory',
  MANAGE_CONFIGURATION: 'securityGovernance.manageConfiguration',
});
