export const PLANNING_PERMISSIONS = Object.freeze({
  VIEW: 'financialPlanning.view',
  VIEW_DASHBOARD: 'financialPlanning.viewDashboard',
  MANAGE_CONFIGURATION: 'financialPlanning.manageConfiguration',
  VIEW_BUDGETS: 'financialPlanning.viewBudgets',
  CREATE_BUDGET: 'financialPlanning.createBudget',
  EDIT_DRAFT_BUDGET: 'financialPlanning.editDraftBudget',
  APPROVE_BUDGET: 'financialPlanning.approveBudget',
  VIEW_FORECASTS: 'financialPlanning.viewForecasts',
  CREATE_FORECAST: 'financialPlanning.createForecast',
  RECALCULATE_FORECAST: 'financialPlanning.recalculateForecast',
  MANAGE_SCENARIOS: 'financialPlanning.manageScenarios',
  MANAGE_ASSUMPTIONS: 'financialPlanning.manageAssumptions',
  APPROVE_ASSUMPTIONS: 'financialPlanning.approveAssumptions',
  CREATE_OVERRIDES: 'financialPlanning.createOverrides',
  APPROVE_OVERRIDES: 'financialPlanning.approveOverrides',
  RUN_AI: 'financialPlanning.runAISuggestions',
  REVIEW_AI: 'financialPlanning.reviewAISuggestions',
  REVIEW_FORECAST: 'financialPlanning.reviewForecast',
  APPROVE_FORECAST: 'financialPlanning.approveForecast',
  SNAPSHOT_FORECAST: 'financialPlanning.snapshotForecast',
  EXPORT: 'financialPlanning.export',
  VIEW_AUDIT: 'financialPlanning.viewAudit',
  MANAGE_IMPORTS: 'financialPlanning.manageImports',
});
