/**
 * Phase 7 — report exports (§56–58).
 *
 * Every export consumes a COMPLETED report envelope from the canonical
 * engine — no export recalculates anything, so screen, CSV, Excel and PDF
 * totals are identical by construction (REP-026). Excel uses numeric cells;
 * text cells are protected against spreadsheet formula injection.
 */

const CSV_INJECTION = /^[=+\-@\t\r]/;

/** Neutralize spreadsheet formula injection in text cells. */
export function sanitizeCell(value) {
  const text = String(value ?? '');
  return CSV_INJECTION.test(text) ? `'${text}` : text;
}

const csvEscape = (value) => {
  const text = sanitizeCell(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
};

function headerRows(envelope) {
  return [
    ['Report', envelope.reportName],
    ['Business', envelope.businessId],
    ['Period', `${envelope.dateRange?.fromDate ?? ''} — ${envelope.dateRange?.toDate ?? envelope.asOfDate ?? ''}`],
    ['Currency', envelope.currency],
    ['Definition version', envelope.definitionVersion ?? ''],
    ['Integrity status', envelope.integrityStatus],
    ['Generated at', envelope.generatedAt],
    ['Generated by', envelope.generatedBy],
    ...(envelope.integrityWarnings?.length
      ? [['Warnings', `${envelope.integrityWarnings.length} integrity warning(s) — see integrity sheet/section`]]
      : []),
    ...(envelope.unresolvedExceptions?.length
      ? [['Unresolved exceptions', `${envelope.unresolvedExceptions.length} open historical exception(s) disclosed`]]
      : []),
  ];
}

function lineRows(envelope) {
  if (envelope.reportType === 'TRIAL_BALANCE') {
    return {
      columns: ['Code', 'Account', 'Opening Dr', 'Opening Cr', 'Period Dr', 'Period Cr', 'Closing Dr', 'Closing Cr', 'Warning'],
      rows: envelope.lines.map((r) => [
        r.accountCode ?? '',
        r.accountName ?? '',
        r.openingDebit.decimal,
        r.openingCredit.decimal,
        r.periodDebit.decimal,
        r.periodCredit.decimal,
        r.closingDebit.decimal,
        r.closingCredit.decimal,
        r.warningStatus ?? '',
      ]),
      totals: [
        ['TOTALS', '', envelope.totals.openingDebit.decimal, envelope.totals.openingCredit.decimal,
          envelope.totals.periodDebit.decimal, envelope.totals.periodCredit.decimal,
          envelope.totals.closingDebit.decimal, envelope.totals.closingCredit.decimal,
          `Difference ${envelope.totals.difference.decimal}`],
      ],
    };
  }
  return {
    columns: ['Line', 'Label', 'Account codes', 'Amount', 'Comparative', 'Variance', 'Warning'],
    rows: envelope.lines.map((l) => [
      l.lineId,
      l.label,
      (l.accountCodes ?? []).join(' '),
      l.currentAmount?.decimal ?? '',
      l.comparativeAmount?.decimal ?? '',
      l.varianceAmount?.decimal ?? '',
      l.warningStatus ?? '',
    ]),
    totals: Object.entries(envelope.totals ?? {})
      .filter(([, v]) => v && typeof v === 'object' && 'decimal' in v)
      .map(([k, v]) => ['TOTAL', k, '', v.decimal, '', '', '']),
  };
}

/** CSV export — normalized rows, injection-safe, totals from the envelope. */
export function exportReportToCsv(envelope) {
  const { columns, rows, totals } = lineRows(envelope);
  const out = [];
  for (const h of headerRows(envelope)) out.push(h.map(csvEscape).join(','));
  out.push('');
  out.push(columns.map(csvEscape).join(','));
  for (const row of rows) out.push(row.map(csvEscape).join(','));
  for (const row of totals) out.push(row.map(csvEscape).join(','));
  return out.join('\r\n');
}

/** Excel export — numeric amount cells, integrity sheet, injection-safe text. */
export async function exportReportToExcel(envelope) {
  const { default: ExcelJS } = await import('exceljs');
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'InsightBooks Financial Reporting Engine';

  const summary = workbook.addWorksheet('Summary');
  for (const [k, v] of headerRows(envelope)) {
    summary.addRow([sanitizeCell(k), sanitizeCell(v)]);
  }

  const sheet = workbook.addWorksheet('Report');
  const { columns, rows, totals } = lineRows(envelope);
  sheet.addRow(columns).font = { bold: true };
  const numericColumns = new Set(
    columns.map((c, i) => (/(amount|dr|cr|comparative|variance|opening|period|closing)/i.test(c) ? i : -1)).filter((i) => i >= 0)
  );
  for (const row of rows) {
    sheet.addRow(row.map((cell, i) => (numericColumns.has(i) && cell !== '' ? Number(cell) : sanitizeCell(cell))));
  }
  for (const row of totals) {
    const r = sheet.addRow(row.map((cell, i) => (numericColumns.has(i) && cell !== '' && !Number.isNaN(Number(cell)) ? Number(cell) : sanitizeCell(cell))));
    r.font = { bold: true };
  }

  const accounts = workbook.addWorksheet('Account breakdown');
  accounts.addRow(['Line', 'Account code', 'Account name', 'Amount']).font = { bold: true };
  for (const l of envelope.lines ?? []) {
    for (const a of l.accounts ?? []) {
      accounts.addRow([sanitizeCell(l.label), sanitizeCell(a.accountCode ?? ''), sanitizeCell(a.accountName ?? ''), Number(a.amount?.decimal ?? 0)]);
    }
  }

  const integrity = workbook.addWorksheet('Integrity');
  integrity.addRow(['Status', envelope.integrityStatus]).font = { bold: true };
  for (const w of envelope.integrityWarnings ?? []) {
    integrity.addRow([sanitizeCell(w.code ?? ''), sanitizeCell(w.message ?? '')]);
  }
  for (const e of envelope.unresolvedExceptions ?? []) {
    integrity.addRow([sanitizeCell(e.findingCode ?? e.anomalyType ?? ''), sanitizeCell(`Open historical exception (${e.severity ?? ''})`)]);
  }

  return workbook.xlsx.writeBuffer();
}

/** PDF export — renders the completed envelope; performs no calculation. */
export async function exportReportToPdf(envelope, { companyName = 'InsightBooks' } = {}) {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');
  const doc = new jsPDF({ orientation: 'landscape' });

  doc.setFontSize(14);
  doc.text(String(companyName), 14, 14);
  doc.setFontSize(12);
  doc.text(envelope.reportName, 14, 21);
  doc.setFontSize(9);
  let y = 27;
  for (const [k, v] of headerRows(envelope)) {
    doc.text(`${k}: ${v}`, 14, y);
    y += 4.5;
  }

  const { columns, rows, totals } = lineRows(envelope);
  autoTable(doc, {
    startY: y + 2,
    head: [columns],
    body: [...rows, ...totals].map((r) => r.map((c) => String(c ?? ''))),
    styles: { fontSize: 7 },
    headStyles: { fillColor: [30, 64, 124] },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.text(
      `Generated ${envelope.generatedAt} — integrity ${envelope.integrityStatus} — page ${i}/${pageCount}`,
      14,
      doc.internal.pageSize.getHeight() - 6
    );
  }
  return Buffer.from(doc.output('arraybuffer'));
}
