/**
 * Phase 7 — report-type → permission mapping used by every report API route.
 * Server-side authorization only; menu visibility is never relied upon.
 */

import { ACCOUNTING_PERMISSIONS as P } from '../permissions.js';

export const REPORT_TYPE_PERMISSIONS = Object.freeze({
  TRIAL_BALANCE: [P.REPORTS_VIEW_TRIAL_BALANCE, P.REPORTS_VIEW, P.TRIAL_BALANCE_VIEW],
  INCOME_STATEMENT: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  BALANCE_SHEET: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  CASH_FLOW: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  EQUITY_STATEMENT: [P.REPORTS_VIEW_EQUITY, P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  RECEIVABLES: [P.REPORTS_VIEW_RECEIVABLES, P.REPORTS_VIEW, P.RECEIVABLES_VIEW],
  PAYABLES: [P.REPORTS_VIEW_PAYABLES, P.REPORTS_VIEW, P.PAYABLES_VIEW],
  INVENTORY: [P.REPORTS_VIEW_INVENTORY, P.REPORTS_VIEW],
  FIXED_ASSETS: [P.REPORTS_VIEW_ASSETS, P.REPORTS_VIEW],
  PAYROLL: [P.REPORTS_VIEW_PAYROLL], // sensitive: never granted via generic reports.view
  LOANS: [P.REPORTS_VIEW_LOANS, P.REPORTS_VIEW],
  TAXES: [P.REPORTS_VIEW_TAX, P.REPORTS_VIEW],
  EQUITY: [P.REPORTS_VIEW_EQUITY, P.CAPITAL_VIEW], // sensitive: capital/equity restricted
  BUDGET_VS_ACTUAL: [P.REPORTS_VIEW, P.REPORTS_VIEW_STATEMENTS],
  PROFIT_ANALYSIS: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  SALES: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  EXPENSES: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
  STOCK_MOVEMENTS: [P.REPORTS_VIEW_INVENTORY, P.REPORTS_VIEW],
  INVENTORY_LOSS: [P.REPORTS_VIEW_INVENTORY, P.REPORTS_VIEW],
  DAILY_POS: [P.REPORTS_VIEW_STATEMENTS, P.REPORTS_VIEW],
});

export function permissionsForReportType(reportType) {
  return REPORT_TYPE_PERMISSIONS[reportType] ?? [P.REPORTS_VIEW];
}
