/**
 * Client-safe report type constants (no Node built-ins).
 * Server contracts that need crypto live in reportContracts.js.
 */

export const REPORT_TYPES = Object.freeze({
  TRIAL_BALANCE: 'TRIAL_BALANCE',
  INCOME_STATEMENT: 'INCOME_STATEMENT',
  BALANCE_SHEET: 'BALANCE_SHEET',
  CASH_FLOW: 'CASH_FLOW',
  EQUITY_STATEMENT: 'EQUITY_STATEMENT',
  RECEIVABLES: 'RECEIVABLES',
  PAYABLES: 'PAYABLES',
  INVENTORY: 'INVENTORY',
  FIXED_ASSETS: 'FIXED_ASSETS',
  PAYROLL: 'PAYROLL',
  LOANS: 'LOANS',
  TAXES: 'TAXES',
  EQUITY: 'EQUITY',
  BUDGET_VS_ACTUAL: 'BUDGET_VS_ACTUAL',
  GENERAL_LEDGER: 'GENERAL_LEDGER',
  PROFIT_ANALYSIS: 'PROFIT_ANALYSIS',
  SALES: 'SALES',
  EXPENSES: 'EXPENSES',
  STOCK_MOVEMENTS: 'STOCK_MOVEMENTS',
  INVENTORY_LOSS: 'INVENTORY_LOSS',
  DAILY_POS: 'DAILY_POS',
});
