/** Phase 12 — closing domain enumerations. */

export const CloseMethod = Object.freeze({
  DIRECT_TO_RETAINED_EARNINGS: 'DIRECT_TO_RETAINED_EARNINGS',
  INCOME_SUMMARY_TO_RETAINED_EARNINGS: 'INCOME_SUMMARY_TO_RETAINED_EARNINGS',
  OWNER_CAPITAL_CLOSE: 'OWNER_CAPITAL_CLOSE',
  PARTNER_CAPITAL_ALLOCATION: 'PARTNER_CAPITAL_ALLOCATION',
  FUND_BALANCE_CLOSE: 'FUND_BALANCE_CLOSE',
  OTHER_APPROVED_METHOD: 'OTHER_APPROVED_METHOD',
});

export const CloseType = Object.freeze({
  PERIOD_END_CLOSE: 'PERIOD_END_CLOSE',
  YEAR_END_CLOSE: 'YEAR_END_CLOSE',
});

export const YearEndCloseRunStatus = Object.freeze({
  DRAFT: 'DRAFT',
  PREPARING: 'PREPARING',
  VALIDATING: 'VALIDATING',
  BLOCKED: 'BLOCKED',
  ADJUSTMENTS_IN_PROGRESS: 'ADJUSTMENTS_IN_PROGRESS',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  APPROVED_FOR_CLOSING: 'APPROVED_FOR_CLOSING',
  CLOSING: 'CLOSING',
  COMPLETED: 'COMPLETED',
  REOPEN_REQUESTED: 'REOPEN_REQUESTED',
  REOPENED: 'REOPENED',
  RECLOSING: 'RECLOSING',
  SUPERSEDED: 'SUPERSEDED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
});

export const CloseStatusAction = Object.freeze({
  CREATE_CLOSE_RUN: 'CREATE_CLOSE_RUN',
  BEGIN_PREPARATION: 'BEGIN_PREPARATION',
  BEGIN_VALIDATION: 'BEGIN_VALIDATION',
  BLOCK: 'BLOCK',
  UNBLOCK: 'UNBLOCK',
  BEGIN_ADJUSTMENTS: 'BEGIN_ADJUSTMENTS',
  SUBMIT_FOR_REVIEW: 'SUBMIT_FOR_REVIEW',
  APPROVE_CLOSING: 'APPROVE_CLOSING',
  BEGIN_CLOSING: 'BEGIN_CLOSING',
  COMPLETE_CLOSE: 'COMPLETE_CLOSE',
  REQUEST_REOPEN: 'REQUEST_REOPEN',
  APPROVE_REOPEN: 'APPROVE_REOPEN',
  REOPEN: 'REOPEN',
  BEGIN_RECLOSE: 'BEGIN_RECLOSE',
  COMPLETE_RECLOSE: 'COMPLETE_RECLOSE',
  CANCEL: 'CANCEL',
  FAIL: 'FAIL',
});

export const CloseTaskStatus = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  PASSED: 'PASSED',
  PASSED_WITH_WARNING: 'PASSED_WITH_WARNING',
  FAILED: 'FAILED',
  BLOCKED: 'BLOCKED',
  WAIVED: 'WAIVED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

export const TASK_TERMINAL_OK = Object.freeze([
  CloseTaskStatus.PASSED,
  CloseTaskStatus.PASSED_WITH_WARNING,
  CloseTaskStatus.WAIVED,
  CloseTaskStatus.NOT_APPLICABLE,
]);

export const CloseExceptionStatus = Object.freeze({
  OPEN: 'OPEN',
  UNDER_REVIEW: 'UNDER_REVIEW',
  AWAITING_ADJUSTMENT: 'AWAITING_ADJUSTMENT',
  AWAITING_DOCUMENTS: 'AWAITING_DOCUMENTS',
  ACCEPTED_FOR_CLOSE: 'ACCEPTED_FOR_CLOSE',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
});

export const ClosingBatchStatus = Object.freeze({
  DRAFT: 'DRAFT',
  GENERATED: 'GENERATED',
  VALIDATING: 'VALIDATING',
  INVALID: 'INVALID',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  APPROVED: 'APPROVED',
  POSTING: 'POSTING',
  POSTED: 'POSTED',
  FAILED: 'FAILED',
  REVERSED: 'REVERSED',
  SUPERSEDED: 'SUPERSEDED',
  CANCELLED: 'CANCELLED',
});

export const ClosingLineRole = Object.freeze({
  CLOSE_REVENUE: 'CLOSE_REVENUE',
  CLOSE_OTHER_INCOME: 'CLOSE_OTHER_INCOME',
  CLOSE_COST_OF_SALES: 'CLOSE_COST_OF_SALES',
  CLOSE_EXPENSE: 'CLOSE_EXPENSE',
  CLOSE_OTHER_EXPENSE: 'CLOSE_OTHER_EXPENSE',
  CLOSE_TAX_EXPENSE: 'CLOSE_TAX_EXPENSE',
  INCOME_SUMMARY: 'INCOME_SUMMARY',
  PROFIT_TRANSFER: 'PROFIT_TRANSFER',
  LOSS_TRANSFER: 'LOSS_TRANSFER',
  CLOSE_DRAWINGS: 'CLOSE_DRAWINGS',
  PARTNER_ALLOCATION: 'PARTNER_ALLOCATION',
});

export const ReadinessStatus = Object.freeze({
  READY: 'READY',
  READY_WITH_WARNINGS: 'READY_WITH_WARNINGS',
  BLOCKED: 'BLOCKED',
  REQUIRES_ADJUSTMENTS: 'REQUIRES_ADJUSTMENTS',
  REQUIRES_RECONCILIATION: 'REQUIRES_RECONCILIATION',
  REQUIRES_CONFIGURATION: 'REQUIRES_CONFIGURATION',
  REQUIRES_APPROVAL: 'REQUIRES_APPROVAL',
  REQUIRES_EQUITY_REVIEW: 'REQUIRES_EQUITY_REVIEW',
  REQUIRES_NEXT_YEAR_SETUP: 'REQUIRES_NEXT_YEAR_SETUP',
});

/** Categories treated as temporary (Income Statement) for year-end closure. */
export const TEMPORARY_CATEGORIES = Object.freeze([
  'REVENUE',
  'COST_OF_SALES',
  'EXPENSE',
  'OTHER_INCOME',
  'OTHER_EXPENSE',
]);

/** Permanent Balance Sheet categories — must never be closed to zero. */
export const PERMANENT_CATEGORIES = Object.freeze(['ASSET', 'LIABILITY', 'EQUITY']);

export const DrawingsCloseMethod = Object.freeze({
  TO_OWNER_CAPITAL: 'TO_OWNER_CAPITAL',
  TO_PARTNER_CAPITAL: 'TO_PARTNER_CAPITAL',
  LEAVE_OPEN: 'LEAVE_OPEN',
});
