/**
 * Revenue Intelligence metric catalogue (Phase 6 Wave 1).
 * Classes aligned with REVENUE_METRIC_READINESS_MATRIX.md.
 */

export const REVENUE_CATALOGUE_VERSION = 'revenue-kpi-2026-07-28';

export const REVENUE_READINESS = Object.freeze({
  READY: 'READY',
  READY_WITH_LIMITATIONS: 'READY_WITH_LIMITATIONS',
  READY_WITH_RECONCILIATION: 'READY_WITH_RECONCILIATION',
  UNAVAILABLE: 'UNAVAILABLE',
  NOT_SUPPORTED: 'NOT_SUPPORTED',
  DEFER: 'DEFER',
  FORBIDDEN: 'FORBIDDEN',
});

export const REVENUE_KPI_CODES = Object.freeze({
  MRR_ESTIMATED_TOTAL: 'revenue.mrr.estimated_total',
  MRR_ESTIMATED_CORE: 'revenue.mrr.estimated_core',
  MRR_ESTIMATED_MRA_EIS: 'revenue.mrr.estimated_mra_eis',
  ARR_ESTIMATED: 'revenue.arr.estimated',
  MRR_CROSS_CURRENCY: 'revenue.mrr.cross_currency_total',
  ARPA: 'revenue.arpa',
  BRIDGE_OPENING: 'revenue.mrr.bridge.opening',
  BRIDGE_CLOSING: 'revenue.mrr.bridge.closing',
  BRIDGE_NEW: 'revenue.mrr.bridge.new',
  BRIDGE_EXPANSION: 'revenue.mrr.bridge.expansion',
  BRIDGE_CONTRACTION: 'revenue.mrr.bridge.contraction',
  BRIDGE_CHURNED: 'revenue.mrr.bridge.churned',
  BRIDGE_REACTIVATION: 'revenue.mrr.bridge.reactivation',
  BRIDGE_NET_NEW: 'revenue.mrr.bridge.net_new',
  PAYMENTS_PERIOD: 'revenue.payments.collected_period',
  TENANTS_ACTIVE_PAID: 'revenue.tenants.active_paid',
  SUBSCRIPTIONS_ACTIVE: 'revenue.subscriptions.active',
  // Wave 3 — billing / collections / AR / payments / credits / MRA EIS commercial
  BILLED_PERIOD: 'revenue.billing.billed_period',
  BILLED_INVOICE_COUNT: 'revenue.billing.invoice_count',
  COLLECTED_PERIOD: 'revenue.collections.collected_period',
  COLLECTED_PAYMENT_COUNT: 'revenue.collections.payment_count',
  OUTSTANDING_TOTAL: 'revenue.receivables.outstanding',
  AGEING_CURRENT: 'revenue.receivables.ageing.current',
  AGEING_D1_30: 'revenue.receivables.ageing.d1_30',
  AGEING_D31_60: 'revenue.receivables.ageing.d31_60',
  AGEING_D61_90: 'revenue.receivables.ageing.d61_90',
  AGEING_D90_PLUS: 'revenue.receivables.ageing.d90_plus',
  PAYMENT_SUCCESS_COUNT: 'revenue.payments.success_count',
  PAYMENT_FAILURE_COUNT: 'revenue.payments.failure_count',
  PAYMENT_SUCCESS_RATE: 'revenue.payments.success_rate',
  PAYMENT_FAILURE_RATE: 'revenue.payments.failure_rate',
  PAYMENT_RETRY_ANALYTICS: 'revenue.payments.retry_analytics',
  CREDITS_OPEN_COUNT: 'revenue.credits.open_count',
  CREDITS_OPEN_REMAINING: 'revenue.credits.open_remaining',
  CREDITS_ISSUED_PERIOD: 'revenue.credits.issued_period',
  REFUNDS_PERIOD: 'revenue.refunds.period',
  MRA_EIS_BILLED_PERIOD: 'revenue.mra_eis.billed_period',
  MRA_EIS_COLLECTED_PERIOD: 'revenue.mra_eis.collected_period',
  // Wave 4 — cohorts / concentration / forecast / segments
  COHORT_RETENTION_COUNT: 'revenue.cohorts.retention_count',
  COHORT_RETENTION_MRR: 'revenue.cohorts.retention_mrr',
  COHORT_MATRIX: 'revenue.cohorts.matrix',
  CONCENTRATION_HHI: 'revenue.concentration.hhi',
  CONCENTRATION_TOP10_SHARE: 'revenue.concentration.top10_share',
  CONCENTRATION_TOP_MRR: 'revenue.concentration.top_tenant_mrr',
  FORECAST_RENEWAL_EXPOSURE: 'revenue.forecast.renewal_exposure',
  FORECAST_SCENARIO_BASE: 'revenue.forecast.scenario.base',
  FORECAST_SCENARIO_CONSERVATIVE: 'revenue.forecast.scenario.conservative',
  FORECAST_SCENARIO_OPTIMISTIC: 'revenue.forecast.scenario.optimistic',
  SEGMENT_INDUSTRY: 'revenue.segments.industry',
  SEGMENT_REGION: 'revenue.segments.region',
  SEGMENT_ACQUISITION: 'revenue.segments.acquisition',
  SEGMENT_PLAN_SPLIT: 'revenue.segments.plan_split',
  CUSTOMERS_TOP_CONTRIBUTORS: 'revenue.customers.top_contributors',
});

export const REVENUE_KPI_DEFINITIONS = Object.freeze({
  [REVENUE_KPI_CODES.MRR_ESTIMATED_TOTAL]: {
    label: 'Estimated contracted MRR (total)',
    definition:
      'Approximate monthly recurring revenue from active paid AccountSubscription amounts normalized by plan period, per native currency. Not GAAP recognised revenue.',
    source: 'AccountSubscription via computeSaasBillingKpis / reconstruct',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.MRR_ESTIMATED_CORE]: {
    label: 'Estimated contracted MRR (CORE)',
    definition: 'Estimated MRR for InsightBooks CORE plans only (planCategory / plan code).',
    source: 'AccountSubscription + categoryForPlanCode',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.MRR_ESTIMATED_MRA_EIS]: {
    label: 'Estimated contracted MRR (MRA EIS)',
    definition:
      'Estimated MRR for MRA EIS commercial add-on plans. Not tenant fiscal EISInvoice revenue.',
    source: 'AccountSubscription + categoryForPlanCode',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.ARR_ESTIMATED]: {
    label: 'Estimated contracted ARR',
    definition: 'Estimated MRR × 12. Approximate; not a separate ARR engine.',
    source: 'Derived from revenue.mrr.estimated_total',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.MRR_CROSS_CURRENCY]: {
    label: 'Cross-currency MRR total',
    definition: 'Consolidated MRR across currencies using FX conversion.',
    source: 'Requires documented FX rate source (none certified)',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.ARPA]: {
    label: 'ARPA (estimated)',
    definition: 'Estimated MRR ÷ distinct active paid tenants in the currency bucket.',
    source: 'AccountSubscription',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.BRIDGE_OPENING]: {
    label: 'Opening estimated MRR',
    definition: 'Snapshot estimated MRR at period start (reconstruct-then-snapshot).',
    source: 'AnalyticsDailySnapshot mrr_estimated_total_<CCY>',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.BRIDGE_CLOSING]: {
    label: 'Closing estimated MRR',
    definition: 'Snapshot estimated MRR at period end (reconstruct-then-snapshot).',
    source: 'AnalyticsDailySnapshot mrr_estimated_total_<CCY>',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.BRIDGE_NEW]: {
    label: 'New MRR',
    definition: 'MRR from subscriptions present at close but absent at open.',
    source: 'MRR bridge classification',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.BRIDGE_EXPANSION]: {
    label: 'Expansion MRR',
    definition: 'Positive MRR delta for subscriptions present at open and close.',
    source: 'MRR bridge classification',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.BRIDGE_CONTRACTION]: {
    label: 'Contraction MRR',
    definition: 'Negative MRR delta (absolute) for subscriptions present at open and close.',
    source: 'MRR bridge classification',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.BRIDGE_CHURNED]: {
    label: 'Churned MRR',
    definition: 'MRR from subscriptions present at open but absent at close.',
    source: 'MRR bridge classification',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.BRIDGE_REACTIVATION]: {
    label: 'Reactivation MRR',
    definition: 'MRR returning after prior churn evidence. Requires churn history.',
    source: 'MRR bridge classification',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.BRIDGE_NET_NEW]: {
    label: 'Net new MRR',
    definition: 'Closing − opening estimated MRR when both snapshots are available.',
    source: 'MRR bridge',
    unit: 'money',
    readiness: REVENUE_READINESS.UNAVAILABLE,
  },
  [REVENUE_KPI_CODES.PAYMENTS_PERIOD]: {
    label: 'Payments collected (period)',
    definition: 'Sum of successful PlatformPayment amounts in the period (native currency when filtered).',
    source: 'PlatformPayment',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_RECONCILIATION,
  },
  [REVENUE_KPI_CODES.TENANTS_ACTIVE_PAID]: {
    label: 'Active paid tenants',
    definition: 'Distinct tenants with active paid commercial subscription in the currency bucket.',
    source: 'AccountSubscription',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.SUBSCRIPTIONS_ACTIVE]: {
    label: 'Active subscriptions',
    definition: 'Active paid AccountSubscription rows (may exceed distinct tenants; CORE+EIS coexist).',
    source: 'AccountSubscription',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.BILLED_PERIOD]: {
    label: 'Billed (period)',
    definition:
      'Sum of PlatformInvoice.total issued in the period, excluding void/cancelled. Sparse vs PayChangu path.',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.BILLED_INVOICE_COUNT]: {
    label: 'Invoices billed (period)',
    definition: 'Count of non-void/cancelled PlatformInvoice rows created in the period.',
    source: 'PlatformInvoice',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.COLLECTED_PERIOD]: {
    label: 'Collected (period)',
    definition:
      'Sum of successful PlatformPayment amounts in the period (COMPLETED/SUCCESSFUL/FULLY_ALLOCATED).',
    source: 'PlatformPayment',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_RECONCILIATION,
  },
  [REVENUE_KPI_CODES.COLLECTED_PAYMENT_COUNT]: {
    label: 'Successful payments (period)',
    definition: 'Count of successful PlatformPayment rows in the period.',
    source: 'PlatformPayment',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_RECONCILIATION,
  },
  [REVENUE_KPI_CODES.OUTSTANDING_TOTAL]: {
    label: 'Outstanding receivables',
    definition: 'Sum of PlatformInvoice.outstanding for open (non-void/cancelled) invoices as-of now.',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.AGEING_CURRENT]: {
    label: 'Ageing — current',
    definition:
      'Outstanding not yet past due. Due reference: periodEnd, else createdAt (PlatformInvoice has no dueDate).',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.AGEING_D1_30]: {
    label: 'Ageing — 1–30 days',
    definition: 'Outstanding 1–30 days past due (periodEnd → createdAt fallback).',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.AGEING_D31_60]: {
    label: 'Ageing — 31–60 days',
    definition: 'Outstanding 31–60 days past due (periodEnd → createdAt fallback).',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.AGEING_D61_90]: {
    label: 'Ageing — 61–90 days',
    definition: 'Outstanding 61–90 days past due (periodEnd → createdAt fallback).',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.AGEING_D90_PLUS]: {
    label: 'Ageing — 90+ days',
    definition: 'Outstanding more than 90 days past due (periodEnd → createdAt fallback).',
    source: 'PlatformInvoice',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.PAYMENT_SUCCESS_COUNT]: {
    label: 'Payment successes (period)',
    definition: 'Count of PlatformPayment with successful status in the period.',
    source: 'PlatformPayment',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.PAYMENT_FAILURE_COUNT]: {
    label: 'Payment failures (period)',
    definition: 'Count of PlatformPayment with failed/declined status in the period.',
    source: 'PlatformPayment',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.PAYMENT_SUCCESS_RATE]: {
    label: 'Payment success rate',
    definition: 'success / (success + failure) when denominator > 0; else UNAVAILABLE.',
    source: 'PlatformPayment',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.PAYMENT_FAILURE_RATE]: {
    label: 'Payment failure rate',
    definition: 'failure / (success + failure) when denominator > 0; else UNAVAILABLE.',
    source: 'PlatformPayment',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.PAYMENT_RETRY_ANALYTICS]: {
    label: 'Payment retry analytics',
    definition: 'Retry attempts / recovery rates. No platform retry model.',
    source: 'none',
    unit: null,
    readiness: REVENUE_READINESS.NOT_SUPPORTED,
  },
  [REVENUE_KPI_CODES.CREDITS_OPEN_COUNT]: {
    label: 'Open credits',
    definition: 'Count of PlatformCredit with status OPEN and remaining > 0.',
    source: 'PlatformCredit',
    unit: 'count',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CREDITS_OPEN_REMAINING]: {
    label: 'Open credit remaining',
    definition: 'Sum of PlatformCredit.remaining for open credits in currency.',
    source: 'PlatformCredit',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CREDITS_ISSUED_PERIOD]: {
    label: 'Credits issued (period)',
    definition: 'Sum of PlatformCredit.amount created in the period.',
    source: 'PlatformCredit',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.REFUNDS_PERIOD]: {
    label: 'Refunds (period)',
    definition: 'Sum of completed PlatformRefund amounts in the period.',
    source: 'PlatformRefund',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.MRA_EIS_BILLED_PERIOD]: {
    label: 'MRA EIS billed (period)',
    definition:
      'PlatformInvoice totals attributable to MRA_EIS plans when subscription plan is known. Not fiscal EISInvoice.',
    source: 'PlatformInvoice + AccountSubscription + categoryForPlanCode',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.MRA_EIS_COLLECTED_PERIOD]: {
    label: 'MRA EIS collected (period)',
    definition:
      'Successful PlatformPayment totals attributable to MRA_EIS plans when invoice→subscription plan is known.',
    source: 'PlatformPayment + PlatformInvoice + AccountSubscription',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.COHORT_RETENTION_COUNT]: {
    label: 'Cohort retention (count)',
    definition:
      'Share of start-month cohort subscriptions still covering month N. Requires reconstruct confidence HIGH/MIXED over the window.',
    source: 'AccountSubscription + reconstructMrrHistory',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.COHORT_RETENTION_MRR]: {
    label: 'Cohort retention (contracted MRR)',
    definition:
      'Share of cohort contracted estimated MRR still active at month N. UNAVAILABLE when reconstruct window insufficient.',
    source: 'AccountSubscription + reconstructMrrHistory',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.COHORT_MATRIX]: {
    label: 'Subscription start-month cohorts',
    definition: 'Cohort matrix keyed by access-start month with retention by count and MRR.',
    source: 'AccountSubscription',
    unit: null,
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CONCENTRATION_HHI]: {
    label: 'MRR Herfindahl–Hirschman Index',
    definition: 'HHI of estimated contracted MRR shares across active paid tenants (0–1 scale).',
    source: 'AccountSubscription',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CONCENTRATION_TOP10_SHARE]: {
    label: 'Top-10 tenant MRR share',
    definition: 'Share of estimated contracted MRR held by the top 10 tenants in the currency bucket.',
    source: 'AccountSubscription',
    unit: 'ratio',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CONCENTRATION_TOP_MRR]: {
    label: 'Largest tenant estimated MRR',
    definition: 'Estimated contracted MRR of the single largest tenant contributor.',
    source: 'AccountSubscription',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.FORECAST_RENEWAL_EXPOSURE]: {
    label: 'Deterministic renewal exposure',
    definition:
      'Sum of estimated MRR for active paid subscriptions with expiresAt within the horizon. Not predictive revenue.',
    source: 'AccountSubscription expiresAt + normalizeAmountToMrr',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.FORECAST_SCENARIO_BASE]: {
    label: 'Renewal exposure — base (1.0×)',
    definition: 'Deterministic renewal exposure × 1.0. Documented multiplier scenario; not ML.',
    source: 'Derived from revenue.forecast.renewal_exposure',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.FORECAST_SCENARIO_CONSERVATIVE]: {
    label: 'Renewal exposure — conservative (0.9×)',
    definition: 'Deterministic renewal exposure × 0.9. Documented multiplier scenario; not ML.',
    source: 'Derived from revenue.forecast.renewal_exposure',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.FORECAST_SCENARIO_OPTIMISTIC]: {
    label: 'Renewal exposure — optimistic (1.1×)',
    definition: 'Deterministic renewal exposure × 1.1. Documented multiplier scenario; not ML.',
    source: 'Derived from revenue.forecast.renewal_exposure',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.SEGMENT_INDUSTRY]: {
    label: 'Revenue by industry',
    definition: 'Industry dimension not instrumented on platform billing tenants.',
    source: 'none',
    unit: null,
    readiness: REVENUE_READINESS.NOT_SUPPORTED,
  },
  [REVENUE_KPI_CODES.SEGMENT_REGION]: {
    label: 'Revenue by region',
    definition: 'Region dimension not instrumented on platform billing tenants.',
    source: 'none',
    unit: null,
    readiness: REVENUE_READINESS.NOT_SUPPORTED,
  },
  [REVENUE_KPI_CODES.SEGMENT_ACQUISITION]: {
    label: 'Revenue by acquisition channel',
    definition: 'Acquisition channel not instrumented on platform billing tenants.',
    source: 'none',
    unit: null,
    readiness: REVENUE_READINESS.NOT_SUPPORTED,
  },
  [REVENUE_KPI_CODES.SEGMENT_PLAN_SPLIT]: {
    label: 'Estimated MRR by plan',
    definition: 'Active paid estimated MRR grouped by plan code (verified dimension).',
    source: 'AccountSubscription',
    unit: 'money',
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
  [REVENUE_KPI_CODES.CUSTOMERS_TOP_CONTRIBUTORS]: {
    label: 'Top customer contributors',
    definition:
      'Top tenants by estimated contracted MRR. Labels masked without tenants.view.',
    source: 'AccountSubscription (+ Tenant name when permitted)',
    unit: null,
    readiness: REVENUE_READINESS.READY_WITH_LIMITATIONS,
  },
});

export function getRevenueDefinition(code) {
  return (
    REVENUE_KPI_DEFINITIONS[code] || {
      label: code,
      definition: null,
      source: null,
      unit: null,
      readiness: REVENUE_READINESS.UNAVAILABLE,
    }
  );
}
