/** Phase 4 — MRA EIS control-plane constants (no MRA network I/O). */

export const POLICY_VERSION = 'mra-eis-capability-v1';

export const PLATFORM_STATUS = Object.freeze({
  DISABLED: 'DISABLED',
  ENABLED: 'ENABLED',
  EMERGENCY_PAUSED: 'EMERGENCY_PAUSED',
  MAINTENANCE: 'MAINTENANCE',
  RETIRED: 'RETIRED',
});

export const ENTITLEMENT_STATUS = Object.freeze({
  NOT_ENTITLED: 'NOT_ENTITLED',
  ENTITLEMENT_PENDING: 'ENTITLEMENT_PENDING',
  ENTITLED_SANDBOX_ONLY: 'ENTITLED_SANDBOX_ONLY',
  ENTITLED_PRODUCTION: 'ENTITLED_PRODUCTION',
  SUSPENDED: 'SUSPENDED',
  REVOKED: 'REVOKED',
  EXPIRED: 'EXPIRED',
});

export const PARTICIPATION_STATUS = Object.freeze({
  NOT_STARTED: 'NOT_STARTED',
  OPTED_IN: 'OPTED_IN',
  PAUSED: 'PAUSED',
  OPTED_OUT: 'OPTED_OUT',
  DISABLING_AFTER_QUEUE: 'DISABLING_AFTER_QUEUE',
  SUSPENDED_BY_SYSTEM: 'SUSPENDED_BY_SYSTEM',
});

export const BUSINESS_OPS_STATUS = Object.freeze({
  UNAVAILABLE: 'UNAVAILABLE',
  AVAILABLE: 'AVAILABLE',
  SETUP_REQUIRED: 'SETUP_REQUIRED',
  SETUP_IN_PROGRESS: 'SETUP_IN_PROGRESS',
  READY_FOR_ACTIVATION: 'READY_FOR_ACTIVATION',
  OPERATIONALLY_ENABLED: 'OPERATIONALLY_ENABLED',
  PAUSED: 'PAUSED',
  DISABLING_AFTER_QUEUE: 'DISABLING_AFTER_QUEUE',
  DISABLED: 'DISABLED',
  DEGRADED: 'DEGRADED',
  BLOCKED_BY_DEPENDENCY: 'BLOCKED_BY_DEPENDENCY',
  SUSPENDED_BY_SYSTEM: 'SUSPENDED_BY_SYSTEM',
  ERROR: 'ERROR',
});

export const EIS_ENVIRONMENT = Object.freeze({
  MOCK: 'MOCK',
  DEVELOPMENT: 'DEVELOPMENT',
  SANDBOX: 'SANDBOX',
  CERTIFICATION: 'CERTIFICATION',
  STAGING: 'STAGING',
  PRODUCTION: 'PRODUCTION',
});

export const CERTIFICATION_STATUS = Object.freeze({
  NOT_REQUIRED_FOR_CURRENT_ACTION: 'NOT_REQUIRED_FOR_CURRENT_ACTION',
  NOT_STARTED: 'NOT_STARTED',
  DOCUMENTATION_REQUIRED: 'DOCUMENTATION_REQUIRED',
  SANDBOX_PENDING: 'SANDBOX_PENDING',
  SANDBOX_IN_PROGRESS: 'SANDBOX_IN_PROGRESS',
  SANDBOX_PASSED: 'SANDBOX_PASSED',
  CERTIFICATION_PENDING: 'CERTIFICATION_PENDING',
  CERTIFIED_ONLINE: 'CERTIFIED_ONLINE',
  CERTIFIED_OFFLINE: 'CERTIFIED_OFFLINE',
  PRODUCTION_APPROVED: 'PRODUCTION_APPROVED',
  EXPIRED: 'EXPIRED',
  SUSPENDED: 'SUSPENDED',
  REVOKED: 'REVOKED',
});

export const CERTIFICATION_TYPE = Object.freeze({
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  RECEIPT: 'RECEIPT',
  ENVIRONMENT: 'ENVIRONMENT',
  PRODUCT: 'PRODUCT',
});

export const ENTITLEMENT_SOURCE = Object.freeze({
  SYSTEM_ADMINISTRATOR: 'SYSTEM_ADMINISTRATOR',
  CONTRACT: 'CONTRACT',
  SUBSCRIPTION_PLAN: 'SUBSCRIPTION_PLAN',
  PILOT_PROGRAM: 'PILOT_PROGRAM',
  MIGRATION: 'MIGRATION',
  SUPPORT_OVERRIDE: 'SUPPORT_OVERRIDE',
  REGULATORY_REQUIREMENT: 'REGULATORY_REQUIREMENT',
});

export const PAUSE_MODE = Object.freeze({
  PAUSE_NEW_ONLY: 'PAUSE_NEW_ONLY',
  PAUSE_ALL_PROCESSING: 'PAUSE_ALL_PROCESSING',
  PAUSE_AFTER_CURRENT_ATTEMPT: 'PAUSE_AFTER_CURRENT_ATTEMPT',
  SYSTEM_EMERGENCY_PAUSE: 'SYSTEM_EMERGENCY_PAUSE',
});

export const DISABLE_MODE = Object.freeze({
  DISABLE_BEFORE_SETUP: 'DISABLE_BEFORE_SETUP',
  DISABLE_BEFORE_ACTIVATION: 'DISABLE_BEFORE_ACTIVATION',
  DISABLE_AFTER_QUEUE_DRAINS: 'DISABLE_AFTER_QUEUE_DRAINS',
  IMMEDIATE_ADMINISTRATIVE_SUSPENSION: 'IMMEDIATE_ADMINISTRATIVE_SUSPENSION',
  REVOKE_ENTITLEMENT: 'REVOKE_ENTITLEMENT',
});

export const OPERATION_MODE = Object.freeze({
  ONLINE_ONLY: 'ONLINE_ONLY',
  ONLINE_WITH_CERTIFIED_OFFLINE_FALLBACK: 'ONLINE_WITH_CERTIFIED_OFFLINE_FALLBACK',
  MANUAL_FISCALIZATION: 'MANUAL_FISCALIZATION',
});

export const RECEIPT_POLICY = Object.freeze({
  WAIT_FOR_MRA_ACCEPTANCE: 'WAIT_FOR_MRA_ACCEPTANCE',
  ISSUE_PENDING_RECEIPT: 'ISSUE_PENDING_RECEIPT',
  CERTIFIED_OFFLINE_RECEIPT: 'CERTIFIED_OFFLINE_RECEIPT',
});

/** Requested operations for evaluateMraEisCapability */
export const EIS_OPERATION = Object.freeze({
  VIEW_EIS: 'VIEW_EIS',
  START_SETUP: 'START_SETUP',
  MODIFY_SETTINGS: 'MODIFY_SETTINGS',
  ACTIVATE_TERMINAL: 'ACTIVATE_TERMINAL',
  SYNC_CONFIGURATION: 'SYNC_CONFIGURATION',
  MAP_PRODUCTS: 'MAP_PRODUCTS',
  MAP_TAXES: 'MAP_TAXES',
  ENABLE_OPERATION: 'ENABLE_OPERATION',
  CREATE_FISCAL_SNAPSHOT: 'CREATE_FISCAL_SNAPSHOT',
  TRANSMIT_SALE: 'TRANSMIT_SALE',
  USE_OFFLINE_MODE: 'USE_OFFLINE_MODE',
  VIEW_REPORTS: 'VIEW_REPORTS',
  EXPORT_REPORTS: 'EXPORT_REPORTS',
  PAUSE: 'PAUSE',
  DISABLE: 'DISABLE',
});

export const BLOCKER = Object.freeze({
  EIS_PLATFORM_DISABLED: 'EIS_PLATFORM_DISABLED',
  EIS_PLATFORM_EMERGENCY_PAUSED: 'EIS_PLATFORM_EMERGENCY_PAUSED',
  EIS_PLATFORM_MAINTENANCE: 'EIS_PLATFORM_MAINTENANCE',
  EIS_NEW_ENTITLEMENTS_DISABLED: 'EIS_NEW_ENTITLEMENTS_DISABLED',
  TENANT_NOT_ENTITLED: 'TENANT_NOT_ENTITLED',
  TENANT_ENTITLEMENT_PENDING: 'TENANT_ENTITLEMENT_PENDING',
  TENANT_ENTITLEMENT_SUSPENDED: 'TENANT_ENTITLEMENT_SUSPENDED',
  TENANT_ENTITLEMENT_REVOKED: 'TENANT_ENTITLEMENT_REVOKED',
  TENANT_ENTITLEMENT_EXPIRED: 'TENANT_ENTITLEMENT_EXPIRED',
  TENANT_NOT_PARTICIPATING: 'TENANT_NOT_PARTICIPATING',
  TENANT_OPERATION_PAUSED: 'TENANT_OPERATION_PAUSED',
  SANDBOX_NOT_AUTHORIZED: 'SANDBOX_NOT_AUTHORIZED',
  PRODUCTION_NOT_AUTHORIZED: 'PRODUCTION_NOT_AUTHORIZED',
  PRODUCTION_CERTIFICATION_REQUIRED: 'PRODUCTION_CERTIFICATION_REQUIRED',
  ENVIRONMENT_MISMATCH: 'ENVIRONMENT_MISMATCH',
  BUSINESS_SETTING_MISSING: 'BUSINESS_SETTING_MISSING',
  BUSINESS_SETUP_REQUIRED: 'BUSINESS_SETUP_REQUIRED',
  BUSINESS_OPERATION_DISABLED: 'BUSINESS_OPERATION_DISABLED',
  BUSINESS_OPERATION_PAUSED: 'BUSINESS_OPERATION_PAUSED',
  BUSINESS_SUSPENDED_BY_SYSTEM: 'BUSINESS_SUSPENDED_BY_SYSTEM',
  TERMINAL_REQUIRED: 'TERMINAL_REQUIRED',
  TERMINAL_NOT_ACTIVE: 'TERMINAL_NOT_ACTIVE',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
  CONFIGURATION_REQUIRED: 'CONFIGURATION_REQUIRED',
  CONFIGURATION_STALE: 'CONFIGURATION_STALE',
  SITE_MAPPING_REQUIRED: 'SITE_MAPPING_REQUIRED',
  PRODUCT_MAPPING_REQUIRED: 'PRODUCT_MAPPING_REQUIRED',
  TAX_MAPPING_REQUIRED: 'TAX_MAPPING_REQUIRED',
  PAYMENT_MAPPING_REQUIRED: 'PAYMENT_MAPPING_REQUIRED',
  OFFLINE_NOT_CERTIFIED: 'OFFLINE_NOT_CERTIFIED',
  FEATURE_FLAG_DISABLED: 'FEATURE_FLAG_DISABLED',
});

export const WARNING = Object.freeze({
  ENTITLEMENT_EXPIRING: 'ENTITLEMENT_EXPIRING',
  CERTIFICATION_EXPIRING: 'CERTIFICATION_EXPIRING',
  SETUP_INCOMPLETE: 'SETUP_INCOMPLETE',
  SANDBOX_ONLY: 'SANDBOX_ONLY',
  PRODUCTION_PENDING_APPROVAL: 'PRODUCTION_PENDING_APPROVAL',
  QUEUE_DRAIN_REQUIRED: 'QUEUE_DRAIN_REQUIRED',
  FEATURE_IN_PILOT: 'FEATURE_IN_PILOT',
  PLATFORM_MAINTENANCE_SCHEDULED: 'PLATFORM_MAINTENANCE_SCHEDULED',
  LEGACY_EIS_SETTING_PRESENT: 'LEGACY_EIS_SETTING_PRESENT',
  PHASE_DEPENDENCY_PENDING: 'PHASE_DEPENDENCY_PENDING',
});

export const EIS_FEATURE_FLAGS = Object.freeze({
  PLATFORM_ENABLED: 'mraEisPlatformEnabled',
  EMERGENCY_PAUSE: 'mraEisEmergencyPause',
  NEW_ENTITLEMENTS: 'mraEisNewEntitlementsEnabled',
  SANDBOX: 'mraEisSandboxEnabled',
  CERTIFICATION_ENV: 'mraEisCertificationEnvironmentEnabled',
  PRODUCTION: 'mraEisProductionEnabled',
  TENANT_OPT_IN: 'mraEisTenantOptInEnabled',
  BUSINESS_SETUP: 'mraEisBusinessSetupEnabled',
  TERMINAL_ACTIVATION: 'mraEisTerminalActivationEnabled',
  CONFIGURATION_SYNC: 'mraEisConfigurationSyncEnabled',
  PRODUCT_MAPPING: 'mraEisProductMappingEnabled',
  TAX_MAPPING: 'mraEisTaxMappingEnabled',
  POS_FISCALIZATION: 'mraEisPosFiscalizationEnabled',
  INVOICE_FISCALIZATION: 'mraEisInvoiceFiscalizationEnabled',
  ONLINE_TRANSMISSION: 'mraEisOnlineTransmissionEnabled',
  OFFLINE_MODE: 'mraEisOfflineModeEnabled',
  RECEIPT_QR: 'mraEisReceiptQrEnabled',
  RECONCILIATION: 'mraEisReconciliationEnabled',
});

/** Platform setting singleton id */
export const PLATFORM_SETTING_ID = 'global';

export const ACTIVE_ENTITLEMENT_STATUSES = new Set([
  ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY,
  ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
]);

export const HUMAN_LABELS = Object.freeze({
  entitlement: {
    [ENTITLEMENT_STATUS.NOT_ENTITLED]: 'Not entitled',
    [ENTITLEMENT_STATUS.ENTITLEMENT_PENDING]: 'Entitlement pending review',
    [ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY]: 'Sandbox entitlement granted',
    [ENTITLEMENT_STATUS.ENTITLED_PRODUCTION]: 'Production entitlement granted',
    [ENTITLEMENT_STATUS.SUSPENDED]: 'Entitlement suspended',
    [ENTITLEMENT_STATUS.REVOKED]: 'Entitlement revoked',
    [ENTITLEMENT_STATUS.EXPIRED]: 'Entitlement expired',
  },
  participation: {
    [PARTICIPATION_STATUS.NOT_STARTED]: 'Not started',
    [PARTICIPATION_STATUS.OPTED_IN]: 'Opted in',
    [PARTICIPATION_STATUS.PAUSED]: 'Paused',
    [PARTICIPATION_STATUS.OPTED_OUT]: 'Opted out',
    [PARTICIPATION_STATUS.DISABLING_AFTER_QUEUE]: 'Disabling after queue drains',
    [PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM]: 'Suspended by system',
  },
  businessOps: {
    [BUSINESS_OPS_STATUS.UNAVAILABLE]: 'Unavailable',
    [BUSINESS_OPS_STATUS.AVAILABLE]: 'Available',
    [BUSINESS_OPS_STATUS.SETUP_REQUIRED]: 'Setup required',
    [BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS]: 'Setup in progress',
    [BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION]: 'Ready for activation',
    [BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED]: 'Operationally enabled',
    [BUSINESS_OPS_STATUS.PAUSED]: 'Paused',
    [BUSINESS_OPS_STATUS.DISABLING_AFTER_QUEUE]: 'Disabling after queue drains',
    [BUSINESS_OPS_STATUS.DISABLED]: 'Disabled',
    [BUSINESS_OPS_STATUS.DEGRADED]: 'Degraded',
    [BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY]: 'Blocked by dependency',
    [BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM]: 'Suspended by system',
    [BUSINESS_OPS_STATUS.ERROR]: 'Error',
  },
});
