import {
  TERMINAL_STATUS,
  SNAPSHOT_STATUS,
  TRANSMISSION_STATUS,
  CONFIGURATION_STATUS,
  OFFLINE_QUEUE_STATUS,
} from './operationalEnums.js';
import { EisErrors } from './errors.js';

function freezeMap(obj) {
  return Object.freeze(
    Object.fromEntries(Object.entries(obj).map(([k, v]) => [k, new Set(v)]))
  );
}

export const TERMINAL_TRANSITIONS = freezeMap({
  [TERMINAL_STATUS.DRAFT]: [
    TERMINAL_STATUS.READINESS_INCOMPLETE,
    TERMINAL_STATUS.TAC_REQUIRED,
    TERMINAL_STATUS.ACTIVATION_REQUEST_PENDING,
    TERMINAL_STATUS.INACTIVE,
  ],
  [TERMINAL_STATUS.READINESS_INCOMPLETE]: [
    TERMINAL_STATUS.TAC_REQUIRED,
    TERMINAL_STATUS.DRAFT,
    TERMINAL_STATUS.INACTIVE,
  ],
  [TERMINAL_STATUS.TAC_REQUIRED]: [
    TERMINAL_STATUS.ACTIVATION_REQUEST_PENDING,
    TERMINAL_STATUS.ACTIVATION_FAILED,
    TERMINAL_STATUS.INACTIVE,
  ],
  [TERMINAL_STATUS.ACTIVATION_REQUEST_PENDING]: [
    TERMINAL_STATUS.ACTIVATION_IN_PROGRESS,
    TERMINAL_STATUS.ACTIVATION_FAILED,
  ],
  [TERMINAL_STATUS.ACTIVATION_IN_PROGRESS]: [
    TERMINAL_STATUS.ACTIVATION_RESPONSE_RECEIVED,
    TERMINAL_STATUS.ACTIVATION_FAILED,
    TERMINAL_STATUS.UNKNOWN_ACTIVATION_OUTCOME,
    TERMINAL_STATUS.MANUAL_REVIEW,
  ],
  [TERMINAL_STATUS.ACTIVATION_RESPONSE_RECEIVED]: [
    TERMINAL_STATUS.CREDENTIALS_PERSISTED,
    TERMINAL_STATUS.CREDENTIAL_STORAGE_FAILED,
    TERMINAL_STATUS.ACTIVATION_FAILED,
    TERMINAL_STATUS.MANUAL_REVIEW,
  ],
  [TERMINAL_STATUS.CREDENTIALS_PERSISTED]: [
    TERMINAL_STATUS.CONFIRMATION_PENDING,
    TERMINAL_STATUS.CONFIGURATION_BOOTSTRAP_FAILED,
    TERMINAL_STATUS.MANUAL_REVIEW,
  ],
  [TERMINAL_STATUS.CONFIRMATION_PENDING]: [
    TERMINAL_STATUS.CONFIRMATION_IN_PROGRESS,
    TERMINAL_STATUS.CONFIRMATION_FAILED,
    TERMINAL_STATUS.MANUAL_REVIEW,
  ],
  [TERMINAL_STATUS.CONFIRMATION_IN_PROGRESS]: [
    TERMINAL_STATUS.ACTIVE,
    TERMINAL_STATUS.CONFIRMATION_FAILED,
    TERMINAL_STATUS.UNKNOWN_CONFIRMATION_OUTCOME,
    TERMINAL_STATUS.MANUAL_REVIEW,
  ],
  [TERMINAL_STATUS.UNKNOWN_ACTIVATION_OUTCOME]: [
    TERMINAL_STATUS.MANUAL_REVIEW,
    TERMINAL_STATUS.ACTIVATION_FAILED,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.UNKNOWN_CONFIRMATION_OUTCOME]: [
    TERMINAL_STATUS.MANUAL_REVIEW,
    TERMINAL_STATUS.CONFIRMATION_PENDING,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.CREDENTIAL_STORAGE_FAILED]: [
    TERMINAL_STATUS.MANUAL_REVIEW,
    TERMINAL_STATUS.ACTIVATION_FAILED,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.CONFIGURATION_BOOTSTRAP_FAILED]: [
    TERMINAL_STATUS.MANUAL_REVIEW,
    TERMINAL_STATUS.CONFIRMATION_PENDING,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.MANUAL_REVIEW]: [
    TERMINAL_STATUS.TAC_REQUIRED,
    TERMINAL_STATUS.CONFIRMATION_PENDING,
    TERMINAL_STATUS.REVOKED,
    TERMINAL_STATUS.INACTIVE,
  ],
  [TERMINAL_STATUS.ACTIVE]: [
    TERMINAL_STATUS.CONFIGURATION_STALE,
    TERMINAL_STATUS.TOKEN_EXPIRED,
    TERMINAL_STATUS.REACTIVATION_REQUIRED,
    TERMINAL_STATUS.BLOCKED,
    TERMINAL_STATUS.INACTIVE,
    TERMINAL_STATUS.REVOKED,
    TERMINAL_STATUS.ERROR,
  ],
  [TERMINAL_STATUS.CONFIGURATION_STALE]: [
    TERMINAL_STATUS.ACTIVE,
    TERMINAL_STATUS.BLOCKED,
    TERMINAL_STATUS.ERROR,
  ],
  [TERMINAL_STATUS.TOKEN_EXPIRED]: [
    TERMINAL_STATUS.REACTIVATION_REQUIRED,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.REACTIVATION_REQUIRED]: [
    TERMINAL_STATUS.TAC_REQUIRED,
    TERMINAL_STATUS.ACTIVATION_REQUEST_PENDING,
    TERMINAL_STATUS.REVOKED,
  ],
  // Unblock workflow: BLOCKED → CONFIGURATION_STALE → ACTIVE (never direct ACTIVE)
  [TERMINAL_STATUS.BLOCKED]: [
    TERMINAL_STATUS.CONFIGURATION_STALE,
    TERMINAL_STATUS.REVOKED,
    TERMINAL_STATUS.ERROR,
  ],
  [TERMINAL_STATUS.ACTIVATION_FAILED]: [
    TERMINAL_STATUS.TAC_REQUIRED,
    TERMINAL_STATUS.DRAFT,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.CONFIRMATION_FAILED]: [
    TERMINAL_STATUS.CONFIRMATION_PENDING,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.INACTIVE]: [TERMINAL_STATUS.DRAFT, TERMINAL_STATUS.REVOKED],
  [TERMINAL_STATUS.ERROR]: [
    TERMINAL_STATUS.ACTIVE,
    TERMINAL_STATUS.BLOCKED,
    TERMINAL_STATUS.INACTIVE,
    TERMINAL_STATUS.REVOKED,
  ],
  [TERMINAL_STATUS.REVOKED]: [],
});

export const SNAPSHOT_TRANSITIONS = freezeMap({
  [SNAPSHOT_STATUS.REQUESTED]: [SNAPSHOT_STATUS.VALIDATING, SNAPSHOT_STATUS.CANCELLED_BEFORE_QUEUE, SNAPSHOT_STATUS.MANUAL_REVIEW],
  [SNAPSHOT_STATUS.VALIDATING]: [
    SNAPSHOT_STATUS.MAPPINGS_RESOLVED,
    SNAPSHOT_STATUS.FAILED,
    SNAPSHOT_STATUS.MANUAL_REVIEW,
    SNAPSHOT_STATUS.CANCELLED_BEFORE_QUEUE,
  ],
  [SNAPSHOT_STATUS.MAPPINGS_RESOLVED]: [
    SNAPSHOT_STATUS.NUMBER_RESERVED,
    SNAPSHOT_STATUS.FAILED,
    SNAPSHOT_STATUS.MANUAL_REVIEW,
  ],
  [SNAPSHOT_STATUS.NUMBER_RESERVED]: [
    SNAPSHOT_STATUS.CREATED,
    SNAPSHOT_STATUS.FAILED_WITH_NUMBER_EVIDENCE,
    SNAPSHOT_STATUS.MANUAL_REVIEW,
  ],
  [SNAPSHOT_STATUS.CREATED]: [SNAPSHOT_STATUS.QUEUED, SNAPSHOT_STATUS.SUPERSEDED, SNAPSHOT_STATUS.MANUAL_REVIEW],
  [SNAPSHOT_STATUS.QUEUED]: [],
  [SNAPSHOT_STATUS.FAILED]: [SNAPSHOT_STATUS.SUPERSEDED],
  [SNAPSHOT_STATUS.FAILED_WITH_NUMBER_EVIDENCE]: [SNAPSHOT_STATUS.MANUAL_REVIEW],
  [SNAPSHOT_STATUS.CANCELLED_BEFORE_QUEUE]: [],
  [SNAPSHOT_STATUS.MANUAL_REVIEW]: [SNAPSHOT_STATUS.SUPERSEDED],
  [SNAPSHOT_STATUS.SUPERSEDED]: [],
});

export const TRANSMISSION_TRANSITIONS = freezeMap({
  [TRANSMISSION_STATUS.CREATED]: [
    TRANSMISSION_STATUS.QUEUED,
    TRANSMISSION_STATUS.OFFLINE_SIGNED,
    TRANSMISSION_STATUS.CANCELLED_BEFORE_SUBMISSION,
    TRANSMISSION_STATUS.BLOCKED,
  ],
  [TRANSMISSION_STATUS.QUEUED]: [TRANSMISSION_STATUS.CLAIMED, TRANSMISSION_STATUS.BLOCKED, TRANSMISSION_STATUS.CANCELLED_BEFORE_SUBMISSION],
  [TRANSMISSION_STATUS.CLAIMED]: [TRANSMISSION_STATUS.VALIDATING, TRANSMISSION_STATUS.QUEUED],
  [TRANSMISSION_STATUS.VALIDATING]: [
    TRANSMISSION_STATUS.SENDING,
    TRANSMISSION_STATUS.REJECTED,
    TRANSMISSION_STATUS.MANUAL_REVIEW,
  ],
  [TRANSMISSION_STATUS.SENDING]: [
    TRANSMISSION_STATUS.SENT_AWAITING_RESULT,
    TRANSMISSION_STATUS.RETRY_SCHEDULED,
    TRANSMISSION_STATUS.UNKNOWN_OUTCOME,
  ],
  [TRANSMISSION_STATUS.SENT_AWAITING_RESULT]: [
    TRANSMISSION_STATUS.ACCEPTED_ONLINE,
    TRANSMISSION_STATUS.REJECTED,
    TRANSMISSION_STATUS.UNKNOWN_OUTCOME,
  ],
  [TRANSMISSION_STATUS.RETRY_SCHEDULED]: [TRANSMISSION_STATUS.QUEUED, TRANSMISSION_STATUS.DEAD_LETTER, TRANSMISSION_STATUS.BLOCKED],
  [TRANSMISSION_STATUS.UNKNOWN_OUTCOME]: [TRANSMISSION_STATUS.RECONCILIATION_QUEUED, TRANSMISSION_STATUS.MANUAL_REVIEW],
  [TRANSMISSION_STATUS.RECONCILIATION_QUEUED]: [TRANSMISSION_STATUS.RECONCILING],
  [TRANSMISSION_STATUS.RECONCILING]: [
    TRANSMISSION_STATUS.RECONCILED_ACCEPTED,
    TRANSMISSION_STATUS.RECONCILED_NOT_FOUND,
    TRANSMISSION_STATUS.MANUAL_REVIEW,
  ],
  [TRANSMISSION_STATUS.RECONCILED_NOT_FOUND]: [TRANSMISSION_STATUS.RETRY_SCHEDULED, TRANSMISSION_STATUS.MANUAL_REVIEW],
  [TRANSMISSION_STATUS.REJECTED]: [TRANSMISSION_STATUS.MANUAL_REVIEW, TRANSMISSION_STATUS.DEAD_LETTER],
  [TRANSMISSION_STATUS.MANUAL_REVIEW]: [TRANSMISSION_STATUS.DEAD_LETTER, TRANSMISSION_STATUS.RETRY_SCHEDULED],
  [TRANSMISSION_STATUS.OFFLINE_SIGNED]: [TRANSMISSION_STATUS.OFFLINE_QUEUED],
  [TRANSMISSION_STATUS.OFFLINE_QUEUED]: [TRANSMISSION_STATUS.OFFLINE_UPLOADING, TRANSMISSION_STATUS.BLOCKED],
  [TRANSMISSION_STATUS.OFFLINE_UPLOADING]: [
    TRANSMISSION_STATUS.ACCEPTED_OFFLINE,
    TRANSMISSION_STATUS.UNKNOWN_OUTCOME,
    TRANSMISSION_STATUS.REJECTED,
  ],
  [TRANSMISSION_STATUS.ACCEPTED_ONLINE]: [],
  [TRANSMISSION_STATUS.ACCEPTED_OFFLINE]: [],
  [TRANSMISSION_STATUS.RECONCILED_ACCEPTED]: [],
  [TRANSMISSION_STATUS.DEAD_LETTER]: [],
  [TRANSMISSION_STATUS.BLOCKED]: [TRANSMISSION_STATUS.QUEUED, TRANSMISSION_STATUS.MANUAL_REVIEW],
  [TRANSMISSION_STATUS.CANCELLED_BEFORE_SUBMISSION]: [],
  [TRANSMISSION_STATUS.SUPERSEDED]: [],
});

export const CONFIGURATION_TRANSITIONS = freezeMap({
  [CONFIGURATION_STATUS.RECEIVED]: [CONFIGURATION_STATUS.VALIDATING, CONFIGURATION_STATUS.REJECTED],
  [CONFIGURATION_STATUS.VALIDATING]: [
    CONFIGURATION_STATUS.VALID,
    CONFIGURATION_STATUS.INVALID,
    CONFIGURATION_STATUS.CONFLICT,
  ],
  [CONFIGURATION_STATUS.VALID]: [CONFIGURATION_STATUS.ACTIVE, CONFIGURATION_STATUS.SUPERSEDED],
  [CONFIGURATION_STATUS.ACTIVE]: [CONFIGURATION_STATUS.SUPERSEDED],
  [CONFIGURATION_STATUS.INVALID]: [CONFIGURATION_STATUS.REJECTED],
  [CONFIGURATION_STATUS.CONFLICT]: [CONFIGURATION_STATUS.REJECTED, CONFIGURATION_STATUS.SUPERSEDED],
  [CONFIGURATION_STATUS.REJECTED]: [],
  [CONFIGURATION_STATUS.SUPERSEDED]: [],
});

export function assertOperationalTransition(map, from, to, ErrorFactory = EisErrors.invalidTransition) {
  const allowed = map[from];
  if (!allowed || !allowed.has(to)) {
    throw ErrorFactory({
      currentStatus: from,
      message: `Invalid transition from ${from} to ${to}.`,
      details: { from, to },
    });
  }
}

export function transitionTerminal(from, to) {
  assertOperationalTransition(TERMINAL_TRANSITIONS, from, to, EisErrors.invalidTerminalTransition);
}

export function transitionSnapshot(from, to) {
  assertOperationalTransition(SNAPSHOT_TRANSITIONS, from, to);
}

export function transitionTransmission(from, to) {
  if (from === TRANSMISSION_STATUS.ACCEPTED_ONLINE || from === TRANSMISSION_STATUS.ACCEPTED_OFFLINE) {
    if (to === TRANSMISSION_STATUS.SENDING || to === TRANSMISSION_STATUS.QUEUED) {
      throw EisErrors.transmissionAccepted({ currentStatus: from });
    }
  }
  if (from === TRANSMISSION_STATUS.UNKNOWN_OUTCOME && to === TRANSMISSION_STATUS.RETRY_SCHEDULED) {
    throw EisErrors.unknownOutcomeRetry({ currentStatus: from });
  }
  assertOperationalTransition(TRANSMISSION_TRANSITIONS, from, to);
}

export function transitionConfiguration(from, to) {
  assertOperationalTransition(CONFIGURATION_TRANSITIONS, from, to);
}

export function assertOfflineCreationAllowed({ offlineCertified }) {
  if (!offlineCertified) {
    throw EisErrors.offlineNotCertified();
  }
}

export { OFFLINE_QUEUE_STATUS };
