/** Phase 5 — operational domain enums (control-plane enums remain in constants.js). */

export const TERMINAL_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  READINESS_INCOMPLETE: 'READINESS_INCOMPLETE',
  TAC_REQUIRED: 'TAC_REQUIRED',
  ACTIVATION_REQUEST_PENDING: 'ACTIVATION_REQUEST_PENDING',
  ACTIVATION_IN_PROGRESS: 'ACTIVATION_IN_PROGRESS',
  ACTIVATION_RESPONSE_RECEIVED: 'ACTIVATION_RESPONSE_RECEIVED',
  CREDENTIALS_PERSISTED: 'CREDENTIALS_PERSISTED',
  CONFIRMATION_PENDING: 'CONFIRMATION_PENDING',
  CONFIRMATION_IN_PROGRESS: 'CONFIRMATION_IN_PROGRESS',
  ACTIVE: 'ACTIVE',
  ACTIVATION_FAILED: 'ACTIVATION_FAILED',
  CONFIRMATION_FAILED: 'CONFIRMATION_FAILED',
  UNKNOWN_ACTIVATION_OUTCOME: 'UNKNOWN_ACTIVATION_OUTCOME',
  UNKNOWN_CONFIRMATION_OUTCOME: 'UNKNOWN_CONFIRMATION_OUTCOME',
  CREDENTIAL_STORAGE_FAILED: 'CREDENTIAL_STORAGE_FAILED',
  CONFIGURATION_BOOTSTRAP_FAILED: 'CONFIGURATION_BOOTSTRAP_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  CONFIGURATION_STALE: 'CONFIGURATION_STALE',
  REACTIVATION_REQUIRED: 'REACTIVATION_REQUIRED',
  BLOCKED: 'BLOCKED',
  REVOKED: 'REVOKED',
  INACTIVE: 'INACTIVE',
  ERROR: 'ERROR',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const ACTIVATION_ATTEMPT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  VALIDATING: 'VALIDATING',
  READY: 'READY',
  SENDING: 'SENDING',
  SENT_AWAITING_RESULT: 'SENT_AWAITING_RESULT',
  RESPONSE_RECEIVED: 'RESPONSE_RECEIVED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  CANCELLED: 'CANCELLED',
});

export const ACTIVATION_OUTCOME = Object.freeze({
  ACTIVATION_ACCEPTED: 'ACTIVATION_ACCEPTED',
  ACTIVATION_REJECTED_CORRECTABLE: 'ACTIVATION_REJECTED_CORRECTABLE',
  ACTIVATION_REJECTED_PERMANENT: 'ACTIVATION_REJECTED_PERMANENT',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  INVALID_TAC: 'INVALID_TAC',
  TAC_EXPIRED: 'TAC_EXPIRED',
  TAC_ALREADY_USED: 'TAC_ALREADY_USED',
  TERMINAL_ALREADY_ACTIVATED: 'TERMINAL_ALREADY_ACTIVATED',
  PRODUCT_NOT_APPROVED: 'PRODUCT_NOT_APPROVED',
  PRODUCT_VERSION_NOT_APPROVED: 'PRODUCT_VERSION_NOT_APPROVED',
  ENVIRONMENT_REJECTED: 'ENVIRONMENT_REJECTED',
  TEMPORARY_MRA_FAILURE: 'TEMPORARY_MRA_FAILURE',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const ACTIVATION_MODE = Object.freeze({
  MOCK: 'MOCK',
  SANDBOX: 'SANDBOX',
  CERTIFICATION: 'CERTIFICATION',
  PRODUCTION: 'PRODUCTION',
});

export const TERMINAL_SCOPE_TYPE = Object.freeze({
  BUSINESS: 'BUSINESS',
  BRANCH: 'BRANCH',
  SITE: 'SITE',
  POS_TILL: 'POS_TILL',
  SOFTWARE_INSTANCE: 'SOFTWARE_INSTANCE',
});

export const CREDENTIAL_TYPE = Object.freeze({
  TERMINAL_JWT: 'TERMINAL_JWT',
  TERMINAL_SECRET: 'TERMINAL_SECRET',
  ACTIVATION_CODE_EPHEMERAL: 'ACTIVATION_CODE_EPHEMERAL',
  BUYER_AUTHORIZATION_EPHEMERAL: 'BUYER_AUTHORIZATION_EPHEMERAL',
  SANDBOX_ACCESS: 'SANDBOX_ACCESS',
  OTHER_VERIFIED_TYPE: 'OTHER_VERIFIED_TYPE',
});

export const CREDENTIAL_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  EXPIRING: 'EXPIRING',
  EXPIRED: 'EXPIRED',
  ROTATED: 'ROTATED',
  REVOKED: 'REVOKED',
  INVALID: 'INVALID',
});

export const CONFIGURATION_TYPE = Object.freeze({
  GLOBAL: 'GLOBAL',
  TERMINAL: 'TERMINAL',
  TAXPAYER: 'TAXPAYER',
});

export const CONFIGURATION_STATUS = Object.freeze({
  RECEIVED: 'RECEIVED',
  VALIDATING: 'VALIDATING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  ACTIVE: 'ACTIVE',
  SUPERSEDED: 'SUPERSEDED',
  CONFLICT: 'CONFLICT',
  REJECTED: 'REJECTED',
});

export const MAPPING_STATUS = Object.freeze({
  UNMAPPED: 'UNMAPPED',
  SUGGESTED: 'SUGGESTED',
  MATCHED: 'MATCHED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  ACTIVE: 'ACTIVE',
  CONFLICT: 'CONFLICT',
  STALE: 'STALE',
  INACTIVE: 'INACTIVE',
  SUPERSEDED: 'SUPERSEDED',
  BLOCKED: 'BLOCKED',
  REQUIRES_MRA_APPROVAL: 'REQUIRES_MRA_APPROVAL',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

/** Phase 9 tax treatment types — zero-rated ≠ exempt ≠ VAT5 */
export const TAX_TREATMENT_TYPE = Object.freeze({
  STANDARD_RATED: 'STANDARD_RATED',
  ZERO_RATED: 'ZERO_RATED',
  EXEMPT: 'EXEMPT',
  RELIEF: 'RELIEF',
  VAT5_RELIEF: 'VAT5_RELIEF',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',
  OTHER_VERIFIED_TREATMENT: 'OTHER_VERIFIED_TREATMENT',
});

/** Phase 9 split-payment policy — fail closed until verified */
export const SPLIT_PAYMENT_POLICY = Object.freeze({
  VERIFIED_MULTI_PAYMENT_LINES: 'VERIFIED_MULTI_PAYMENT_LINES',
  VERIFIED_PRIMARY_PAYMENT_METHOD: 'VERIFIED_PRIMARY_PAYMENT_METHOD',
  VERIFIED_SEPARATE_PAYMENT_SUMMARY: 'VERIFIED_SEPARATE_PAYMENT_SUMMARY',
  UNSUPPORTED: 'UNSUPPORTED',
  REQUIRES_MRA_CLARIFICATION: 'REQUIRES_MRA_CLARIFICATION',
});

export const MRA_PAYMENT_CODE = Object.freeze({
  CASH: 'CASH',
  CARD: 'CARD',
  MOBILE_MONEY: 'MOBILE_MONEY',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CHEQUE: 'CHEQUE',
  CREDIT: 'CREDIT',
  VOUCHER: 'VOUCHER',
  OTHER: 'OTHER',
});

export const SNAPSHOT_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  VALIDATING: 'VALIDATING',
  MAPPINGS_RESOLVED: 'MAPPINGS_RESOLVED',
  NUMBER_RESERVED: 'NUMBER_RESERVED',
  CREATED: 'CREATED',
  QUEUED: 'QUEUED',
  FAILED: 'FAILED',
  SUPERSEDED: 'SUPERSEDED',
  CANCELLED_BEFORE_QUEUE: 'CANCELLED_BEFORE_QUEUE',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  FAILED_WITH_NUMBER_EVIDENCE: 'FAILED_WITH_NUMBER_EVIDENCE',
  // Phase 12 build lifecycle
  BUILDING: 'BUILDING',
  NUMBER_PENDING: 'NUMBER_PENDING',
  COMPLETED: 'COMPLETED',
  CONFLICT: 'CONFLICT',
  SOURCE_CHANGED: 'SOURCE_CHANGED',
  CANCELLED_BEFORE_COMPLETION: 'CANCELLED_BEFORE_COMPLETION',
});

export const SNAPSHOT_SOURCE_TYPE = Object.freeze({
  POS_SALE: 'POS_SALE',
  SALES_INVOICE: 'SALES_INVOICE',
  OTHER_VERIFIED_SALE_TYPE: 'OTHER_VERIFIED_SALE_TYPE',
});

export const TRANSMISSION_MODE = Object.freeze({
  ONLINE: 'ONLINE',
  CERTIFIED_OFFLINE: 'CERTIFIED_OFFLINE',
  TEST_SANDBOX: 'TEST_SANDBOX',
  HISTORICAL_CONTROLLED_SUBMISSION: 'HISTORICAL_CONTROLLED_SUBMISSION',
});

export const TRANSMISSION_STATUS = Object.freeze({
  CREATED: 'CREATED',
  QUEUED: 'QUEUED',
  CLAIMED: 'CLAIMED',
  VALIDATING: 'VALIDATING',
  SENDING: 'SENDING',
  SENT_AWAITING_RESULT: 'SENT_AWAITING_RESULT',
  ACCEPTED_ONLINE: 'ACCEPTED_ONLINE',
  REJECTED: 'REJECTED',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  RECONCILIATION_QUEUED: 'RECONCILIATION_QUEUED',
  RECONCILING: 'RECONCILING',
  RECONCILED_ACCEPTED: 'RECONCILED_ACCEPTED',
  RECONCILED_NOT_FOUND: 'RECONCILED_NOT_FOUND',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  DEAD_LETTER: 'DEAD_LETTER',
  OFFLINE_SIGNED: 'OFFLINE_SIGNED',
  OFFLINE_QUEUED: 'OFFLINE_QUEUED',
  OFFLINE_UPLOADING: 'OFFLINE_UPLOADING',
  ACCEPTED_OFFLINE: 'ACCEPTED_OFFLINE',
  BLOCKED: 'BLOCKED',
  CANCELLED_BEFORE_SUBMISSION: 'CANCELLED_BEFORE_SUBMISSION',
  SUPERSEDED: 'SUPERSEDED',
});

export const ATTEMPT_OUTCOME = Object.freeze({
  STARTED: 'STARTED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  PERMANENT_FAILURE: 'PERMANENT_FAILURE',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  CONTRACT_ERROR: 'CONTRACT_ERROR',
  SECURITY_ERROR: 'SECURITY_ERROR',
  CANCELLED: 'CANCELLED',
});

export const RETRY_CLASSIFICATION = Object.freeze({
  AUTOMATIC_RETRY: 'AUTOMATIC_RETRY',
  RECONCILE_BEFORE_RETRY: 'RECONCILE_BEFORE_RETRY',
  DATA_CORRECTION_REQUIRED: 'DATA_CORRECTION_REQUIRED',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
  NO_RETRY: 'NO_RETRY',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

/** Phase 15 — transmission reconciliation case states */
export const RECONCILIATION_CASE_STATUS = Object.freeze({
  CREATED: 'CREATED',
  VALIDATING_LOCAL_EVIDENCE: 'VALIDATING_LOCAL_EVIDENCE',
  LOCAL_EVIDENCE_INVALID: 'LOCAL_EVIDENCE_INVALID',
  RECONCILIATION_CONTRACT_PENDING: 'RECONCILIATION_CONTRACT_PENDING',
  READY_TO_QUERY_MRA: 'READY_TO_QUERY_MRA',
  QUERYING_MRA: 'QUERYING_MRA',
  MRA_RESPONSE_RECEIVED: 'MRA_RESPONSE_RECEIVED',
  COMPARING: 'COMPARING',
  ACCEPTED_CONFIRMED: 'ACCEPTED_CONFIRMED',
  REJECTED_CONFIRMED: 'REJECTED_CONFIRMED',
  DEFINITELY_NOT_PROCESSED: 'DEFINITELY_NOT_PROCESSED',
  DUPLICATE_CONFIRMED: 'DUPLICATE_CONFIRMED',
  MRA_AHEAD: 'MRA_AHEAD',
  LOCAL_AHEAD: 'LOCAL_AHEAD',
  CONFIGURATION_REFRESH_REQUIRED: 'CONFIGURATION_REFRESH_REQUIRED',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
  STILL_UNKNOWN: 'STILL_UNKNOWN',
  RETRY_ELIGIBLE: 'RETRY_ELIGIBLE',
  RETRY_AUTHORIZATION_PENDING: 'RETRY_AUTHORIZATION_PENDING',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  RETRY_IN_PROGRESS: 'RETRY_IN_PROGRESS',
  RECOVERED_ACCEPTED: 'RECOVERED_ACCEPTED',
  RECOVERED_REJECTED: 'RECOVERED_REJECTED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  DEAD_LETTER: 'DEAD_LETTER',
  COMPLETED: 'COMPLETED',
});

export const RECONCILIATION_OUTCOME = Object.freeze({
  ACCEPTED_CONFIRMED: 'ACCEPTED_CONFIRMED',
  REJECTED_CONFIRMED: 'REJECTED_CONFIRMED',
  DEFINITELY_NOT_PROCESSED: 'DEFINITELY_NOT_PROCESSED',
  DUPLICATE_ACCEPTED_CONFIRMED: 'DUPLICATE_ACCEPTED_CONFIRMED',
  DUPLICATE_WITHOUT_ACCEPTANCE_PROOF: 'DUPLICATE_WITHOUT_ACCEPTANCE_PROOF',
  MRA_AHEAD: 'MRA_AHEAD',
  LOCAL_AHEAD: 'LOCAL_AHEAD',
  CONFIGURATION_REFRESH_REQUIRED: 'CONFIGURATION_REFRESH_REQUIRED',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
  TARGET_NOT_RETURNED: 'TARGET_NOT_RETURNED',
  RESPONSE_WINDOW_INSUFFICIENT: 'RESPONSE_WINDOW_INSUFFICIENT',
  CONTRACT_MISMATCH: 'CONTRACT_MISMATCH',
  EVIDENCE_CONFLICT: 'EVIDENCE_CONFLICT',
  STILL_UNKNOWN: 'STILL_UNKNOWN',
  MANUAL_REVIEW_REQUIRED: 'MANUAL_REVIEW_REQUIRED',
});

export const DISPATCH_CERTAINTY = Object.freeze({
  DEFINITELY_NOT_PREPARED: 'DEFINITELY_NOT_PREPARED',
  PREPARED_NOT_DISPATCHED: 'PREPARED_NOT_DISPATCHED',
  DEFINITELY_NOT_SENT: 'DEFINITELY_NOT_SENT',
  DISPATCH_STARTED: 'DISPATCH_STARTED',
  REQUEST_BYTES_MAY_HAVE_LEFT_PROCESS: 'REQUEST_BYTES_MAY_HAVE_LEFT_PROCESS',
  REQUEST_CONFIRMED_SENT: 'REQUEST_CONFIRMED_SENT',
  RESPONSE_HEADERS_RECEIVED: 'RESPONSE_HEADERS_RECEIVED',
  COMPLETE_RESPONSE_RECEIVED: 'COMPLETE_RESPONSE_RECEIVED',
  RESPONSE_PERSISTED: 'RESPONSE_PERSISTED',
  DATABASE_ACKNOWLEDGEMENT_UNKNOWN: 'DATABASE_ACKNOWLEDGEMENT_UNKNOWN',
  WORKER_CRASH_AFTER_DISPATCH: 'WORKER_CRASH_AFTER_DISPATCH',
  UNKNOWN: 'UNKNOWN',
});

export const RETRY_AUTHORIZATION_STATE = Object.freeze({
  REQUESTED: 'REQUESTED',
  APPROVAL_PENDING: 'APPROVAL_PENDING',
  AUTHORIZED: 'AUTHORIZED',
  DENIED: 'DENIED',
  EXPIRED: 'EXPIRED',
  CONSUMED: 'CONSUMED',
  REVOKED: 'REVOKED',
});

export const CIRCUIT_BREAKER_STATE = Object.freeze({
  CLOSED: 'CLOSED',
  OPEN: 'OPEN',
  HALF_OPEN: 'HALF_OPEN',
  PROBING: 'PROBING',
  RECOVERING: 'RECOVERING',
  FORCED_OPEN: 'FORCED_OPEN',
  DISABLED_FOR_TEST_ONLY: 'DISABLED_FOR_TEST_ONLY',
});

export const FISCAL_ALLOCATION_STATUS = Object.freeze({
  RESERVED: 'RESERVED',
  ATTACHED_TO_SNAPSHOT: 'ATTACHED_TO_SNAPSHOT',
  RELEASE_PROHIBITED: 'RELEASE_PROHIBITED',
  ABANDONED_WITH_EVIDENCE: 'ABANDONED_WITH_EVIDENCE',
  SUPERSEDED_BY_APPROVED_PROCESS: 'SUPERSEDED_BY_APPROVED_PROCESS',
});

export const RECEIPT_EIS_STATUS = Object.freeze({
  LOCAL_FINALIZED: 'LOCAL_FINALIZED',
  EIS_NOT_REQUIRED: 'EIS_NOT_REQUIRED',
  EIS_PENDING: 'EIS_PENDING',
  EIS_FISCALIZING: 'EIS_FISCALIZING',
  EIS_ACCEPTED_ONLINE: 'EIS_ACCEPTED_ONLINE',
  EIS_SIGNED_OFFLINE: 'EIS_SIGNED_OFFLINE',
  EIS_REJECTED: 'EIS_REJECTED',
  EIS_UNKNOWN_OUTCOME: 'EIS_UNKNOWN_OUTCOME',
  EIS_BLOCKED: 'EIS_BLOCKED',
  EIS_MANUAL_REVIEW: 'EIS_MANUAL_REVIEW',
  // Phase 13 projection aliases (truthful UI)
  EIS_PAYLOAD_PENDING: 'EIS_PAYLOAD_PENDING',
  EIS_PAYLOAD_INVALID: 'EIS_PAYLOAD_INVALID',
  EIS_READY_FOR_SUBMISSION: 'EIS_READY_FOR_SUBMISSION',
  EIS_SUBMITTING: 'EIS_SUBMITTING',
  EIS_ACCEPTED: 'EIS_ACCEPTED',
  EIS_TEMPORARY_FAILURE: 'EIS_TEMPORARY_FAILURE',
  EIS_AUTHENTICATION_FAILURE: 'EIS_AUTHENTICATION_FAILURE',
  EIS_CONFIGURATION_REFRESH_REQUIRED: 'EIS_CONFIGURATION_REFRESH_REQUIRED',
  EIS_TERMINAL_BLOCKED: 'EIS_TERMINAL_BLOCKED',
  EIS_RECEIPT_GENERATION_PENDING: 'EIS_RECEIPT_GENERATION_PENDING',
  // Phase 14 receipt projection statuses (acceptance remains separate)
  EIS_ACCEPTED_RECEIPT_PENDING: 'EIS_ACCEPTED_RECEIPT_PENDING',
  EIS_RECEIPT_GENERATING: 'EIS_RECEIPT_GENERATING',
  EIS_RECEIPT_READY: 'EIS_RECEIPT_READY',
  EIS_RECEIPT_READY_WITH_WARNINGS: 'EIS_RECEIPT_READY_WITH_WARNINGS',
  EIS_RECEIPT_RENDER_FAILED: 'EIS_RECEIPT_RENDER_FAILED',
  EIS_RECEIPT_QR_INVALID: 'EIS_RECEIPT_QR_INVALID',
  EIS_RECEIPT_STORAGE_FAILED: 'EIS_RECEIPT_STORAGE_FAILED',
  EIS_RECEIPT_MANUAL_REVIEW: 'EIS_RECEIPT_MANUAL_REVIEW',
});

export const FISCAL_RECEIPT_STATUS = Object.freeze({
  CREATED: 'CREATED',
  VALIDATING_READINESS: 'VALIDATING_READINESS',
  BUILDING_RECEIPT_DATA: 'BUILDING_RECEIPT_DATA',
  QR_SOURCE_VALIDATING: 'QR_SOURCE_VALIDATING',
  QR_GENERATING: 'QR_GENERATING',
  RENDERING: 'RENDERING',
  STORING: 'STORING',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_WARNINGS: 'COMPLETED_WITH_WARNINGS',
  BLOCKED: 'BLOCKED',
  QR_INVALID: 'QR_INVALID',
  RENDER_FAILED: 'RENDER_FAILED',
  STORAGE_FAILED: 'STORAGE_FAILED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  SUPERSEDED_BY_LEGAL_REPLACEMENT: 'SUPERSEDED_BY_LEGAL_REPLACEMENT',
  LEGACY_READ_ONLY: 'LEGACY_READ_ONLY',
});

export const FISCAL_RECEIPT_ARTIFACT_TYPE = Object.freeze({
  HTML: 'HTML',
  POS_58MM_HTML: 'POS_58MM_HTML',
  POS_80MM_HTML: 'POS_80MM_HTML',
  POS_PRINT_PDF: 'POS_PRINT_PDF',
  SALES_INVOICE_A4_PDF: 'SALES_INVOICE_A4_PDF',
  QR_PNG: 'QR_PNG',
  QR_SVG: 'QR_SVG',
  EMAIL_HTML: 'EMAIL_HTML',
  EVIDENCE_JSON: 'EVIDENCE_JSON',
});

export const FISCAL_RECEIPT_CLASSIFICATION = Object.freeze({
  ORIGINAL_POS_FISCAL_RECEIPT: 'ORIGINAL_POS_FISCAL_RECEIPT',
  ORIGINAL_SALES_INVOICE_FISCAL_DOCUMENT: 'ORIGINAL_SALES_INVOICE_FISCAL_DOCUMENT',
  ORIGINAL_CREDIT_SALE_FISCAL_DOCUMENT: 'ORIGINAL_CREDIT_SALE_FISCAL_DOCUMENT',
  REPRINT_POS_FISCAL_RECEIPT: 'REPRINT_POS_FISCAL_RECEIPT',
  REPRINT_SALES_INVOICE_FISCAL_DOCUMENT: 'REPRINT_SALES_INVOICE_FISCAL_DOCUMENT',
  SANDBOX_FISCAL_RECEIPT: 'SANDBOX_FISCAL_RECEIPT',
  LEGACY_READ_ONLY_RECEIPT: 'LEGACY_READ_ONLY_RECEIPT',
  NON_FISCAL_LOCAL_RECEIPT: 'NON_FISCAL_LOCAL_RECEIPT',
  RECEIPT_GENERATION_PENDING: 'RECEIPT_GENERATION_PENDING',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const VAT5_STATUS = Object.freeze({
  REQUESTED: 'REQUESTED',
  VALIDATING: 'VALIDATING',
  VALID: 'VALID',
  INVALID: 'INVALID',
  EXPIRED: 'EXPIRED',
  RESERVED: 'RESERVED',
  PARTIALLY_CONSUMED: 'PARTIALLY_CONSUMED',
  CONSUMED: 'CONSUMED',
  RELEASED: 'RELEASED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const OFFLINE_QUEUE_STATUS = Object.freeze({
  ELIGIBILITY_CHECKED: 'ELIGIBILITY_CHECKED',
  SIGNING: 'SIGNING',
  SIGNED: 'SIGNED',
  RECEIPT_ISSUED: 'RECEIPT_ISSUED',
  QUEUED: 'QUEUED',
  UPLOAD_PENDING: 'UPLOAD_PENDING',
  UPLOADING: 'UPLOADING',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  AGE_LIMIT_EXCEEDED: 'AGE_LIMIT_EXCEEDED',
  AMOUNT_LIMIT_EXCEEDED: 'AMOUNT_LIMIT_EXCEEDED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  DEAD_LETTER: 'DEAD_LETTER',
  // Phase 16 extended states
  CREATED: 'CREATED',
  SEALED: 'SEALED',
  WAITING_FOR_CONNECTIVITY: 'WAITING_FOR_CONNECTIVITY',
  READY_FOR_UPLOAD: 'READY_FOR_UPLOAD',
  CLAIMED: 'CLAIMED',
  RESPONSE_RECEIVED: 'RESPONSE_RECEIVED',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  CONFIGURATION_REFRESH_REQUIRED: 'CONFIGURATION_REFRESH_REQUIRED',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
});

export const OFFLINE_CERTIFICATION_STATUS = Object.freeze({
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  NOT_STARTED: 'NOT_STARTED',
  DOCUMENTATION_PENDING: 'DOCUMENTATION_PENDING',
  ARCHITECTURE_REVIEW_PENDING: 'ARCHITECTURE_REVIEW_PENDING',
  SECURITY_REVIEW_PENDING: 'SECURITY_REVIEW_PENDING',
  SANDBOX_TESTING: 'SANDBOX_TESTING',
  MRA_TECHNICAL_REVIEW: 'MRA_TECHNICAL_REVIEW',
  CERTIFICATION_PENDING: 'CERTIFICATION_PENDING',
  CERTIFIED_SANDBOX: 'CERTIFIED_SANDBOX',
  CERTIFIED_PRODUCTION: 'CERTIFIED_PRODUCTION',
  CERTIFICATION_SUSPENDED: 'CERTIFICATION_SUSPENDED',
  CERTIFICATION_REVOKED: 'CERTIFICATION_REVOKED',
  CERTIFICATION_EXPIRED: 'CERTIFICATION_EXPIRED',
  REQUIRES_RECERTIFICATION: 'REQUIRES_RECERTIFICATION',
});

export const TRUSTED_AGENT_LIFECYCLE = Object.freeze({
  REGISTERED: 'REGISTERED',
  PROVISIONING: 'PROVISIONING',
  AWAITING_ACTIVATION: 'AWAITING_ACTIVATION',
  ACTIVE: 'ACTIVE',
  DEGRADED: 'DEGRADED',
  OFFLINE_ACTIVE: 'OFFLINE_ACTIVE',
  SYNCHRONIZING: 'SYNCHRONIZING',
  SUSPENDED: 'SUSPENDED',
  BLOCKED: 'BLOCKED',
  REVOKED: 'REVOKED',
  COMPROMISED: 'COMPROMISED',
  LOST: 'LOST',
  RETIRED: 'RETIRED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const TRUSTED_AGENT_TRUST = Object.freeze({
  UNVERIFIED: 'UNVERIFIED',
  VERIFIED: 'VERIFIED',
  ATTESTATION_PENDING: 'ATTESTATION_PENDING',
  ATTESTED: 'ATTESTED',
  ATTESTATION_FAILED: 'ATTESTATION_FAILED',
  TRUST_EXPIRED: 'TRUST_EXPIRED',
  COMPROMISED: 'COMPROMISED',
  REVOKED: 'REVOKED',
});

export const CONNECTIVITY_STATE = Object.freeze({
  ONLINE_STABLE: 'ONLINE_STABLE',
  ONLINE_DEGRADED: 'ONLINE_DEGRADED',
  CONNECTIVITY_UNCERTAIN: 'CONNECTIVITY_UNCERTAIN',
  OFFLINE_CANDIDATE: 'OFFLINE_CANDIDATE',
  OFFLINE_CONFIRMED: 'OFFLINE_CONFIRMED',
  OFFLINE_ACTIVE: 'OFFLINE_ACTIVE',
  RESTORATION_CANDIDATE: 'RESTORATION_CANDIDATE',
  ONLINE_RESTORED: 'ONLINE_RESTORED',
  SYNCHRONIZING: 'SYNCHRONIZING',
  SYNC_DEGRADED: 'SYNC_DEGRADED',
  BLOCKED: 'BLOCKED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const CLOCK_TRUST_STATE = Object.freeze({
  TRUSTED: 'TRUSTED',
  DRIFT_WARNING: 'DRIFT_WARNING',
  DRIFT_BLOCKED: 'DRIFT_BLOCKED',
  CLOCK_ROLLBACK_DETECTED: 'CLOCK_ROLLBACK_DETECTED',
  CLOCK_JUMP_DETECTED: 'CLOCK_JUMP_DETECTED',
  TIMEZONE_MISMATCH: 'TIMEZONE_MISMATCH',
  UNKNOWN: 'UNKNOWN',
});

export const OFFLINE_ENVELOPE_STATE = Object.freeze({
  CREATED: 'CREATED',
  BUILDING: 'BUILDING',
  VALIDATING: 'VALIDATING',
  SIGNING: 'SIGNING',
  SIGNATURE_VERIFYING: 'SIGNATURE_VERIFYING',
  SEALED: 'SEALED',
  QUEUED: 'QUEUED',
  UPLOADING: 'UPLOADING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
  CONFIGURATION_REFRESH_REQUIRED: 'CONFIGURATION_REFRESH_REQUIRED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const OFFLINE_DEPLOYMENT_ARCHITECTURE = Object.freeze({
  CENTRAL_SERVER_WITH_BRANCH_AGENT: 'CENTRAL_SERVER_WITH_BRANCH_AGENT',
  CENTRAL_SERVER_WITH_DEVICE_AGENT: 'CENTRAL_SERVER_WITH_DEVICE_AGENT',
  ON_PREMISE_BRANCH_NODE: 'ON_PREMISE_BRANCH_NODE',
  MANAGED_DESKTOP_POS_AGENT: 'MANAGED_DESKTOP_POS_AGENT',
  MANAGED_MOBILE_AGENT: 'MANAGED_MOBILE_AGENT',
  BROWSER_ONLY_PROHIBITED: 'BROWSER_ONLY_PROHIBITED',
  OTHER_CERTIFIED_ARCHITECTURE: 'OTHER_CERTIFIED_ARCHITECTURE',
});

export const RECON_TYPE = Object.freeze({
  ELIGIBILITY: 'ELIGIBILITY',
  SNAPSHOT: 'SNAPSHOT',
  TRANSMISSION: 'TRANSMISSION',
  LAST_ONLINE: 'LAST_ONLINE',
  LAST_OFFLINE: 'LAST_OFFLINE',
  FISCAL_NUMBER: 'FISCAL_NUMBER',
  AMOUNT: 'AMOUNT',
  VAT: 'VAT',
  PRODUCT_MAPPING: 'PRODUCT_MAPPING',
  CONFIGURATION: 'CONFIGURATION',
  RECEIPT_QR: 'RECEIPT_QR',
  QUEUE: 'QUEUE',
  DAILY_SUMMARY: 'DAILY_SUMMARY',
  TERMINAL_STATUS: 'TERMINAL_STATUS',
});

export const RECON_STATUS = Object.freeze({
  CREATED: 'CREATED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  COMPLETED_WITH_DIFFERENCES: 'COMPLETED_WITH_DIFFERENCES',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const SYNC_TYPE = Object.freeze({
  CONFIGURATION: 'CONFIGURATION',
  PRODUCTS: 'PRODUCTS',
  SERVICES: 'SERVICES',
  SITES: 'SITES',
  TAXES: 'TAXES',
  LEVIES: 'LEVIES',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  INITIAL_INVENTORY: 'INITIAL_INVENTORY',
  TERMINAL_STATUS: 'TERMINAL_STATUS',
});

export const SYNC_STATUS = Object.freeze({
  CREATED: 'CREATED',
  QUEUED: 'QUEUED',
  CLAIMED: 'CLAIMED',
  VALIDATING_READINESS: 'VALIDATING_READINESS',
  FETCHING_GLOBAL: 'FETCHING_GLOBAL',
  FETCHING_TERMINAL: 'FETCHING_TERMINAL',
  FETCHING_TAXPAYER: 'FETCHING_TAXPAYER',
  VALIDATING_RESPONSES: 'VALIDATING_RESPONSES',
  STORING_SNAPSHOTS: 'STORING_SNAPSHOTS',
  EXTRACTING_DERIVED_RULES: 'EXTRACTING_DERIVED_RULES',
  VALIDATING_CONFIGURATION_SET: 'VALIDATING_CONFIGURATION_SET',
  REVALIDATING_MAPPINGS: 'REVALIDATING_MAPPINGS',
  ACTIVATING: 'ACTIVATING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  COMPLETED_NO_CHANGES: 'COMPLETED_NO_CHANGES',
  COMPLETED_WITH_WARNINGS: 'COMPLETED_WITH_WARNINGS',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
  RETRY_SCHEDULED: 'RETRY_SCHEDULED',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  CONFLICT: 'CONFLICT',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  DEAD_LETTER: 'DEAD_LETTER',
});

/** Phase 8 configuration sync triggers */
export const CONFIG_SYNC_TRIGGER = Object.freeze({
  POST_ACTIVATION: 'POST_ACTIVATION',
  BEGINNING_OF_DAY: 'BEGINNING_OF_DAY',
  SCHEDULED: 'SCHEDULED',
  MANUAL: 'MANUAL',
  MRA_REQUESTED: 'MRA_REQUESTED',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
  WORKER_STARTUP: 'WORKER_STARTUP',
  APPLICATION_STARTUP: 'APPLICATION_STARTUP',
  TERMINAL_UNBLOCKED: 'TERMINAL_UNBLOCKED',
  TOKEN_ROTATED: 'TOKEN_ROTATED',
  CERTIFICATION_UPDATED: 'CERTIFICATION_UPDATED',
  SUPPORT_REQUESTED: 'SUPPORT_REQUESTED',
  RECOVERY: 'RECOVERY',
  MIGRATION_VERIFICATION: 'MIGRATION_VERIFICATION',
});

export const CONFIG_FRESHNESS_STATUS = Object.freeze({
  CURRENT: 'CURRENT',
  REFRESH_DUE: 'REFRESH_DUE',
  STALE: 'STALE',
  EXPIRED: 'EXPIRED',
  CONFLICT: 'CONFLICT',
  MISSING: 'MISSING',
  INVALID: 'INVALID',
  REFRESH_IN_PROGRESS: 'REFRESH_IN_PROGRESS',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const CONFIG_FETCH_OUTCOME = Object.freeze({
  ACCEPTED: 'ACCEPTED',
  NO_CHANGE: 'NO_CHANGE',
  REJECTED: 'REJECTED',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  PERMANENT_FAILURE: 'PERMANENT_FAILURE',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  CONTRACT_ERROR: 'CONTRACT_ERROR',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  CANCELLED: 'CANCELLED',
});

export const CONFIG_RESPONSE_OUTCOME = Object.freeze({
  CONFIGURATION_RECEIVED: 'CONFIGURATION_RECEIVED',
  CONFIGURATION_UNCHANGED: 'CONFIGURATION_UNCHANGED',
  CONFIGURATION_NOT_AVAILABLE: 'CONFIGURATION_NOT_AVAILABLE',
  CONFIGURATION_REJECTED: 'CONFIGURATION_REJECTED',
  AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
  TERMINAL_BLOCKED: 'TERMINAL_BLOCKED',
  TERMINAL_NOT_ACTIVE: 'TERMINAL_NOT_ACTIVE',
  CONFIGURATION_REFRESH_REQUIRED: 'CONFIGURATION_REFRESH_REQUIRED',
  TEMPORARY_MRA_FAILURE: 'TEMPORARY_MRA_FAILURE',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  VERSION_CONFLICT: 'VERSION_CONFLICT',
  CONTRACT_MISMATCH: 'CONTRACT_MISMATCH',
  UNKNOWN_OUTCOME: 'UNKNOWN_OUTCOME',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
});

export const MANUAL_REVIEW_STATUS = Object.freeze({
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  INVESTIGATING: 'INVESTIGATING',
  AWAITING_TENANT: 'AWAITING_TENANT',
  AWAITING_MRA: 'AWAITING_MRA',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
});

export const OUTBOX_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CLAIMED: 'CLAIMED',
  PROCESSED: 'PROCESSED',
  DEAD_LETTER: 'DEAD_LETTER',
  CANCELLED: 'CANCELLED',
});

export const EIS_OUTBOX_EVENT = Object.freeze({
  TERMINAL_STATE_CHANGED: 'MRA_EIS_TERMINAL_STATE_CHANGED',
  CONFIGURATION_SYNC_REQUESTED: 'MRA_EIS_CONFIGURATION_SYNC_REQUESTED',
  CONFIGURATION_ACTIVATED: 'MRA_EIS_CONFIGURATION_ACTIVATED',
  PRODUCT_SYNC_REQUESTED: 'MRA_EIS_PRODUCT_SYNC_REQUESTED',
  MAPPING_CHANGED: 'MRA_EIS_MAPPING_CHANGED',
  TAX_MAPPING_REVALIDATION_REQUESTED: 'MRA_EIS_TAX_MAPPING_REVALIDATION_REQUESTED',
  LEVY_MAPPING_REVALIDATION_REQUESTED: 'MRA_EIS_LEVY_MAPPING_REVALIDATION_REQUESTED',
  SITE_MAPPING_REVALIDATION_REQUESTED: 'MRA_EIS_SITE_MAPPING_REVALIDATION_REQUESTED',
  PAYMENT_MAPPING_REVALIDATION_REQUESTED: 'MRA_EIS_PAYMENT_MAPPING_REVALIDATION_REQUESTED',
  PRODUCT_MAPPING_REVALIDATION_REQUESTED: 'MRA_EIS_PRODUCT_MAPPING_REVALIDATION_REQUESTED',
  OFFLINE_READINESS_REVALIDATION_REQUESTED: 'MRA_EIS_OFFLINE_READINESS_REVALIDATION_REQUESTED',
  RECEIPT_POLICY_REBUILD_REQUESTED: 'MRA_EIS_RECEIPT_POLICY_REBUILD_REQUESTED',
  SNAPSHOT_REQUESTED: 'MRA_EIS_SNAPSHOT_REQUESTED',
  /** Phase 11 — references-only request for Phase 12 immutable fiscal snapshot */
  FISCAL_SNAPSHOT_REQUESTED: 'MRA_EIS_FISCAL_SNAPSHOT_REQUESTED',
  SNAPSHOT_CREATED: 'MRA_EIS_SNAPSHOT_CREATED',
  /** Phase 12 → Phase 13: references-only sales payload request */
  SALES_PAYLOAD_REQUESTED: 'MRA_EIS_SALES_PAYLOAD_REQUESTED',
  TRANSMISSION_QUEUED: 'MRA_EIS_TRANSMISSION_QUEUED',
  RECONCILIATION_REQUESTED: 'MRA_EIS_RECONCILIATION_REQUESTED',
  /** Phase 13 → Phase 14: accepted sale → receipt/QR work (references only) */
  ACCEPTED_RECEIPT_REQUESTED: 'MRA_EIS_ACCEPTED_RECEIPT_REQUESTED',
  /** Phase 13 → Phase 15: unknown/duplicate outcomes (references only) */
  TRANSMISSION_RECONCILIATION_REQUESTED: 'MRA_EIS_TRANSMISSION_RECONCILIATION_REQUESTED',
  RECEIPT_PROJECTION_UPDATE_REQUESTED: 'MRA_EIS_RECEIPT_PROJECTION_UPDATE_REQUESTED',
  OFFLINE_UPLOAD_REQUESTED: 'MRA_EIS_OFFLINE_UPLOAD_REQUESTED',
  MANUAL_REVIEW_OPENED: 'MRA_EIS_MANUAL_REVIEW_OPENED',
  ALERT_REQUESTED: 'MRA_EIS_ALERT_REQUESTED',
});

export const EXTERNAL_CATALOGUE_TYPE = Object.freeze({
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
});

export const MAPPING_TYPE = Object.freeze({
  PRODUCT_TO_PRODUCT: 'PRODUCT_TO_PRODUCT',
  SERVICE_TO_SERVICE: 'SERVICE_TO_SERVICE',
  APPROVED_PRODUCT_TO_SERVICE: 'APPROVED_PRODUCT_TO_SERVICE',
  APPROVED_SERVICE_TO_PRODUCT: 'APPROVED_SERVICE_TO_PRODUCT',
});
