import {
  ENTITLEMENT_STATUS,
  PARTICIPATION_STATUS,
  BUSINESS_OPS_STATUS,
} from './constants.js';
import { EisErrors } from './errors.js';

/**
 * Allowed entitlement transitions: from → Set(to)
 * Re-entitlement after REVOKED uses a new grant (NOT_ENTITLED → …), not resume.
 */
export const ENTITLEMENT_TRANSITIONS = Object.freeze({
  [ENTITLEMENT_STATUS.NOT_ENTITLED]: new Set([
    ENTITLEMENT_STATUS.ENTITLEMENT_PENDING,
    ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY,
    ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
  ]),
  [ENTITLEMENT_STATUS.ENTITLEMENT_PENDING]: new Set([
    ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY,
    ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
    ENTITLEMENT_STATUS.REVOKED,
    ENTITLEMENT_STATUS.NOT_ENTITLED,
  ]),
  [ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY]: new Set([
    ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
    ENTITLEMENT_STATUS.SUSPENDED,
    ENTITLEMENT_STATUS.REVOKED,
    ENTITLEMENT_STATUS.EXPIRED,
  ]),
  [ENTITLEMENT_STATUS.ENTITLED_PRODUCTION]: new Set([
    ENTITLEMENT_STATUS.SUSPENDED,
    ENTITLEMENT_STATUS.REVOKED,
    ENTITLEMENT_STATUS.EXPIRED,
  ]),
  [ENTITLEMENT_STATUS.SUSPENDED]: new Set([
    ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY,
    ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
    ENTITLEMENT_STATUS.REVOKED,
  ]),
  [ENTITLEMENT_STATUS.EXPIRED]: new Set([
    ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY,
    ENTITLEMENT_STATUS.ENTITLED_PRODUCTION,
    ENTITLEMENT_STATUS.REVOKED,
  ]),
  [ENTITLEMENT_STATUS.REVOKED]: new Set([]),
});

export const PARTICIPATION_TRANSITIONS = Object.freeze({
  [PARTICIPATION_STATUS.NOT_STARTED]: new Set([
    PARTICIPATION_STATUS.OPTED_IN,
    PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [PARTICIPATION_STATUS.OPTED_IN]: new Set([
    PARTICIPATION_STATUS.PAUSED,
    PARTICIPATION_STATUS.OPTED_OUT,
    PARTICIPATION_STATUS.DISABLING_AFTER_QUEUE,
    PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [PARTICIPATION_STATUS.PAUSED]: new Set([
    PARTICIPATION_STATUS.OPTED_IN,
    PARTICIPATION_STATUS.OPTED_OUT,
    PARTICIPATION_STATUS.DISABLING_AFTER_QUEUE,
    PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [PARTICIPATION_STATUS.DISABLING_AFTER_QUEUE]: new Set([
    PARTICIPATION_STATUS.OPTED_OUT,
    PARTICIPATION_STATUS.OPTED_IN,
    PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [PARTICIPATION_STATUS.OPTED_OUT]: new Set([
    PARTICIPATION_STATUS.OPTED_IN,
    PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [PARTICIPATION_STATUS.SUSPENDED_BY_SYSTEM]: new Set([
    PARTICIPATION_STATUS.OPTED_IN,
    PARTICIPATION_STATUS.PAUSED,
    PARTICIPATION_STATUS.OPTED_OUT,
    PARTICIPATION_STATUS.NOT_STARTED,
  ]),
});

export const BUSINESS_OPS_TRANSITIONS = Object.freeze({
  [BUSINESS_OPS_STATUS.UNAVAILABLE]: new Set([
    BUSINESS_OPS_STATUS.AVAILABLE,
    BUSINESS_OPS_STATUS.SETUP_REQUIRED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.AVAILABLE]: new Set([
    BUSINESS_OPS_STATUS.SETUP_REQUIRED,
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.SETUP_REQUIRED]: new Set([
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS]: new Set([
    BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION,
    BUSINESS_OPS_STATUS.SETUP_REQUIRED,
    BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
    BUSINESS_OPS_STATUS.ERROR,
  ]),
  [BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION]: new Set([
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED]: new Set([
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.DISABLING_AFTER_QUEUE,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.DEGRADED,
    BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
    BUSINESS_OPS_STATUS.ERROR,
  ]),
  [BUSINESS_OPS_STATUS.PAUSED]: new Set([
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION,
    BUSINESS_OPS_STATUS.DISABLING_AFTER_QUEUE,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.DISABLING_AFTER_QUEUE]: new Set([
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.DISABLED]: new Set([
    BUSINESS_OPS_STATUS.AVAILABLE,
    BUSINESS_OPS_STATUS.SETUP_REQUIRED,
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.DEGRADED]: new Set([
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
    BUSINESS_OPS_STATUS.ERROR,
  ]),
  [BUSINESS_OPS_STATUS.BLOCKED_BY_DEPENDENCY]: new Set([
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION,
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.ERROR]: new Set([
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.DISABLED,
    BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM,
  ]),
  [BUSINESS_OPS_STATUS.SUSPENDED_BY_SYSTEM]: new Set([
    BUSINESS_OPS_STATUS.AVAILABLE,
    BUSINESS_OPS_STATUS.SETUP_REQUIRED,
    BUSINESS_OPS_STATUS.SETUP_IN_PROGRESS,
    BUSINESS_OPS_STATUS.READY_FOR_ACTIVATION,
    BUSINESS_OPS_STATUS.OPERATIONALLY_ENABLED,
    BUSINESS_OPS_STATUS.PAUSED,
    BUSINESS_OPS_STATUS.DISABLED,
  ]),
});

export function assertTransition(map, from, to, { tenantId, businessId } = {}) {
  const allowed = map[from];
  if (!allowed || !allowed.has(to)) {
    throw EisErrors.invalidTransition({
      tenantId,
      businessId,
      currentStatus: from,
      message: `Invalid transition from ${from} to ${to}.`,
      details: { from, to },
    });
  }
}

export function assertEntitlementTransition(from, to, ctx) {
  assertTransition(ENTITLEMENT_TRANSITIONS, from, to, ctx);
}

export function assertParticipationTransition(from, to, ctx) {
  assertTransition(PARTICIPATION_TRANSITIONS, from, to, ctx);
}

export function assertBusinessOpsTransition(from, to, ctx) {
  assertTransition(BUSINESS_OPS_TRANSITIONS, from, to, ctx);
}

/** Resume after suspension must restore prior entitled state only. */
export function resolveResumeEntitlementStatus(priorStatus) {
  if (
    priorStatus === ENTITLEMENT_STATUS.ENTITLED_PRODUCTION ||
    priorStatus === ENTITLEMENT_STATUS.ENTITLED_SANDBOX_ONLY
  ) {
    return priorStatus;
  }
  throw EisErrors.invalidTransition({
    currentStatus: ENTITLEMENT_STATUS.SUSPENDED,
    message: 'Cannot resume: prior entitlement status is unknown or invalid.',
    details: { priorStatus },
  });
}
